// packages/web-components/src/components/content-item-horizontal/content-item-horizontal.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSContentItem from '../content-item/content-item';
import styles from './content-item-horizontal.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * A component to present a content in a horizontal orientation.
 *
 * @element dds-content-item-horizontal
 */
@customElement(`${ddsPrefix}-content-item-horizontal`)
class DDSContentItemHorizontal extends DDSContentItem {
  render() {
    return html`
      <div class="${prefix}--content-item-horizontal__row">
        <div class="${prefix}--content-item-horizontal__col ${prefix}--content-item-horizontal__col--1">
          <div class="${prefix}--content-item-horizontal__heading-wrapper">
            <slot name="eyebrow" @slotchange="${this._handleSlotChange}"></slot>
            <slot name="heading"></slot>
          </div>
          <div class="${prefix}--content-item-horizontal__content-wrapper">
            ${this._renderBody()}${this._renderFooter()}
          </div>
        </div>
        <div class="${prefix}--content-item-horizontal__col ${prefix}--content-item-horizontal__col--2">
          <slot name="thumbnail" @slotchange="${this._handleSlotChange}"></slot>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-item-horizontal`;
  }

  static styles = styles;
}

export default DDSContentItemHorizontal;

// packages/react/src/patterns/sub-patterns/ContentItemHorizontal/ContentItemHorizontal.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Content } from 'carbon-components-react';
import { CTA } from '../../../components/CTA';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { markdownToHtml } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * ContentItemHorizontal Pattern
 *
 * @param {object} props props object
 * @param {Array} props.items items array
 *
 * @returns {*} JSX ContentItemHorizontal pattern
 */
const ContentItemHorizontal = ({ items }) => (
  <div
    className={`${prefix}--content-item-horizontal`}
    data-autoid={`${stablePrefix}--content-item-horizontal`}>
    {items.map((item, index) => {
      return (
        <div className={`${prefix}--content-item-horizontal__container`}>
          <div
            className={`${prefix}---content-item-horizontal__row ${prefix}--content-item-horizontal__item`}
            key={index}>
            <div className={`${prefix}--content-item-horizontal__col`}>
              <p>{item.eyebrow}</p>
              <h3
                className={`${prefix}--content-item-horizontal__item--heading`}>
                {item.heading}
              </h3>
            </div>
            <div className={`${prefix}--content-item-horizontal__col`}>
              <p>{item.copy}</p>
              <CTA
                style="text"
                {...item.cta}
                customClassName={`${prefix}--card__cta`}
              />
            </div>
          </div>
        </div>
      );
    })}
  </div>
);

ContentItemHorizontal.propTypes = {
  items: PropTypes.array,
};

export default ContentItemHorizontal;
