// packages/react/src/patterns/sub-patterns/Callout/Callout.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 *
 * @param {object} children jsx component
 * @returns {*} callout with child object
 */
const Callout = ({ children }) => (
  <section
    className={`${prefix}--callout__container`}
    data-autoid={`${stablePrefix}--callout__container`}>
    <div
      className={`${prefix}--callout__column`}
      data-autoid={`${stablePrefix}--callout__column`}>
      <div
        className={`${prefix}--callout__content`}
        data-autoid={`${stablePrefix}--callout__content`}>
        {children}
      </div>
    </div>
  </section>
);

Callout.propTypes = {
  children: PropTypes.object,
};

export default Callout;

// packages/web-components/src/components/callout/callout.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { customElement, html, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './callout.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Callout.
 *
 * @element dds-callout
 */
@customElement(`${ddsPrefix}-callout`)
class DDSCallout extends LitElement {
  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader

  static get stableSelector() {
    return `${ddsPrefix}--callout`;
  }

  render() {
    return html`
      <div class="${prefix}--callout__column">
        <div class="${prefix}--callout__content">
          <slot></slot>
        </div>
      </div>
    `;
  }
}

export default DDSCallout;
