// packages/react/src/patterns/blocks/ContentBlockSegmented/ContentBlockSegmented.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ContentBlock } from '../../sub-patterns/ContentBlock';
import { ContentGroup } from '../../sub-patterns/ContentGroup';
import { ContentItem } from '../../sub-patterns/ContentItem';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { Image } from '../../../components/Image';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content Block - Simple pattern
 *
 * @param {object} props props object
 * @param {string} props.heading content block heading
 * @param {string} props.copy content block short copy to support the heading
 * @param {object} props.cta content block cta
 * @param {Array} props.image content block intro image
 * @param {Array} props.items content block content items
 * @returns {*} Content Block - Segmented pattern
 */
const ContentBlockSegmented = ({ copy, cta, heading, image, items }) => {
  return (
    <ContentBlock
      heading={heading}
      copy={copy}
      cta={cta}
      customClassName={`${prefix}--content-block-segmented`}>
      <div data-autoid={`${stablePrefix}--content-block-segmented`}>
        {image && (
          <Image
            classname={`${prefix}--content-block-segmented__image`}
            {...image}
          />
        )}
        {_renderGroup(items)}
      </div>
    </ContentBlock>
  );
};

/**
 *
 * @param {object} items content item data
 * @returns {*} JSX Component with the media
 */
const _renderGroup = items =>
  items.map((item, index) => (
    <ContentGroup heading={item.heading} key={index}>
      <div
        data-autoid={`${stablePrefix}--content-block-segmented__content-group`}>
        <ContentItem copy={item.copy} key={index} />
        {item.image && (
          <div data-autoid={`${stablePrefix}--content-block-segmented__media`}>
            <Image {...item.image} />
          </div>
        )}
      </div>
    </ContentGroup>
  ));

ContentBlockSegmented.propTypes = {
  heading: PropTypes.string.isRequired,
  copy: PropTypes.string.isRequired,
  cta: PropTypes.object,
  image: PropTypes.array,
  items: PropTypes.array.isRequired,
};

export default ContentBlockSegmented;

// packages/web-components/src/components/content-block-segmented/content-block-segmented.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { css, html, Part } from 'lit';
import { customElement } from 'lit/decorators.js';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import DDSContentBlock, {
  CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME,
} from '../content-block/content-block';
import styles from './content-block-segmented.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Simple version of content block.
 *
 * @element dds-content-block-segmented
 */
@customElement(`${ddsPrefix}-content-block-segmented`)
class DDSContentBlockSegmented extends DDSContentBlock {
  protected _getContainerClasses(): string | ((part: Part) => void) {
    const {
      complementaryStyleScheme,
      _hasComplementary: hasComplementary,
      _hasContent: hasContent,
      _hasCopy: hasCopy,
      _hasHeading: hasHeading,
      _hasMedia: hasMedia,
    } = this;
    return classMap({
      [`${prefix}--content-layout`]: true,
      [`${prefix}--content-layout--with-complementary`]: hasComplementary,
      [`${ddsPrefix}-ce--content-layout--with-adjacent-heading-content`]:
        hasHeading && hasContent && !hasCopy && !hasMedia,
      [`${prefix}--layout--border`]:
        complementaryStyleScheme ===
        CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.WITH_BORDER,
    });
  }

  protected _renderInnerBody() {
    return html` ${this._renderMedia()}${this._renderContent()} `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-segmented`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentBlockSegmented;
