// packages/react/src/patterns/sub-patterns/ButtonGroup/ButtonGroup.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { Button } from 'carbon-components-react';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * renders the buttons
 *
 * @param {object} props props object
 * @param {Array.<{copy: string}>} props.buttons array of buttons
 * @param {string} props.buttons[].copy Button copy
 * @param {string} props.buttons[].href URL for the button item
 * @param {object} props.buttons[].renderIcon Optional icon type
 * @returns {*} button components
 */
const ButtonGroup = ({ buttons }) => {
  console.log('buttons', buttons);
  return (
    <ol
      className={`${prefix}--buttongroup`}
      data-autoid={`${stablePrefix}--button-group`}>
      {buttons.map((button, key) => {
        return (
          <li key={key} className={`${prefix}--buttongroup-item`}>
            <Button
              tabIndex={key === 0 ? 2 : 1}
              data-autoid={`${stablePrefix}--button-group-${key}`}
              {...button}
              kind={key === 0 ? 'primary' : 'tertiary'}>
              {button.copy}
            </Button>
          </li>
        );
      })}
    </ol>
  );
};

ButtonGroup.propTypes = {
  buttons: PropTypes.arrayOf(
    PropTypes.shape({
      copy: PropTypes.string.isRequired,
      href: PropTypes.string.isRequired,
      renderIcon: PropTypes.element,
    })
  ),
};

export default ButtonGroup;

// packages/web-components/src/components/button-group/button-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { customElement, html, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import sameHeight from '@carbon/ibmdotcom-utilities/es/utilities/sameHeight/sameHeight';
import styles from './button-group.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

export enum BUTTON_TYPES {
  /**
   * Default / Primary
   */
  DEFAULT = 'primary',

  /**
   * Alternate / Tertiary
   */
  ALTERNATE = 'tertiary',
}

/**
 * Button group.
 *
 * @element dds-button-group
 */
@customElement(`${ddsPrefix}-button-group`)
class DDSButtonGroup extends LitElement {
  static get stableSelector() {
    return `${ddsPrefix}--button-group`;
  }

  static get buttonGroupItemSelector() {
    return `${ddsPrefix}-button-group-item`;
  }

  render() {
    return html`
      <slot @slotchange="${this._handleSlotChange}"></slot>
    `;
  }

  connectedCallback() {
    super.connectedCallback();
    this.setAttribute('role', 'list');
  }

  /**
   * Handler for @slotchange, set the first button-group-item to kind tertiary and primary for the remaining ones
   *
   * @private
   */
  private _handleSlotChange(event: Event) {
    const childItems = (event.target as HTMLSlotElement)
      .assignedNodes()
      .filter(elem =>
        (elem as HTMLElement).matches !== undefined
          ? (elem as HTMLElement).matches((this.constructor as typeof DDSButtonGroup).buttonGroupItemSelector)
          : false
      );

    childItems.forEach((elem, index) => {
      (elem as HTMLElement).setAttribute('kind', index !== childItems.length - 1 ? BUTTON_TYPES.ALTERNATE : BUTTON_TYPES.DEFAULT);
    });

    setTimeout(() => {
      sameHeight(childItems, 'md');
    });
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSButtonGroup;
