// packages/react/src/components/DotcomShell/__stories__/data/content.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* eslint-disable jsx-a11y/anchor-is-valid, jsx-a11y/anchor-has-content */
import {
  CalloutQuote,
  CalloutWithMedia,
  ContentBlockCards,
  ContentBlockSegmented,
  ContentGroupHorizontal,
  CTASection,
  Layout,
  LeadSpaceBlock,
  LogoGrid,
  FeatureCard,
  TableOfContents,
} from '../../../../index';

import { ArrowRight20 } from '@carbon/icons-react';
import imgLg16x9 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--003.jpg';
import imgLg16x9_2 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--004.jpg';
import imgLg1x1 from '../../../../../../storybook-images/assets/720/fpo--1x1--720x720--004.jpg';
import imgMd16x9 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--003.jpg';
import imgMd16x9_2 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--004.jpg';
import imgSm16x9 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--003.jpg';
import imgSm16x9_2 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--004.jpg';
import imgSm1x1 from '../../../../../../storybook-images/assets/320/fpo--1x1--320x320--001.jpg';
import imgXlg4x3 from '../../../../../../storybook-images/assets/1312/fpo--4x3--1312x984--002.jpg';
import React from 'react';

/**
 * DDS patterns template
 *
 * @returns {*} JSX for Learn template
 */
const Content = () => (
  <>
    <TableOfContents menuLabel="Jump to" theme="white" stickyOffset="48">
      <a name="section-1" data-title="Lorem ipsum dolor sit amet" />
      <Layout type="2-1">
        <div>
          <LeadSpaceBlock
            title="Lorem ipsum dolor sit amet"
            copy="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
            heading="Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut."
            mediaType="video"
            mediaData={{
              videoId: '1_9h94wo6b',
              showDescription: true,
            }}
            items={{
              heading: 'Featured products',
              items: [
                {
                  type: 'local',
                  copy: 'IBM Cloud Continuous Delivery',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
                {
                  type: 'local',
                  copy: 'UrbanCode',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
                {
                  type: 'local',
                  copy: 'View all products',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
              ],
            }}
            cta={{
              style: 'button',
              type: 'local',
              buttons: [
                {
                  type: 'local',
                  copy: 'Excepteur sint occaecat',
                  href: 'https://example.com/',
                },
              ],
            }}
          />
        </div>
        <></>
      </Layout>

      <a
        name="section-2"
        data-title="Pharetra pharetra massa massa ultricies mi quis."
      />
      <ContentBlockSegmented
        heading="Pharetra pharetra massa massa ultricies mi quis."
        items={[
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
          },
        ]}
      />
      <FeatureCard
        card={{
          eyebrow: 'scelerisque purus',
          heading: 'Elementum nibh tellus molestie nunc?',
          copy:
            'Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbi tristique.',
          cta: {
            href: 'https://example.com',
            icon: {
              src: ArrowRight20,
            },
          },
          image: {
            defaultSrc: imgLg1x1,
            alt: 'Image alt text',
          },
        }}
        size={'large'}
      />

      <a
        name="section-3"
        data-title="Elementum nibh tellus molestie nunc non"
      />
      <ContentBlockSegmented
        heading="Elementum nibh tellus molestie nunc non."
        items={[
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            image: {
              heading: 'Mauris iaculis eget dolor nec hendrerit.',
              image: {
                sources: [
                  {
                    src: imgSm16x9,
                    breakpoint: 320,
                  },
                  {
                    src: imgMd16x9,
                    breakpoint: 400,
                  },
                  {
                    src: imgLg16x9,
                    breakpoint: 672,
                  },
                ],
                alt: 'Image alt text',
                defaultSrc: imgLg16x9,
              },
            },
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            image: {
              heading: 'Mauris iaculis eget dolor nec hendrerit.',
              image: {
                sources: [
                  {
                    src: imgSm16x9_2,
                    breakpoint: 320,
                  },
                  {
                    src: imgMd16x9_2,
                    breakpoint: 400,
                  },
                  {
                    src: imgLg16x9_2,
                    breakpoint: 672,
                  },
                ],
                alt: 'Image alt text',
                defaultSrc: imgLg16x9_2,
              },
            },
          },
        ]}
        cta={{
          style: 'card',
          disableImage: true,
          type: 'video',
          media: {
            src: '1_9h94wo6b',
            type: 'video',
          },
        }}
        mediaType="image"
      />

      <CalloutWithMedia
        heading="Mauris ultrices eros in cursus"
        copy="Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada proin libero nunc consequat. In est ante in nibh mauris cursus mattis. Turpis tincidunt id aliquet risus feugiat in. Vel facilisis volutpat est velit egestas dui."
        mediaType="video"
        mediaData={{
          videoId: '1_9h94wo6b',
        }}
      />

      <a name="section-4" data-title="Tincidunt ornare massa" />
      <ContentGroupHorizontal
        heading="Tincidunt ornare massa"
        items={[
          {
            eyebrow: 'Lorem ipsum',
            heading: 'Aliquam condimentum',
            copy:
              'Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin.',
            cta: {
              heading: 'Aliquam condimentum',
              items: [
                {
                  type: 'local',
                  copy: 'Link text',
                  href: 'https://example.com',
                },
                {
                  type: 'external',
                  copy: 'External link text',
                  href: 'https://example.com',
                },
              ],
            },
          },
          {
            eyebrow: 'Lorem ipsum',
            heading: 'Aliquam condimentum',
            copy:
              'Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin.',
            cta: {
              heading: 'Aliquam condimentum',
              items: [
                {
                  type: 'local',
                  copy: 'Link text',
                  href: 'https://example.com',
                },
                {
                  type: 'external',
                  copy: 'External link text',
                  href: 'https://example.com',
                },
              ],
            },
          },
        ]}
      />

      <a name="section-5" data-title="Lobortis elementum nibh tellus" />
      <LogoGrid
        heading="Lobortis elementum nibh tellus"
        logosGroup={[
          {
            title: 'Company A',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company B',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company C',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company D',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company E',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company F',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
        ]}
        ctaCopy="Amet justo donec"
        ctaHref="https://www.example.com"
      />

      <a name="section-6" data-title="Aliquam condimentum interdum" />
      <ContentBlockCards
        heading="Aliquam condimentum interdum"
        cards={[
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
        ]}
      />
      <a name="section-7" data-title="Duis aute irure dolor in reprehenderit" />
      <CalloutQuote
        quote={{
          copy: 'Duis aute irure dolor in reprehenderit',
          source: {
            heading: 'Lorem ipsum',
            copy: 'dolor sit amet',
          },
          cta: {
            copy: 'Link with Icon',
            type: 'local',
            href: 'https://example.com',
          },
        }}
      />
    </TableOfContents>
    <div className="bx--grid" style={{ backgroundColor: '#f4f4f4' }}>
      <div className="bx--row">
        <div className="bx--col-sm-4 bx--col-lg-12 bx--offset-lg-4">
          <CTASection
            theme="g10"
            cta={{
              style: 'button',
              type: 'local',
              buttons: [
                {
                  type: 'local',
                  copy: 'Contact sales',
                  href: 'https://example.com/',
                },
              ],
            }}
            items={[
              {
                heading: 'Get connected',
                copy:
                  'IBM DevOps partners have a wide range of expertise. Find one to build the right solution for you.',
                cta: {
                  copy: 'Find a partner',
                  type: 'local',
                  href: 'https://example.com/',
                },
              },
              {
                heading: 'Learn how',
                copy:
                  'Dig into more self-directed learning about DevOps methodologies.',
                cta: {
                  copy: 'Browse tutorials',
                  type: 'local',
                  href: 'https://example.com/',
                },
              },
            ]}
            heading="Take the next step"
            copy="Want to discuss your options with a DevOps expert? Contact our sales team to evaluate your needs."
          />
        </div>
      </div>
    </div>
  </>
);

export default Content;

// packages/web-components/src/components/content-block/__stories__/data/content.js
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit-element';
import imgLg1x1 from '../../../../../.storybook/storybook-images/assets/960/fpo--1x1--960x960--006.jpg';
import imgLg16x9 from '../../../../../.storybook/storybook-images/assets/720/fpo--16x9--720x405--005.jpg';
import imgXlg16x9 from '../../../../../.storybook/storybook-images/assets/1312/fpo--16x9--1312x738--005.jpg';
import imgMd16x9 from '../../../../../.storybook/storybook-images/assets/960/fpo--16x9--960x540--005.jpg';
import imgLg4x3 from '../../../../../.storybook/storybook-images/assets/720/fpo--4x3--720x540--004.jpg';
import imgSm4x3 from '../../../../../.storybook/storybook-images/assets/480/fpo--4x3--480x360--005.jpg';
import ArrowRight20 from '@carbon/web-components/es/icons/arrow--right/20.js';

export const cardGroupItem1 = html`
  <c4d-card-group-item href="https://www.example.com">
    <c4d-card-heading>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    </c4d-card-heading>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
    </p>
    <c4d-card-footer icon-placement="left">
      ${ArrowRight20({ slot: 'icon' })}
    </c4d-card-footer>
  </c4d-card-group-item>
`;

export const cardGroupItem2 = html`
  <c4d-card-group-item href="https://www.example.com">
    <c4d-card-heading>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    </c4d-card-heading>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
    <c4d-card-footer icon-placement="left">
      ${ArrowRight20({ slot: 'icon' })}
    </c4d-card-footer>
  </c4d-card-group-item>
`;

export const card = (heading) => html`
  <c4d-card slot="footer" cta-type="local" href="https://www.example.com">
    <c4d-card-heading>${heading} processing</c4d-card-heading>
    <c4d-card-footer></c4d-card-footer>
  </c4d-card>
`;

export const imageCard = html`
  <c4d-card href="http://www.example.com" cta-type="local">
    <c4d-card-heading>Lorem ipsum dolor sit atemt</c4d-card-heading>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et
      ultricies est.
    </p>
    <c4d-image slot="image" alt="example image" default-src="${imgLg4x3}">
    </c4d-image>
    <c4d-card-footer></c4d-card-footer>
  </c4d-card>
`;

export const videoCard = html`
  <c4d-video-cta-container>
    <c4d-card cta-type="video" href="0_ibuqxqbe">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et
        ultricies est.
      </p>
      <c4d-card-footer> </c4d-card-footer>
    </c4d-card>
  </c4d-video-cta-container>
`;

export const currentComponents = [
  'Callout quote',
  'Callout with media',
  'Card group',
  'Card in card',
  'Carousel',
  'Content group',
  'Content item row',
  'Content item',
  'Feature card',
  'Image',
  'Link list',
  'Quote',
  'Structured list',
  'Tabs extended',
  'Video player',
];

export const image = html`
  <c4d-image
    alt="Image alt text"
    default-src="${imgLg16x9}"
    heading="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
  </c4d-image>
`;

export const calloutQuote = html`
  <c4d-callout-quote mark-type="double-curved" color-scheme="regular">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus est purus,
    posuere at est vitae, ornare rhoncus sem. Suspendisse vitae tellus
    fermentum, hendrerit augue eu, placerat magna.
    <c4d-quote-source-heading
      >Lorem ipsum dolor sit amet</c4d-quote-source-heading
    >
    <c4d-quote-source-copy> consectetur adipiscing elit </c4d-quote-source-copy>
    <c4d-quote-source-bottom-copy> IBM Cloud </c4d-quote-source-bottom-copy>
    <c4d-callout-link-with-icon
      slot="footer"
      href="https://example.com"
      cta-type="local">
      Link with icon
    </c4d-callout-link-with-icon>
  </c4d-callout-quote>
`;

export const calloutWithMedia = html`
  <c4d-callout-with-media color-scheme="regular">
    <c4d-content-block-heading
      >Curabitur malesuada varius mi eu posuere</c4d-content-block-heading
    >
    <c4d-callout-with-media-copy size="sm"
      >${`Lorem ipsum *dolor* sit amet, consectetur adipiscing elit. Aenean et ultricies est.
      Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin, sodales
      nulla quis, *consequat* libero. Here are
      some common categories:`}</c4d-callout-with-media-copy
    >
    <c4d-callout-with-media-image
      alt="Image alt text"
      default-src="${imgLg16x9}"
      heading="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
    </c4d-callout-with-media-image>
  </c4d-callout-with-media>
`;

export const cardGroup = html`
  <c4d-card-group>
    ${cardGroupItem1}${cardGroupItem2}${cardGroupItem1}
    ${cardGroupItem2}${cardGroupItem1}${cardGroupItem2}
  </c4d-card-group>
`;

export const cardInCard = html`
  <c4d-card-in-card href="https://example.com" cta-type="local">
    <c4d-card-in-card-image slot="image" default-src="${imgLg16x9}">
      <c4d-image-item media="(min-width: 1312px)" srcset="${imgXlg16x9}">
      </c4d-image-item>
      <c4d-image-item media="(min-width: 672px)" srcset="${imgMd16x9}">
      </c4d-image-item>
      <c4d-image-item media="(min-width: 320px)" srcset="${imgSm4x3}">
      </c4d-image-item>
    </c4d-card-in-card-image>
    <c4d-card-eyebrow>Label</c4d-card-eyebrow>
    <c4d-card-heading
      >Standard Bank Group prepares to embrace Africa’s AI
      opportunity</c4d-card-heading
    >
    <c4d-card-footer></c4d-card-footer>
  </c4d-card-in-card>
`;

export const carousel = html`
  <c4d-carousel>
    ${imageCard}${videoCard}${imageCard}${videoCard}${imageCard}${videoCard}
  </c4d-carousel>
`;

export const contentBlock = html`
  <c4d-content-block>
    <c4d-content-block-heading
      >What is the latest news in artificial
      intelligence?</c4d-content-block-heading
    >
    <c4d-content-block-copy
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quam ante,
      mattis id pellentesque at, molestie et ipsum. Proin sodales est hendrerit
      maximus malesuada. Orci varius natoque penatibus et magnis dis parturient
      montes, nascetur ridiculus mus. Etiam at arcu ligula. Praesent faucibus
      est ligula, vitae finibus ante aliquet a.</c4d-content-block-copy
    >
    <c4d-card slot="footer" cta-type="local" href="https://www.example.com">
      <c4d-card-heading>Learn more about natural processing</c4d-card-heading>
      <c4d-card-footer></c4d-card-footer>
    </c4d-card>
  </c4d-content-block>
`;

export const contentGroup = html`
  <c4d-content-group>
    <c4d-content-group-heading
      >Natural language processing (NLP)</c4d-content-group-heading
    >
    <c4d-content-group-copy
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quam ante,
      mattis id pellentesque at, molestie et ipsum. Proin sodales est hendrerit
      maximus malesuada. Orci varius natoque penatibus et magnis dis parturient
      montes, nascetur ridiculus mus. Etiam at arcu ligula. Praesent faucibus
      est ligula, vitae finibus ante aliquet a.
    </c4d-content-group-copy>
    ${card(`Learn more about natual language processing`)}
  </c4d-content-group>
`;

export const contentItem = html`
  <c4d-content-item>
    <c4d-content-item-heading
      >Natural language understanding</c4d-content-item-heading
    >
    <c4d-content-item-copy
      >${`This area of NLP takes “real world” text and applies a symbolic system
     for a machine to interpret its meaning, using formal logic; structures that describe the various
     relationships between concepts (ontologies); and other semantic tools.`}</c4d-content-item-copy
    >
    <c4d-link-with-icon
      slot="footer"
      cta-type="local"
      href="https://www.example.com">
      Learn more about NLP</c4d-link-with-icon
    >
  </c4d-content-item>
`;

export const contentItemRow = ({
  thumbnail = false,
  image = false,
} = {}) => html`
  <c4d-content-item-row ?thumbnail=${thumbnail}>
    ${image
      ? html`<c4d-image
          slot="media"
          alt="Alt text"
          default-src="${imgLg16x9}"></c4d-image>`
      : ''}
    <c4d-content-item-row-eyebrow>Lorem ipsum</c4d-content-item-row-eyebrow>
    <c4d-content-item-heading>Aliquam condimentum</c4d-content-item-heading>
    <c4d-content-item-row-copy
      >Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Aenean et
      ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit
      sollicitudin.</c4d-content-item-row-copy
    >
    <c4d-link-list slot="footer" type="vertical">
      <c4d-link-list-item-cta
        icon-placement="right"
        href="https://www.ibm.com"
        cta-type="local">
        Learn more
      </c4d-link-list-item-cta>
      <c4d-link-list-item-cta
        icon-placement="right"
        href="https://www.ibm.com"
        cta-type="external">
        Microservices and containers
      </c4d-link-list-item-cta>
    </c4d-link-list>
    ${thumbnail
      ? html`<c4d-image
          slot="thumbnail"
          alt="Alt text"
          default-src="${imgLg16x9}"></c4d-image>`
      : ''}
  </c4d-content-item-row>
`;

export const contentItemRowStory = html`${contentItemRow()}${contentItemRow({
  thumbnail: true,
})}${contentItemRow({ image: true })}`;

export const ctaBlock = html`
  <c4d-cta-block no-border>
    <c4d-content-block-heading>Take the next step</c4d-content-block-heading>
    <c4d-content-block-copy
      >Want to discuss your options with a DevOps expert? Contact our sales team
      to evaluate your needs.</c4d-content-block-copy
    >
    <c4d-button-group slot="action">
      <c4d-button-group-item href="https://example.com">
        Secondary Button
      </c4d-button-group-item>
      <c4d-button-group-item ref="https://example.com">
        Primary button
      </c4d-button-group-item>
    </c4d-button-group>
    <c4d-cta-block-item-row>
      <c4d-cta-block-item>
        <c4d-content-item-heading>Get connected</c4d-content-item-heading>
        <c4d-content-item-copy
          >IBM DevOps partners have a wide range of expertise. Find one to build
          that right solution for you.</c4d-content-item-copy
        >
        <c4d-text-cta
          slot="footer"
          cta-type="local"
          icon-placement="right"
          href="example.com"
          >Find a partner</c4d-text-cta
        >
      </c4d-cta-block-item>
      <c4d-cta-block-item>
        <c4d-content-item-heading>Learn how</c4d-content-item-heading>
        <c4d-content-item-copy
          >Dig into more self-directed larning about DevOps
          methodologies.</c4d-content-item-copy
        >
        <c4d-text-cta
          slot="footer"
          cta-type="local"
          icon-placement="right"
          href="example.com"
          >Browse tutorials</c4d-text-cta
        >
      </c4d-cta-block-item>
      <c4d-cta-block-item>
        <c4d-content-item-heading>Learn how</c4d-content-item-heading>
        <c4d-content-item-copy
          >Dig into more self-directed larning about DevOps
          methodologies.</c4d-content-item-copy
        >
        <c4d-text-cta
          slot="footer"
          cta-type="local"
          icon-placement="right"
          href="example.com"
          >Browse tutorials</c4d-text-cta
        >
      </c4d-cta-block-item>
    </c4d-cta-block-item-row>
  </c4d-cta-block>
`;

export const featureCard = html`
  <c4d-feature-card cta-type="local" href="https://example.com">
    <c4d-image
      slot="image"
      alt="Image alt text"
      default-src="${imgLg16x9}"></c4d-image>
    <c4d-card-heading>Natural language processing (NLP)</c4d-card-heading>
    <c4d-feature-card-footer> </c4d-feature-card-footer>
  </c4d-feature-card>
`;

export const linkListItemCopy = [
  'Learn more about Kubernetes',
  'Containerization A Complete Guide',
  'Microservices and containers',
];

export const linkListItem = ({ copy = '' } = {}) => html`
  <c4d-link-list-item href="https://example.com">
    <p>${copy}</p>
    <svg
      slot="icon"
      focusable="false"
      preserveAspectRatio="xMidYMid meet"
      xmlns="http://www.w3.org/2000/svg"
      fill="currentColor"
      aria-hidden="true"
      width="20"
      height="20"
      viewBox="0 0 20 20">
      <path
        d="M11.8 2.8L10.8 3.8 16.2 9.3 1 9.3 1 10.7 16.2 10.7 10.8 16.2 11.8 17.2 19 10z"></path>
    </svg>
  </c4d-link-list-item>
`;

export const linkList = html`
  <c4d-link-list type="end">
    <c4d-link-list-heading>Tutorial</c4d-link-list-heading>
    ${linkListItem({ copy: linkListItemCopy[0] })}
    ${linkListItem({ copy: linkListItemCopy[1] })}
    ${linkListItem({ copy: linkListItemCopy[2] })}
  </c4d-link-list>
`;

export const quote = html`
  <c4d-quote inverse mark-type="double-curved">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus est purus,
    posuere at est vitae, ornare rhoncus sem. Suspendisse vitae tellus
    fermentum, hendrerit augue eu, placerat magna.
    <c4d-quote-source-heading>
      Lorem ipsum dolor sit amet
    </c4d-quote-source-heading>
    <c4d-quote-source-copy> consectetur adipiscing elit </c4d-quote-source-copy>
    <c4d-quote-source-bottom-copy> IBM Cloud </c4d-quote-source-bottom-copy>
    <c4d-quote-link-with-icon
      slot="footer"
      href="https://example.com"
      cta-type="local">
      Link with Icon
    </c4d-quote-link-with-icon>
  </c4d-quote>
`;

export const structuredList = html`
  <c4d-structured-list>
    <c4d-structured-list-head>
      <c4d-structured-list-header-row>
        <c4d-structured-list-header-cell
          >Column A</c4d-structured-list-header-cell
        >
        <c4d-structured-list-header-cell
          >Column B</c4d-structured-list-header-cell
        >
        <c4d-structured-list-header-cell
          >Column C</c4d-structured-list-header-cell
        >
      </c4d-structured-list-header-row>
    </c4d-structured-list-head>
    <c4d-structured-list-body>
      <c4d-structured-list-row>
        <c4d-structured-list-cell>Row 1</c4d-structured-list-cell>
        <c4d-structured-list-cell>Row 1</c4d-structured-list-cell>
        <c4d-structured-list-cell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim.
        </c4d-structured-list-cell>
      </c4d-structured-list-row>
      <c4d-structured-list-row>
        <c4d-structured-list-cell>Row 2</c4d-structured-list-cell>
        <c4d-structured-list-cell>Row 2</c4d-structured-list-cell>
        <c4d-structured-list-cell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim.
        </c4d-structured-list-cell>
      </c4d-structured-list-row>
      <c4d-structured-list-row>
        <c4d-structured-list-cell>Row 3</c4d-structured-list-cell>
        <c4d-structured-list-cell>Row 3</c4d-structured-list-cell>
        <c4d-structured-list-cell>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dui
          magna, finibus id tortor sed, aliquet bibendum augue. Aenean posuere
          sem vel euismod dignissim.
        </c4d-structured-list-cell>
      </c4d-structured-list-row>
    </c4d-structured-list-body>
  </c4d-structured-list>
`;

export const tabsExtended = html`
  <c4d-tabs-extended value="first">
    <c4d-tab id="tab-first" target="panel-first" value="first">
      First tab with long text
    </c4d-tab>
    <c4d-tab id="tab-second" target="panel-second" value="second">
      Second tab
    </c4d-tab>
    <c4d-tab id="tab-third" target="panel-third" value="third">
      Third tab
    </c4d-tab>
    <c4d-tab id="tab-fourth" target="panel-fourth" value="fourth">
      Fourth tab
    </c4d-tab>
    <c4d-tab label="Fifth tab" disabled>Fifth tab</c4d-tab>
  </c4d-tabs-extended>
`;

export const videoPlayer = html`
  <c4d-video-player-container id="my-video" video-id="0_ibuqxqbe">
  </c4d-video-player-container>
`;
