// packages/web-components/src/components/content-block-v2/content-block.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  html,
  customElement,
  property,
  LitElement,
} from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME } from './defs';
import styles from './content-block.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

export { CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME };

const { stablePrefix: ddsPrefix } = ddsSettings;
// const { prefix } = settings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  complementary: '_hasComplementary',
  copy: '_hasCopy',
  heading: '_hasHeading',
  footer: '_hasFooter',
  media: '_hasMedia',
};

// TODO: Figure out how to define a mixin type supporting abstract class
/**
 * Content block.
 *
 * @slot heading - The heading content.
 * @slot copy - The copy content.
 * @slot media - The media content.
 * @slot footer - The footer (CTA) content.
 * @slot complementary - The complementary (aside) content.
 * @abstract
 */
@customElement(`${ddsPrefix}-content-block-v2`)
class DDSContentBlockV2 extends StableSelectorMixin(LitElement) {

  @property({ type: Boolean, reflect: true, attribute: 'padding' })
  padding = false;

  @property({ type: Boolean, reflect: true, attribute: 'border' })
  border = false;

  render() {
    return html`
      <div class="all">
        <slot name="heading" @slotchange=""></slot>
        <div class="body">
          <div class="inner">
            <slot name="copy" @slotchange=""></slot>
            <slot @slotchange=""></slot>
            <slot name="footer" @slotchange=""></slot>
          </div>
          <slot name="complementary" @slotchange=""></slot>
        </div>
      </div>
      ${this.border ? html` <dds-hr></dds-hr> ` : ''}
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentBlockV2;

// packages/react/src/patterns/sub-patterns/ContentBlock/ContentBlock.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  settings as ddsSettings,
  markdownToHtml,
} from '@carbon/ibmdotcom-utilities';
import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * ContentArrayBlock Component, for use with content arrays
 *
 * @param {object} props props object
 * @param {string} props.heading  Heading objects
 * @param {copy} props.copy Heading copy copy
 * @param {*} props.children JSX Components
 * @param {*} props.cta JSX Components
 * @returns {*} JSX ContentArrayBlock component
 */
const ContentBlock = ({ heading, copy, children, cta, customClassName }) => {
  const className = cx(`${prefix}--content-block`, customClassName);

  return (
    <div data-autoid={`${stablePrefix}--content-block`} className={className}>
      {heading && (
        <h2
          data-autoid={`${stablePrefix}--content-block__title`}
          className={`${prefix}--content-block__title`}>
          {heading}
        </h2>
      )}
      {copy && (
        <div
          className={`${prefix}--content-block__intro`}
          dangerouslySetInnerHTML={{ __html: markdownToHtml(copy) }}
        />
      )}
      <div data-autoid={`${stablePrefix}--content-block__children`}>
        {children}
      </div>
      {cta && (
        <div
          data-autoid={`${stablePrefix}--content-block__cta`}
          className={cx(`${prefix}--content-block__cta`)}>
          {cta}
        </div>
      )}
    </div>
  );
};

ContentBlock.propTypes = {
  heading: PropTypes.string,
  copy: PropTypes.string,
  children: PropTypes.element,
  cta: PropTypes.element,
  customClassName: PropTypes.string,
};

export default ContentBlock;
