// packages/web-components/src/component-mixins/callout/callout.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html } from 'lit';
import settings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { Constructor } from '../../globals/defs';

const { prefix } = settings;

/**
 * Callout.
 *
 * @mixin c4d-callout
 */
const C4DCalloutMixin = <T extends Constructor<HTMLElement>>(base: T) => {
  return class extends base {
    render() {
      return html`
        <div class="${prefix}--callout__column">
          <div class="${prefix}--callout__content">
            ${
              /* Declaring this mixin as it extends \`LitElement\` seems to cause a TS error
            // @ts-ignore */
              super.render()
            }
          </div>
        </div>
      `;
    }
  };
};

export default C4DCalloutMixin;

// packages/react/src/patterns/sub-patterns/Callout/Callout.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 *
 * @param {object} children jsx component
 * @returns {*} callout with child object
 */
const Callout = ({ children }) => (
  <section
    className={`${prefix}--callout__container`}
    data-autoid={`${stablePrefix}--callout__container`}>
    <div
      className={`${prefix}--callout__column`}
      data-autoid={`${stablePrefix}--callout__column`}>
      <div
        className={`${prefix}--callout__content`}
        data-autoid={`${stablePrefix}--callout__content`}>
        {children}
      </div>
    </div>
  </section>
);

Callout.propTypes = {
  children: PropTypes.object,
};

export default Callout;
