// packages/react/src/patterns/sub-patterns/PictogramItem/PictogramItem.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import ContentItem from '../ContentItem/ContentItem';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';
const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content with pictogram component
 *
 * @param {object} props props object {title, copy, pictogram, link}
 * @param {string} props.heading Content with pictogram component title property
 * @param {string} props.copy Content with pictogram component copy property
 * @param {string} props.className Pictogram Array className prop
 * @param {*} props.Pictogram Content with pictogram component Pictogram component
 * @returns {*} Content array with pictograms item JSX Component
 */
const PictogramItem = ({ heading, copy, Pictogram, cta, className }) => (
  <div className={classNames(className, `${prefix}--pictogram-item`)}>
    <div className={`${prefix}--pictogram-item__row`}>
      <div className={`${prefix}--pictogram-item__wrapper`}>
        <Pictogram
          data-autoid={`${stablePrefix}--pictogram-item__pictogram`}
          className={`${prefix}--pictogram-item__pictogram`}
        />
      </div>
      <div
        data-autoid={`${stablePrefix}--pictogram-item__content`}
        className={`${prefix}--pictogram-item__content`}>
        <ContentItem
          heading={heading}
          copy={copy}
          cta={{ type: 'text', ...cta }}
        />
      </div>
    </div>
  </div>
);

PictogramItem.propTypes = {
  heading: PropTypes.string.isRequired,
  copy: PropTypes.string.isRequired,
  cta: PropTypes.object,
  Pictogram: PropTypes.object.isRequired,
  className: PropTypes.string,
};

export default PictogramItem;

// packages/web-components/src/components/pictogram-item/pictogram-item.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, LitElement, property } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './pictogram-item.scss';
import '../content-item/content-item';
import '../content-item/content-item-heading';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Pictogram item.
 *
 * @element dds-pictogram-item
 * @slot heading - The heading content.
 * @slot cta - The footer (CTA) content.
 */
@customElement(`${ddsPrefix}-pictogram-item`)
class DDSPictogramItem extends LitElement {
  /**
   * Internal Property for get copy from slot
   */
  @property({ reflect: true })
  copy = '';

  render() {
    return html`
      <div class="${prefix}--pictogram-item__row">
        <div class="${prefix}--pictogram-item__wrapper">
          <slot class="${prefix}--pictogram-item__pictogram" name="pictogram"></slot>
        </div>
        <div class="${prefix}--pictogram-item__content">
          <dds-content-item copy="${this.copy}">
            <dds-content-item-heading>
              <slot name="heading"></slot>
            </dds-content-item-heading>
            <slot name="cta" slot="cta"></slot>
          </dds-content-item>
        </div>
      </div>
    `;
  }

  static styles = styles;
}

export default DDSPictogramItem;
