// packages/web-components/src/components/table-of-contents/__stories__/content.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit-element';

const content = () => html`
  <a name="8">
    <h3>
      Cras molestie condimentum
    </h3>
  </a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <a name="7">
    <h3>
      Praesent fermentum sodales
    </h3>
  </a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <a name="2">
    <h3>
      Nulla tristique lacinia
    </h3>
  </a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <a name="3">
    <h3>
      Morbi id nibh metus
    </h3>
  </a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <a name="14">
    <h3>
      Integer non scelerisque
    </h3>
  </a>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras molestie condimentum consectetur. Nulla tristique lacinia elit,
    at elementum dui gravida non. Mauris et nisl semper, elementum quam non, lacinia purus. Vivamus aliquam vitae sapien volutpat
    efficitur. Curabitur sagittis neque facilisis magna posuere consectetur. Praesent fermentum sodales facilisis. Mauris a
    efficitur sem. Aliquam vehicula sapien libero, a viverra felis scelerisque vel. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam vehicula et. Etiam non vulputate augue.
    Morbi laoreet diam dapibus sapien pellentesque tristique. Morbi id nibh metus. Integer non scelerisque nisl.
  </p>
`;

export default content;

// packages/react/src/patterns/sub-patterns/TableOfContents/__stories__/data/content.js
import React from 'react';
const content = (
    <div>
        <a data-title='Cras molestie condimentum' name="8" style={{ color: '#000' }}>
        <h3 style={{ paddingBottom: '1rem', paddingTop: '2rem' }}>
            Cras molestie condimentum
        </h3>
        </a>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
        molestie condimentum consectetur. Nulla tristique lacinia elit, at
        elementum dui gravida non. Mauris et nisl semper, elementum quam
        non, lacinia purus. Vivamus aliquam vitae sapien volutpat efficitur.
        Curabitur sagittis neque facilisis magna posuere consectetur.
        Praesent fermentum sodales facilisis. Mauris a efficitur sem.
        Aliquam vehicula sapien libero, a viverra felis scelerisque vel.
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam
        vehicula et. Etiam non vulputate augue. Morbi laoreet diam dapibus
        sapien pellentesque tristique. Morbi id nibh metus. Integer non
        scelerisque nisl.
        </p>
        <a data-title='Praesent fermentum sodales'  name="7" style={{ color: '#000' }}>
        <h3 style={{ paddingBottom: '1rem', paddingTop: '2rem' }}>
            Praesent fermentum sodales
        </h3>
        </a>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
        molestie condimentum consectetur. Nulla tristique lacinia elit, at
        elementum dui gravida non. Mauris et nisl semper, elementum quam
        non, lacinia purus. Vivamus aliquam vitae sapien volutpat efficitur.
        Curabitur sagittis neque facilisis magna posuere consectetur.
        Praesent fermentum sodales facilisis. Mauris a efficitur sem.
        Aliquam vehicula sapien libero, a viverra felis scelerisque vel.
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam
        vehicula et. Etiam non vulputate augue. Morbi laoreet diam dapibus
        sapien pellentesque tristique. Morbi id nibh metus. Integer non
        scelerisque nisl.
        </p>
        <a data-title='Nulla tristique lacinia'  name="2" style={{ color: '#000' }}>
        <h3 style={{ paddingBottom: '1rem', paddingTop: '2rem' }}>
            Nulla tristique lacinia
        </h3>
        </a>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
        molestie condimentum consectetur. Nulla tristique lacinia elit, at
        elementum dui gravida non. Mauris et nisl semper, elementum quam
        non, lacinia purus. Vivamus aliquam vitae sapien volutpat efficitur.
        Curabitur sagittis neque facilisis magna posuere consectetur.
        Praesent fermentum sodales facilisis. Mauris a efficitur sem.
        Aliquam vehicula sapien libero, a viverra felis scelerisque vel.
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam
        vehicula et. Etiam non vulputate augue. Morbi laoreet diam dapibus
        sapien pellentesque tristique. Morbi id nibh metus. Integer non
        scelerisque nisl.
        </p>
        <a data-title='Morbi id nibh metus' name="3" style={{ color: '#000' }}>
        <h3 style={{ paddingBottom: '1rem', paddingTop: '2rem' }}>
            Morbi id nibh metus
        </h3>
        </a>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
        molestie condimentum consectetur. Nulla tristique lacinia elit, at
        elementum dui gravida non. Mauris et nisl semper, elementum quam
        non, lacinia purus. Vivamus aliquam vitae sapien volutpat efficitur.
        Curabitur sagittis neque facilisis magna posuere consectetur.
        Praesent fermentum sodales facilisis. Mauris a efficitur sem.
        Aliquam vehicula sapien libero, a viverra felis scelerisque vel.
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam
        vehicula et. Etiam non vulputate augue. Morbi laoreet diam dapibus
        sapien pellentesque tristique. Morbi id nibh metus. Integer non
        scelerisque nisl.
        </p>
        <a data-title='Integer non scelerisque' name="14" style={{ color: '#000' }}>
        <h3 style={{ paddingBottom: '1rem', paddingTop: '2rem' }}>
            Integer non scelerisque
        </h3>
        </a>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras
        molestie condimentum consectetur. Nulla tristique lacinia elit, at
        elementum dui gravida non. Mauris et nisl semper, elementum quam
        non, lacinia purus. Vivamus aliquam vitae sapien volutpat efficitur.
        Curabitur sagittis neque facilisis magna posuere consectetur.
        Praesent fermentum sodales facilisis. Mauris a efficitur sem.
        Aliquam vehicula sapien libero, a viverra felis scelerisque vel.
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
        posuere cubilia Curae; Donec fringilla dui tellus, a pretium diam
        vehicula et. Etiam non vulputate augue. Morbi laoreet diam dapibus
        sapien pellentesque tristique. Morbi id nibh metus. Integer non
        scelerisque nisl.
        </p>
    </div>
);

export default content;
