// packages/web-components/src/components/leadspace/leadspace.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, svg, property, LitElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import { LEADSPACE_TYPE, LEADSPACE_GRADIENT_STYLE_SCHEME } from './defs';
import styles from './leadspace.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

export { LEADSPACE_TYPE, LEADSPACE_GRADIENT_STYLE_SCHEME };

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The LeadSpace component.
 *
 * @element dds-leadspace
 * @slot action The action (CTA) content.
 * @slot image The image content.
 * @csspart section The first DOM node inside the shadow-root
 */
@customElement(`${ddsPrefix}-leadspace`)
class DDSLeadSpace extends StableSelectorMixin(LitElement) {
  /**
   * Sets background image for leadspace centered
   */
  protected _getBackgroundImage() {
    return this.defaultSrc && this.type === LEADSPACE_TYPE.CENTERED ? `background-image: url(${this.defaultSrc})` : '';
  }

  /**
   * Returns a class-name based on the gradient parameter type
   */
  protected _getGradientClass() {
    return classMap({
      [`${prefix}--leadspace--gradient`]: this.gradientStyleScheme === LEADSPACE_GRADIENT_STYLE_SCHEME.WITH_GRADIENT,
      [`${prefix}--leadspace__overlay`]: true,
    });
  }

  /**
   * Returns a class-name based on the type parameter type
   */
  protected _getTypeClass() {
    return classMap({
      [`${prefix}--leadspace--centered`]: this.type === LEADSPACE_TYPE.CENTERED,
      [`${prefix}--leadspace--centered__image`]: this.type === LEADSPACE_TYPE.CENTERED && this.defaultSrc,
      [`${prefix}--leadspace--productive`]: this.type === LEADSPACE_TYPE.SMALL,
      [`${prefix}--leadspace__section`]: true,
    });
  }

  /**
   * Renders Leadspace copy/description
   */
  protected _renderCopy() {
    const { copy } = this;
    return html`
      <div class="${prefix}--leadspace__row">
        <p data-autoid="${ddsPrefix}--leadspace__desc" class="${prefix}--leadspace__desc">
          <slot>${copy}</slot>
        </p>
      </div>
    `;
  }

  /**
   * Renders Leadspace title slot
   */
  protected _renderHeading() {
    const { title } = this;
    return html`
      <slot name="heading">${title}</slot>
    `;
  }

  /**
   *  Renders the image slot or the mobile image for centered leadspace
   */
  protected _renderImage() {
    const { defaultSrc, alt, type } = this;
    if (type === LEADSPACE_TYPE.CENTERED) {
      return html`
        <div data-autoid="${ddsPrefix}--leadspace--centered--mobile__image" class="${prefix}--leadspace--centered--mobile__image">
          <img src="${defaultSrc}" alt="${alt}" />
        </div>
      `;
    }
    return html`
      <slot name="image"></slot>
    `;
  }

  /**
   * The alternate text.
   */
  @property()
  alt = '';

  /**
   * The image source.
   */
  @property({ attribute: 'default-src' })
  defaultSrc = '';

  /**
   * The leadspace copy.
   */
  @property()
  copy = '';

  /**
   * The gradient style sceheme.
   */
  @property({ reflect: true, attribute: 'gradient-style-scheme' })
  gradientStyleScheme = LEADSPACE_GRADIENT_STYLE_SCHEME.WITH_GRADIENT;

  /**
   * The leadspace title.
   */
  @property()
  title = '';

  /**
   *  Leadspace type (small, left, or centered)
   */
  @property({ reflect: true })
  type = LEADSPACE_TYPE.LEFT;

  render() {
    const { gradientStyleScheme, type } = this;
    return html`
      <section style="${this._getBackgroundImage()}" class="${this._getTypeClass()}" part="section">
        <div class="${prefix}--leadspace__container">
          <div class="${this._getGradientClass()}">
            ${gradientStyleScheme === LEADSPACE_GRADIENT_STYLE_SCHEME.NONE
              ? undefined
              : svg`
                <svg
                  class="${prefix}--leadspace__gradient"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="none"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
                  <defs>
                    <linearGradient id="stops" class="${prefix}--leadspace__gradient__stops">
                      ${
                        type === LEADSPACE_TYPE.CENTERED
                          ? svg`
                          <stop offset="0%" />
                          <stop offset="27%" />
                          <stop offset="53%" />
                          <stop offset="80%" />
                        `
                          : svg`
                          <stop offset="0%" />
                          <stop offset="75%" />
                        `
                      }
                    </linearGradient>
                  </defs>
                  <rect class="${prefix}--leadspace__gradient__rect" width="100" height="100" />
                </svg>
              `}
            <div class="${prefix}--leadspace--content__container">
              <div class="${prefix}--leadspace__row">
                ${this._renderHeading()}
              </div>
              <div class="${prefix}--leadspace__content">
                ${this._renderCopy()}
                <slot name="action"></slot>
              </div>
            </div>
          </div>
          ${this._renderImage()}
        </div>
      </section>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--leadspace`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeadSpace;

// packages/react/src/patterns/sections/LeadSpace/LeadSpace.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useEffect, useState } from 'react';
import { ButtonGroup } from '../../sub-patterns/ButtonGroup';
import LeadSpaceImage from './LeadSpaceImage';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * renders the pattern classnames
 *
 * @param {string} variation variation of the pattern
 * @param {string} theme theme of the pattern
 * @param {string} type switches between centered or default
 * @param {object} image object
 * @returns {string} classnames
 */
const className = (variation, theme, type, image) =>
  classnames(
    `${prefix}--leadspace`,
    theme && `${prefix}--leadspace--${theme}`,
    {
      [`${prefix}--leadspace--productive`]: type === 'small',
    },
    {
      [`${prefix}--leadspace--centered${theme && '--g100'}`]:
        type === 'centered',
    },
    {
      [`${prefix}--leadspace--centered__image`]: image && type === 'centered',
    }
  );

/**
 * @param {string} type returns centered or default
 * @param {string} element returns element name
 * @returns {string} classnames
 */
function centeredClassname(type, element) {
  if (type === 'centered') {
    return `${prefix}--leadspace--centered__${element}`;
  } else return `${prefix}--leadspace__${element}`;
}

/**
 *
 * @param {string} type type
 * @param {object} image image
 * @returns {object} returns either image component or the centered image div
 */
function imageClassname(type, image) {
  if (type === 'centered') {
    return (
      <div
        data-autoid={`${stablePrefix}--leadspace--centered--mobile__image`}
        className={`${prefix}--leadspace--centered--mobile__image`}>
        <img src={image.default} alt={image.alt} />
      </div>
    );
  } else
    return (
      <LeadSpaceImage
        images={sortImages(image)}
        defaultImage={image.default}
        alt={image.alt}
      />
    );
}

/**
 * renders the pattern classnames
 *
 * @param {boolean} gradient determines whether to render gradient
 * @returns {string} classnames
 */
const overlayClassname = gradient =>
  classnames(`${prefix}--leadspace__overlay`, {
    [`${prefix}--leadspace--gradient`]: gradient,
  });

/**
 * sorts images by breakpoints for the LeadSpaceImage component
 *
 * @param {object} images object with all the image srcs for diff breakpoints
 * @returns {Array} images sorted
 */
const sortImages = images => {
  return [
    {
      minWidth: 1056,
      url: images.default,
    },
    {
      minWidth: 672,
      url: images.tablet,
    },
    {
      minWidth: 0,
      url: images.mobile,
    },
  ];
};

/**
 * Lead space component (left-aligned)
 *
 * @param {object} props props object
 * @param {Array} props.buttons array of buttons for lead space (max 2 buttons)
 * @param {string} props.copy lead space short copy to support the title
 * @param {boolean} props.gradient determines whether to render gradient overlay
 * @param {object} props.image image object with diff source for diff breakpoints
 * @param {string} props.theme theme of the pattern (g100 or white (default))
 * @param {string} props.title lead space title
 * @param {string} props.variation variation of the lead space (expressive (default) | productive)
 * @returns {*} Lead space component
 */
const LeadSpace = ({
  buttons,
  copy,
  gradient,
  image,
  theme,
  title,
  type,
  variation,
}) => {
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
  const isMobile = windowWidth <= 671;

  /**
   *  Sets the window width
   */
  const handleWindowResize = () => {
    setWindowWidth(window.innerWidth);
  };

  useEffect(() => {
    window.addEventListener('resize', handleWindowResize);

    return () => {
      window.removeEventListener('resize', handleWindowResize);
    };
  });

  const background =
    type === 'centered' && image && !isMobile
      ? { backgroundImage: `url(${image.default})` }
      : { backgroundImage: 'none' };

  return (
    <section
      style={background}
      data-autoid={`${stablePrefix}--leadspace`}
      className={className(variation, theme, type, image)}>
      <div className={`${prefix}--leadspace__container`}>
        <div className={overlayClassname(gradient)}>
          <div
            className={
              type !== 'centered'
                ? `${prefix}--leadspace--content__container`
                : `${prefix}--leadspace--centered--content__container`
            }>
            <div className={`${prefix}--leadspace__row`}>
              <h1 className={centeredClassname(type, 'title')}>{title}</h1>
            </div>
            <div className={centeredClassname(type, 'content')}>
              {copy && (
                <div className={`${prefix}--leadspace__row`}>
                  {copy && (
                    <p
                      data-autoid={`${stablePrefix}--leadspace__desc`}
                      className={centeredClassname(type, 'desc')}>
                      {copy}
                    </p>
                  )}
                </div>
              )}
              {buttons && buttons.length > 0 && (
                <ButtonGroup buttons={buttons} />
              )}
            </div>
          </div>
        </div>

        {image && imageClassname(type, image)}
      </div>
    </section>
  );
};

LeadSpace.propTypes = {
  buttons: PropTypes.array,
  copy: PropTypes.string,
  gradient: PropTypes.bool,
  image: PropTypes.shape({
    mobile: PropTypes.string,
    tablet: PropTypes.string,
    default: PropTypes.string,
    url: PropTypes.string,
    alt: PropTypes.string,
  }),
  theme: PropTypes.string,
  title: PropTypes.string.isRequired,
  type: PropTypes.string,
  variation: PropTypes.string,
};

export default LeadSpace;
