// packages/react/src/components/CardLink/CardLink.js
/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Card } from '../Card';
import cx from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { prefix } = settings;

/**
 * CardLink component
 */
const CardLink = ({ card, disabled }) => {
  const type = disabled ? '' : 'link';
  const cardLinkClassname = cx(`${prefix}--card__CTA`, {
    [`${prefix}--card__CTA--disabled`]: disabled,
  });
  return (
    <Card
      customClassName={cardLinkClassname}
      {...card}
      type={type}
      disabled={disabled}
    />
  );
};

CardLink.propTypes = {
  /**
   * Card options.
   * See [`<Card>`'s README](http://ibmdotcom-react.mybluemix.net/?path=/docs/components-card--link-clickable#props) for full usage details.
   */
  card: PropTypes.shape(Card.propTypes).isRequired,
  /**
   * disabled: `true` to disable it.
   */
  disabled: PropTypes.bool,
};

CardLink.defaultProps = {
  disabled: false,
};

export default CardLink;

// packages/web-components/src/components/card-link/card-link.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSCard from '../card/card';
import styles from './card-link.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Card Link.
 *
 * @element dds-card-link
 */
@customElement(`${ddsPrefix}-card-link`)
class DDSCardLink extends DDSCard {
  updated(changedProperties) {
    super.updated(changedProperties);
    const { _linkNode: linkNode } = this;
    if (linkNode) {
      linkNode.classList.add(`${prefix}--card__CTA`);
      linkNode.classList.add(`${prefix}--card-link`);
      if (this.hasAttribute('disabled')) linkNode.classList.add(`${prefix}--card__CTA--disabled`);
    }
  }

  static get stableSelector() {
    return `${ddsPrefix}--card-link`;
  }

  static styles = styles;
}

export default DDSCardLink;
