// packages/react/src/components/CalloutData/CalloutData.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import Callout from '../../internal/components/Callout/Callout';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import deprecate from '@carbon/ibmdotcom-utilities/es/utilities/deprecate/deprecate';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Callout with Data pattern.
 */

const CalloutData = ({ data, copy, source }) => (
  <div
    data-autoid={`${stablePrefix}--callout-data`}
    className={`${prefix}--callout-data`}>
    <Callout>
      <h4 className={`${prefix}--callout-data__data`}>{data}</h4>

      <p className={`${prefix}--callout-data__copy`}>{copy}</p>
    </Callout>
    <p className={`${prefix}--callout-data__source`}>{source}</p>
  </div>
);

CalloutData.propTypes = {
  /**
   * Data for CalloutData pattern.
   */
  data: PropTypes.string.isRequired,

  /**
   * Copy text
   */
  copy: PropTypes.string.isRequired,

  /**
   * Source test
   */
  source: PropTypes.string.isRequired,
};

export default deprecate(CalloutData);

// packages/web-components/src/components/callout-data/callout-data.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import './callout-data-container';
import styles from './callout-data.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Callout Data.
 *
 * @element dds-callout-data
 */
@customElement(`${ddsPrefix}-callout-data`)
class DDSCalloutData extends LitElement {
  render() {
    return html`
      <dds-callout-data-container class="test">
        <h4 class="${prefix}--callout-data__data"><slot name="data" /></h4>
        <p class="${prefix}--callout-data__copy"><slot name="copy" /></p>
      </dds-callout-data-container>
      <p class="${prefix}--callout-data__source"><slot name="source" /></p>
    `;
  }

  static styles = styles;
}

export default DDSCalloutData;
