// packages/web-components/src/components/content-block-mixed/content-block-mixed.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, css } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import DDSContentBlock from '../content-block/content-block';
import styles from './content-block-mixed.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content block mixed
 *
 * @element dds-content-block-mixed
 */
@customElement(`${ddsPrefix}-content-block-mixed`)
class DDSContentBlockMixed extends DDSContentBlock {
  static get stableSelector() {
    return `${ddsPrefix}--content-block-mixed`;
  }

  // `styles` here is a `CSSResult` generated by custom WepPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentBlockMixed;

// packages/react/src/patterns/blocks/ContentBlockMixed/ContentBlockMixed.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ContentBlock } from '../../sub-patterns/ContentBlock';
import { ContentGroupCards } from '../ContentGroupCards';
import { ContentGroupPictograms } from '../ContentGroupPictograms';
import { ContentGroupSimple } from '../ContentGroupSimple';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * ContentBlockMixed Pattern
 *
 * @param {object} props ContentBlockMixed props object
 * @param {string} props.heading Content block heading
 * @param {string} props.copy Content block description
 * @param {object} props.cta cta object
 * @param {Array} props.items Content block mixed group patterns
 * @returns {*} ContentBlockMixed JSX Object
 */
const ContentBlockMixed = ({ heading, copy, cta, items }) => {
  const patterns = {
    ContentGroupCards,
    ContentGroupSimple,
    ContentGroupPictograms,
  };
  const groups = items.map((item, index) => {
    const Pattern = patterns[item.type];
    return <Pattern key={index} {...item} />;
  });

  return (
    <div
      data-autoid={`${stablePrefix}--content-block-mixed`}
      className={`${prefix}--content-block ${prefix}--content-block-mixed`}>
      <ContentBlock heading={heading} copy={copy} cta={cta}>
        {groups}
      </ContentBlock>
    </div>
  );
};

ContentBlockMixed.propTypes = {
  heading: PropTypes.string.isRequired,
  copy: PropTypes.string,
  items: PropTypes.array,
  cta: PropTypes.shape({
    style: PropTypes.oneOf(['card']),
  }),
};

export default ContentBlockMixed;
