// packages/react/src/patterns/sub-patterns/Quote/Quote.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  settings as ddsSettings,
  decodeString,
} from '@carbon/ibmdotcom-utilities';
import ArrowRight20 from '@carbon/icons-react/es/arrow--right/20';
import classnames from 'classnames';
import { HorizontalRule } from '../../../components/HorizontalRule';
import Launch20 from '@carbon/icons-react/es/launch/20';
import { LinkWithIcon } from '../../../components/LinkWithIcon';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Quote Pattern
 *
 * @param {object} props props Object
 * @param {string} props.markType type of the quote marks
 * @param {string} props.copy quote copy
 * @param {object} props.source source object
 * @param {string} props.source.heading name heading for quote source
 * @param {string} props.source.copy title copy for quote source
 * @param {object} props.cta cta props object
 * @param {string} props.cta.copy cta copy
 * @param {string} props.cta.type type 'local' or 'external'
 * @param {string} props.cta.href cta href
 * @param {boolean} props.inverse toggles inverse theme
 * @returns {*} Quote Pattern
 */
const Quote = ({ markType = 'doubleCurved', copy, source, cta, inverse }) => {
  /**
   * Render the Quote copy with the selected quote marks
   *
   * @returns {*} Blockquote with quote marks
   */
  const renderQuote = () => {
    switch (markType) {
      case 'doubleCurved':
        return (
          <>
            <span className={`${prefix}--quote__mark`}>“</span>
            <blockquote className={`${prefix}--quote__copy`}>
              {decodeString(copy)}”
            </blockquote>
          </>
        );
      case 'singleCurved':
        return (
          <>
            <span className={`${prefix}--quote__mark`}>‘</span>
            <blockquote className={`${prefix}--quote__copy`}>
              {decodeString(copy)}’
            </blockquote>
          </>
        );
      case 'doubleAngle':
        return (
          <>
            <span className={`${prefix}--quote__mark`}>«</span>
            <blockquote className={`${prefix}--quote__copy`}>
              {decodeString(copy)}»
            </blockquote>
          </>
        );
      case 'singleAngle':
        return (
          <>
            <span className={`${prefix}--quote__mark`}>‹</span>
            <blockquote className={`${prefix}--quote__copy`}>
              {decodeString(copy)}›
            </blockquote>
          </>
        );
      case 'lowHighReversedDoubleCurved':
        return (
          <>
            <span className={`${prefix}--quote__mark`}>„</span>
            <blockquote className={`${prefix}--quote__copy`}>
              {decodeString(copy)}“
            </blockquote>
          </>
        );
    }
  };
  return (
    <div
      data-autoid={`${stablePrefix}--quote`}
      className={classnames(
        `${prefix}--quote`,
        `${inverse ? `${prefix}--quote__inverse` : ''}`
      )}>
      <div className={`${prefix}--quote__container`}>
        <div
          className={`${prefix}--quote__wrapper`}
          data-autoid={`${stablePrefix}--quote__copy`}>
          {renderQuote()}
        </div>
        {source && source.heading && source.copy ? (
          <div
            className={`${prefix}--quote__source`}
            data-autoid={`${stablePrefix}--quote__source`}>
            <p className={`${prefix}--quote__source-heading`}>
              {decodeString(source.heading)}
            </p>
            <p className={`${prefix}--quote__source-body`}>
              {decodeString(source.copy)}
            </p>
          </div>
        ) : (
          false
        )}
      </div>
      {cta ? (
        <div className={`${prefix}--quote__footer`}>
          <HorizontalRule />
          <LinkWithIcon href={cta.href}>
            {cta.copy}
            {cta.type === 'local' ? <ArrowRight20 /> : false}
            {cta.type === 'external' ? <Launch20 /> : false}
          </LinkWithIcon>
        </div>
      ) : (
        false
      )}
    </div>
  );
};

Quote.propTypes = {
  markType: PropTypes.string,
  copy: PropTypes.string.isRequired,
  source: PropTypes.object,
  cta: PropTypes.object,
  inverse: PropTypes.bool,
};

export default Quote;

// packages/web-components/src/components/quote/quote.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { customElement, html, LitElement, property } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './quote.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import '../horizontal-rule/horizontal-rule';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

export enum QUOTE_TYPES {
  /**
   * Default - doubleCurved
   */
  DEFAULT = 'doubleCurved',

  /**
   * singleCurved
   */
  SINGLE_CURVED = 'singleCurved',

  /**
   * singleAngle
   */
  SINGLE_ANGLE = 'singleAngle',

  /**
   * doubleAngle
   */
  DOUBLE_ANGLE = 'doubleAngle',

  /**
   * lowHighReversedDoubleCurved
   */
  LOW_HIGH_REVERSED_DOUBLE_CURVED = 'lowHighReversedDoubleCurved',

  /**
   * cornerBracket
   */
  CORNER_BRACKET = 'cornerBracket',
}

const slotExistencePropertyNames = {
  sourceHeading: '_hasSourceHeading',
  sourceCopy: '_hasSourceCopy',
  sourceBottomCopy: '_hasSourceBottomCopy',
  footer: '_hasFooter',
};

/**
 * Quote.
 *
 * @element dds-quote
 * @slot copy - The copy content.
 * @slot footer - The footer (CTA) content.
 */
@customElement(`${ddsPrefix}-quote`)
class DDSQuote extends StableSelectorMixin(LitElement) {
  /**
   * Defines rendered quote mark style
   * styles:
   * `doubleCurved`: `“ ”`;
   * `singleCurved`: `‘ ’`;
   * `singleAngle`: `‹ ›`;
   * `doubleAngle`: `« »`;
   * `lowHighReversedDoubleCurved`: `„ “`;
   * `cornerBracket`: `「 」`;
   */
  @property({ reflect: true, attribute: 'mark-type' })
  markType = QUOTE_TYPES.DEFAULT;

  /**
   * Defines if the inverse class is included
   */
  @property({ reflect: true, type: Boolean })
  inverse = false;

  /**
   * `true` if there is source heading.
   */
  protected _hasSourceHeading = false;

  /**
   * `true` if there is source copy.
   */
  protected _hasSourceCopy = false;

  /**
   * `true` if there is source bottom copy.
   */
  protected _hasSourceBottomCopy = false;

  /**
   * `true` if there is cta.
   */
  protected _hasFooter = false;

  /**
   * Handles `slotchange` event.
   */
  protected _handleSlotChange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name]] = hasContent;
    this.requestUpdate();
  }

  protected _renderQuote() {
    switch (this.markType) {
      case QUOTE_TYPES.SINGLE_CURVED:
        return html`
          <span class="${prefix}--quote__mark">‘</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">’</span>
          </blockquote>
        `;
      case QUOTE_TYPES.DOUBLE_ANGLE:
        return html`
          <span class="${prefix}--quote__mark">«</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">»</span>
          </blockquote>
        `;
      case QUOTE_TYPES.SINGLE_ANGLE:
        return html`
          <span class="${prefix}--quote__mark">‹</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">›</span>
          </blockquote>
        `;
      case QUOTE_TYPES.LOW_HIGH_REVERSED_DOUBLE_CURVED:
        return html`
          <span class="${prefix}--quote__mark">„</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">“</span>
          </blockquote>
        `;
      case QUOTE_TYPES.CORNER_BRACKET:
        return html`
          <span class="${prefix}--quote__mark ${prefix}--quote__mark-corner-bracket">「</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">」</span>
          </blockquote>
        `;
      default:
        return html`
          <span class="${prefix}--quote__mark">“</span>
          <blockquote class="${prefix}--quote__copy">
            <slot name="copy"></slot><span class="${prefix}--quote__mark-closing">”</span>
          </blockquote>
        `;
    }
  }

  protected _renderSource() {
    const {
      _hasSourceHeading: hasSourceHeading,
      _hasSourceCopy: hasSourceCopy,
      _hasSourceBottomCopy: hasSourceBottomCopy,
      _handleSlotChange: handleSlotChange,
    } = this;
    return html`
      <div ?hidden="${!hasSourceHeading || !hasSourceCopy}" class="${prefix}--quote__source">
        <p class="${prefix}--quote__source-heading">
          <slot @slotchange="${handleSlotChange}" name="sourceHeading"></slot>
        </p>
        <p class="${prefix}--quote__source-body">
          <slot @slotchange="${handleSlotChange}" name="sourceCopy"></slot>
        </p>
        <p ?hidden="${!hasSourceBottomCopy}" class="${prefix}--quote__source-optional-copy">
          <slot @slotchange="${handleSlotChange}" name="sourceBottomCopy"></slot>
        </p>
      </div>
    `;
  }

  protected _renderFooter() {
    const { _hasFooter: hasFooter, _handleSlotChange: handleSlotChange } = this;
    return html`
      <div ?hidden="${!hasFooter}" class="${prefix}--quote__footer">
        <dds-hr></dds-hr>
        <slot name="footer" @slotchange="${handleSlotChange}"></slot>
      </div>
    `;
  }

  updated(changedProperties) {
    if (changedProperties.has('inverse')) {
      const { inverse } = this;
      this.classList.toggle(`${prefix}--quote__inverse`, inverse);
    }
  }

  render() {
    return html`
      <div class="${prefix}--quote__container">
        <div class="${prefix}--quote__wrapper">
          ${this._renderQuote()}${this._renderSource()}${this._renderFooter()}
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--quote`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSQuote;
