// packages/react/src/patterns/blocks/ContentBlockSimple/ContentBlockSimple.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ContentBlock } from '../../sub-patterns/ContentBlock';
import { ContentItem } from '../../sub-patterns/ContentItem';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { Image } from '../../../components/Image';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content Block - Simple pattern
 *
 * @param {object} props props object
 * @param {string} props.copy multiple paragraphs to support the heading
 * @param {string} props.heading Content block simple heading
 * @param {object} props.image Content item image
 * @param {object} props.cta cta object
 * @returns {*} Content block simple pattern
 */
const ContentBlockSimple = ({ copy, heading, image, cta }) => (
  <ContentBlock
    heading={heading}
    cta={cta}
    customClassName={`${prefix}--content-block-simple`}>
    <div data-autoid={`${stablePrefix}--content-block-simple`}>
      <div
        data-autoid={`${prefix}--content-block-simple__content`}
        className={`${prefix}--content-block-simple__content`}>
        <ContentItem copy={copy} />
        {image && <Image {...image} />}
      </div>
    </div>
  </ContentBlock>
);

ContentBlockSimple.propTypes = {
  copy: PropTypes.string.isRequired,
  heading: PropTypes.string.isRequired,
  image: PropTypes.instanceOf(Image),
  cta: PropTypes.object,
};

export default ContentBlockSimple;

// packages/web-components/src/components/content-block-simple/content-block-simple.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlock from '../content-block/content-block';
import styles from './content-block-simple.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Simple version of content block.
 *
 * @element dds-content-block-simple
 */
@customElement(`${ddsPrefix}-content-block-simple`)
class DDSContentBlockSimple extends StableSelectorMixin(DDSContentBlock) {
  static get stableSelector() {
    return `${ddsPrefix}--content-block-simple`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }
}

export default DDSContentBlockSimple;
