// packages/carbon-web-components/examples/codesandbox/angular/src/app/app.component.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import '@carbon/web-components/es/components/dropdown/dropdown';
import '@carbon/web-components/es/components/dropdown/dropdown-item';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {}

// packages/react/examples/codesandbox/components/Footer/src/App.js
/**
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import './styles.scss';
import { Footer } from "@carbon/ibmdotcom-react/es/components/Footer";

export default function App() {
  return (
    <div className="App">
      <Footer type="default" />
    </div>
  );
}
