// packages/web-components/src/components/content-group-v2/content-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import DDSContentBlockV2 from '../content-block-v2/content-block';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './content-group.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group.
 *
 * @abstract
 */
@customElement(`${ddsPrefix}-content-group-v2`)
class DDSContentGroupV2 extends StableSelectorMixin(DDSContentBlockV2) {
  // protected _renderInnerBody(): TemplateResult | string | void {
  //   return html` ${this._renderMedia()}${this._renderContent()} `;
  // }

  static get stableSelector() {
    return `${ddsPrefix}--content-group-v2`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupV2;

// packages/react/src/patterns/sub-patterns/ContentGroup/ContentGroup.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import { DDS_CONTENT_GROUP } from '../../../internal/FeatureFlags';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { featureFlag } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * ContentArrayGroup Component, for use with content arrays
 *
 * @param {object} props props object
 * @param {*} props.children JSX Components
 * @param {string} props.heading  Heading objects
 * @returns {*} JSX ContentArrayGroup component
 */
const ContentGroup = ({ children, heading }) => {
  return featureFlag(
    DDS_CONTENT_GROUP,
    <div
      className={`${prefix}--content-group`}
      data-autoid={`${stablePrefix}--content-group`}>
      <div className={`${prefix}--content-group__container`}>
        <div className={`${prefix}--content-group__row`}>
          <div className={`${prefix}--content-group__col`}>
            <h3
              data-autoid={`${stablePrefix}--content-group__title`}
              className={`${prefix}--content-group__title`}>
              {heading}
            </h3>
          </div>
        </div>
        <div className={`${prefix}--content-group__row`}>
          <div
            data-autoid={`${stablePrefix}--content-group__children`}
            className={classNames(
              `${prefix}--content-group__col`,
              `${prefix}--content-group__children`
            )}>
            {children}
          </div>
        </div>
      </div>
    </div>
  );
};

ContentGroup.propTypes = {
  heading: PropTypes.string,
  children: PropTypes.element,
};

export default ContentGroup;
