// packages/react/src/components/Footer/LegalNav.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import Link from '../../internal/vendor/carbon-components-react/components/Link/Link';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Footer legal nav component.
 */
const LegalNav = ({ links, type, button, adjunctLinks }) => {
  if (!links?.length) {
    return null;
  }

  const listStyle = cx({
    [`${prefix}--legal-nav__micro`]: type === 'micro',
  });

  return (
    <aside
      data-autoid={`${stablePrefix}--footer-legal-nav`}
      className={`${prefix}--legal-nav__container`}>
      <nav className={`${prefix}--legal-nav`}>
        <div className={`${prefix}--legal-nav__list ${listStyle}`}>
          <ul className={`${prefix}--legal-nav__holder`}>
            {links &&
              links.map(({ title, titleEnglish, url }, index) => {
                if (!title || !url) {
                  return null;
                }

                const dataTitle = titleEnglish
                  ? titleEnglish
                      .replace(/[^-a-zA-Z0-9_ ]/g, '')
                      .replace(/ +/g, '-')
                      .toLowerCase()
                  : null;

                return (
                  <li className={`${prefix}--legal-nav__list-item`} key={index}>
                    <Link
                      data-autoid={`${stablePrefix}--footer-legal-nav__link-${dataTitle}`}
                      className={`${prefix}--footer__link`}
                      href={url}>
                      {title}
                    </Link>
                  </li>
                );
              })}
            <li
              className={`${prefix}--legal-nav__list-item`}
              data-autoid={`${stablePrefix}--privacy-cp`}
            />
          </ul>
          {button}
        </div>
        <ul className={`${prefix}--adjunct-links__holder`}>
          {adjunctLinks &&
            adjunctLinks.map(({ title, titleEnglish, url }, index) => {
              if (!title || !url) {
                return null;
              }

              const dataTitle = titleEnglish
                ? titleEnglish
                    .replace(/[^-a-zA-Z0-9_ ]/g, '')
                    .replace(/ +/g, '-')
                    .toLowerCase()
                : null;

              return (
                <li className={`${prefix}--legal-nav__list-item`} key={index}>
                  <Link
                    data-autoid={`${stablePrefix}--footer-legal-nav__link-${dataTitle}`}
                    className={`${prefix}--footer__link`}
                    href={url}>
                    {title}
                  </Link>
                </li>
              );
            })}
        </ul>
      </nav>
    </aside>
  );
};

LegalNav.propTypes = {
  /**
   * A list of links to be rendered.
   */
  links: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string,
      url: PropTypes.string,
    })
  ),

  /**
   * List of adjunct links to be rendered
   */
  adjunctLinks: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string,
      url: PropTypes.string,
    })
  ),

  /**
   * Footer type
   */
  type: PropTypes.string,

  /**
   * The locale/language selector button.
   * Renders only in micro version
   */
  button: PropTypes.object,
};

LegalNav.defaultProps = {
  links: null,
};

export default LegalNav;

// packages/web-components/src/components/footer/legal-nav.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, query, LitElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map.js';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { FOOTER_SIZE } from './footer';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './footer.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Legal nav.
 *
 * @element dds-legal-nav
 */
@customElement(`${ddsPrefix}-legal-nav`)
class DDSLegalNav extends StableSelectorMixin(LitElement) {
  /**
   * Size property used for applying classes
   */
  @property()
  size = FOOTER_SIZE.REGULAR;

  /**
   * The adjunct links container
   */
  @query(`.${prefix}--adjunct-links__container`)
  private _adjunctLinksContainer?: HTMLDivElement;

  /**
   * The adjunct links slot
   */
  @query('[name="adjunct-links"]')
  private _adjunctLinksSlot?: HTMLSlotElement;

  /**
   * Returns a class-name based on the type parameter type
   */
  protected _getTypeClass() {
    return classMap({
      [`${prefix}--legal-nav__list`]: true,
      [`${prefix}--legal-nav__micro`]: this.size === FOOTER_SIZE.MICRO,
    });
  }

  /**
   * The shadow slot this legal nav should be in.
   */
  @property({ reflect: true })
  slot = 'legal-nav';

  connectedCallback() {
    if (this.hasAttribute('role')) {
      this.removeAttribute('role');
    }
    super.connectedCallback();
  }

  render() {
    return html`
      <nav class="${prefix}--legal-nav">
        <div class="${this._getTypeClass()}">
          <ul>
            <slot></slot>
          </ul>
          <div class="${prefix}--adjunct-links__container">
            <div class="${prefix}--adjunct-links__row">
              <div class="${prefix}--adjunct-links__col">
                <slot name="adjunct-links"></slot>
              </div>
            </div>
          </div>
          <slot name='locale'>
        </div>
      </nav>
    `;
  }

  firstUpdated() {
    const {
      _adjunctLinksContainer: adjunctLinksContainer,
      _adjunctLinksSlot: adjunctLinksSlot,
    } = this;
    const hideAdjunctLinksContainer =
      adjunctLinksSlot?.assignedNodes().length === 0
        ? adjunctLinksContainer?.classList.add(
            `${prefix}--adjunct-links__container--hidden`
          )
        : '';
    return hideAdjunctLinksContainer;
  }

  static get stableSelector() {
    return `${ddsPrefix}--footer-legal-nav`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLegalNav;
