// packages/react/src/components/ScrollAnimations/ScrollAnimations.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useCallback, useEffect, useRef } from 'react';
import { breakpoints } from '@carbon/layout';
import PropTypes from 'prop-types';
import settings from 'carbon-components/es/globals/js/settings';

const { prefix } = settings;

/**
 * Amount of columns used for calculation.
 *
 * @private
 */
const colSpan = 3;

/**
 * Utility handles fade transition for selected elements.
 *
 * @example
 * import { ScrollAnimations } from '@carbon/ibmdotcom-react';
 * import '@carbon/ibmdotcom-styles/scss/components/scroll-into-view/_scroll-into-view.scss';
 *
 * As an example, the function can be called to target all instances of the
 * elements in a list:
 *
 * const list = '.bx--content-block, .bx--content-group';
 *
 * For default values of 400ms and 'one and done' play:
 * <ScrollAnimations selectorTargets={selectorTargets}>
 *   // some content
 * </ScrollAnimations>
 *
 * With 'continuous play' option:
 * <ScrollAnimations animation={'fade'} selectorTargets={selectorTargets} keepAnimations={true}>
 *   // some content
 * </ScrollAnimations>
 *
 * For custom delay time, set within targeted class in the application's CSS code as such:
 *
 * .bx--content-block {
 *   --#{$dds-prefix}--fade-in-out-delay: 250ms;
 * }
 *
 */
const ScrollAnimations = ({
  animation,
  children,
  selectorTargets,
  keepAnimations,
}) => {
  /**
   * Outer div component ref for using with query selector.
   *
   * @private
   */
  const componentRef = useRef(null);

  /**
   * Intersection Observer that watches outer viewport.
   *
   * @private
   */
  const rootObserver = useRef(null);

  /**
   * Intersection observer that watches the inner viewport.
   *
   * @private
   */
  const innerObserver = useRef(null);

  /**
   * Resize observer to trigger rootMargin recalculations
   *
   * @private
   */
  const resizeObserver = useRef(null);

  /**
   * Scroll animation class to be applied when element is within viewport.
   *
   * @private
   */
  const effectClass = useRef(null);

  /**
   * Scroll animation to be applied when elements are out of view.
   *
   * @private
   */
  const exitEffectClass = useRef(null);

  /**
   * Create observers upon render and update.
   */
  useEffect(() => {
    setAnimationClasses();
    rootObserver.current = new IntersectionObserver(handleExit);
    resizeObserver.current = new ResizeObserver(handleResize);

    if (selectorTargets) {
      componentRef.current?.querySelectorAll(selectorTargets).forEach(item => {
        rootObserver?.current.observe(item);
      });
    }
    resizeObserver.current.observe(document.documentElement);

    return () => {
      rootObserver.current.disconnect();
      innerObserver.current.disconnect();
      resizeObserver.current.disconnect();
      rootObserver.current = null;
      innerObserver.current = null;
      resizeObserver.current = null;
    };
  }, [
    componentRef,
    selectorTargets,
    setAnimationClasses,
    handleEntrance,
    handleResize,
  ]);

  /**
   * Handler to add recalculated rootMargin to a new instance of
   * inner observer after clearing old one first.
   *
   * The calculation is done to retrieve the best fitting top and bottom
   * margin for the fade animation to trigger/remove from elements in a
   * user's screen.
   *
   * The resulting value is the optimal point where a user's attention will be
   * grabbed by the animation without restricting their view and perception of
   * the adopting website. The displayed elements will keep the user's attention
   * for a longer time as they scroll down the website.
   *
   * @private
   */
  const handleResize = useCallback(() => {
    if (innerObserver.current) {
      innerObserver.current.disconnect();
      innerObserver.current = null;
    }

    innerObserver.current = new IntersectionObserver(handleEntrance, {
      rootMargin: `-${(
        (document.documentElement.clientHeight * colSpan) /
        breakpoints.max.columns
      ).toString()}px 0px`,
    });

    if (selectorTargets) {
      componentRef.current?.querySelectorAll(selectorTargets).forEach(item => {
        innerObserver?.current.observe(item);
      });
    }
  }, [componentRef, innerObserver, selectorTargets, handleEntrance]);

  /**
   * Handler to add fade animation to element
   *
   * @param {*} records observed elements
   * @private
   *
   */
  const handleEntrance = useCallback(
    records => {
      records.forEach(({ intersectionRatio, target }) => {
        if (intersectionRatio > 0) {
          target.classList.remove(exitEffectClass.current);
          target.classList.add(effectClass.current);
          if (!keepAnimations) {
            rootObserver.current.unobserve(target);
            innerObserver.current.unobserve(target);
          }
        }
      });
    },
    [keepAnimations, rootObserver, innerObserver]
  );

  /**
   * Handler to remove element from view
   *
   * @param {*} records observed elements
   * @private
   *
   */
  function handleExit(records) {
    records.forEach(({ intersectionRatio, target }) => {
      if (intersectionRatio == 0) {
        target.classList.remove(effectClass.current);
        target.classList.add(exitEffectClass.current);
      }
    });
  }

  const setAnimationClasses = useCallback(() => {
    switch (animation) {
      case 'slide-up':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-up`;
        break;
      case 'slide-up-right':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-up-right`;
        break;
      case 'slide-right':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-right`;
        break;
      case 'slide-down-right':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-down-right`;
        break;
      case 'slide-down':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-down`;
        break;
      case 'slide-down-left':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-down-left`;
        break;
      case 'slide-left':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-left`;
        break;
      case 'slide-up-left':
        effectClass.current = `${prefix}--slide-in`;
        exitEffectClass.current = `${prefix}--slide-up-left`;
        break;
      default:
        effectClass.current = `${prefix}--fade-in`;
        exitEffectClass.current = `${prefix}--fade-out`;
        break;
    }
  }, [animation, effectClass, exitEffectClass]);

  return <div ref={componentRef}>{children}</div>;
};

ScrollAnimations.propTypes = {
  /**
   * String that determines what effect to display
   */
  animation: PropTypes.string,

  /**
   * Component(s) to render within the component
   */
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node,
  ]).isRequired,

  /**
   * List of elements to be targeted
   */
  selectorTargets: PropTypes.string,

  /**
   * Boolean to define if animation is continuous
   */
  keepAnimations: PropTypes.bool,
};

export default ScrollAnimations;

// packages/web-components/src/components/scroll-animations/scroll-animations.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import { breakpoints } from '@carbon/layout';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import { forEach } from '../../globals/internal/collection-helpers';
import { ANIMATION_TYPE } from './defs';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Amount of columns used for calculation.
 */

const colSpan = 3;

/**
 * Function component that handles fade or slide transition for selected elements.
 *
 * @example
 * import '@carbon/ibmdotcom-styles/scss/components/scroll-into-view/_scroll-into-view.scss';
 * import '@carbon/ibmdotcom-web-components/es/components/scroll-animations/scroll-animations.js';
 *
 * As an example, the function can be called to target all instances of the
 * elements in a list:
 *
 * const list = '${prefix}--content-block, ${prefix}--content-group';
 *
 * For default values of 400ms and 'one and done' play:
 * <dds-scroll-animations selectorTargets="${selectorTargets}">
 *  // some content
 * </dds-scroll-animations>
 *
 * With 'continuous play' option:
 * <dds-scroll-animations selector-targets="${selectorTargets}" keep-animation="true">
 *   // some content
 * </dds-scroll-animations>
 *
 * For custom delay time, set within targeted class in the application's CSS code as such:
 *
 * .${prefix}--content-block {
 *   --#{$dds-prefix}--scroll-animations-delay: 250ms;
 * }
 *
 * @element dds-scroll-animations
 */
@customElement(`${ddsPrefix}-scroll-animations`)
class DDSScrollAnimations extends StableSelectorMixin(LitElement) {
  /**
   * Intersection Observer that watches outer viewport.
   *
   * @private
   */
  private _rootObserver: IntersectionObserver | null = null;

  /**
   * Intersection observer that watches the inner viewport.
   *
   * @private
   */
  private _innerObserver: IntersectionObserver | null = null;

  /**
   * Resize observer to trigger rootMargin recalculations
   *
   * @private
   */
  private _resizeObserver: any | null = null;

  private _effectClass?: string;

  private _exitEffectClass?: string;

  /**
   * Cleans observers upon update or exit, and creates new instances if needed.
   *
   * @param [options] The options.
   * @param [options.create] `true` to create the new intersection observer.
   */
  private _cleanAndCreateObservers({ create }: { create?: boolean } = {}) {
    this._setAnimationClasses();
    this._cleanAndCreateRootObserver();
    this._cleanAndCreateInnerObserver();
    this._cleanAndCreateResizeObserver();

    if (create) {
      this._cleanAndCreateRootObserver({ create: true });
      this._cleanAndCreateResizeObserver({ create: true });

      const { selectorTargets } = this;
      if (selectorTargets) {
        forEach(this.querySelectorAll(selectorTargets), item => {
          this._rootObserver?.observe(item);
        });
      }
      this._resizeObserver.observe(this.ownerDocument!.documentElement);
    }
  }

  /**
   * Cleans-up and creats the root intersection observer.
   *
   * @param [options] The options.
   * @param [options.create] `true` to create the new intersection observer.
   */
  private _cleanAndCreateRootObserver({ create }: { create?: boolean } = {}) {
    if (this._rootObserver) {
      this._rootObserver.disconnect();
      this._rootObserver = null;
    }

    if (create) {
      this._rootObserver = new IntersectionObserver(this._handleExit.bind(this));
    }
  }

  /**
   * Cleans-up and creats the inner intersection observer.
   *
   * @param [options] The options.
   * @param [options.create] `true` to create the new intersection observer.
   * @param [options.viewportMargin] recalculated margin value for the observer
   */
  private _cleanAndCreateInnerObserver({ create, viewportMargin }: { create?: boolean; viewportMargin?: string } = {}) {
    if (this._innerObserver) {
      this._innerObserver.disconnect();
      this._innerObserver = null;
    }

    if (create) {
      this._innerObserver = new IntersectionObserver(this._handleEntrance.bind(this), { rootMargin: viewportMargin });
      const { selectorTargets } = this;
      if (selectorTargets) {
        forEach(this.querySelectorAll(selectorTargets), item => {
          this._innerObserver?.observe(item);
        });
      }
    }
  }

  /**
   * Cleans-up and creats the resize observer.
   *
   * @param [options] The options.
   * @param [options.create] `true` to create the new resize observer.
   */
  private _cleanAndCreateResizeObserver({ create }: { create?: boolean } = {}) {
    if (this._resizeObserver) {
      this._resizeObserver.disconnect();
      this._resizeObserver = null;
    }

    if (create) {
      // TODO: Wait for `.d.ts` update to support `ResizeObserver`
      // @ts-ignore
      this._resizeObserver = new ResizeObserver(this._handleResize.bind(this));
    }
  }

  /**
   * Handler to add recalculated rootMargin to observer upon resize.
   *
   * This calculation is done to retrieve the best fitting top and bottom
   * margin for the fade animation to trigger/remove from elements in a
   * user's screen.
   *
   * The resulting value is the optimal point where a user's attention will be
   * grabbed by the animation without restricting their view and perception of
   * the adopting website. The displayed elements will keep the user's attention
   * for a longer time as they scroll down the website.
   *
   * @private
   */
  private _handleResize() {
    this._cleanAndCreateInnerObserver({
      create: true,
      viewportMargin: `-${(
        (this.ownerDocument!.documentElement.clientHeight * colSpan) /
        breakpoints.max.columns
      ).toString()}px 0px`,
    });
  }

  /**
   * Handler to add fade animation to element
   *
   * @param {*} records observed elements
   * @private
   */
  private _handleEntrance = (records: IntersectionObserverEntry[]) => {
    records.forEach(({ intersectionRatio, target }) => {
      if (intersectionRatio > 0) {
        target.classList.remove(`${this._exitEffectClass}`);
        target.classList.add(`${this._effectClass}`);
        if (!this.keepAnimation) {
          this._rootObserver?.unobserve(target);
          this._innerObserver?.unobserve(target);
        }
      }
    });
  };

  /**
   * Handler to remove element from view
   *
   * @param {*} records observed elements
   *
   * @private
   */
  // eslint-disable-next-line class-methods-use-this
  private _handleExit(records: IntersectionObserverEntry[]) {
    records.forEach(({ intersectionRatio, target }) => {
      if (intersectionRatio === 0) {
        target.classList.remove(`${this._effectClass}`);
        target.classList.add(`${this._exitEffectClass}`);
      }
    });
  }

  /**
   * Sets the proper class names to be applied when element is within/out of view.
   *
   * @private
   */
  private _setAnimationClasses() {
    switch (this.animation) {
      case ANIMATION_TYPE.SLIDE_UP:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-up`;
        break;
      case ANIMATION_TYPE.SLIDE_UP_RIGHT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-up-right`;
        break;
      case ANIMATION_TYPE.SLIDE_RIGHT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-right`;
        break;
      case ANIMATION_TYPE.SLIDE_DOWN_RIGHT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-down-right`;
        break;
      case ANIMATION_TYPE.SLIDE_DOWN:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-down`;
        break;
      case ANIMATION_TYPE.SLIDE_DOWN_LEFT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-down-left`;
        break;
      case ANIMATION_TYPE.SLIDE_LEFT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-left`;
        break;
      case ANIMATION_TYPE.SLIDE_UP_LEFT:
        this._effectClass = `${prefix}--slide-in`;
        this._exitEffectClass = `${prefix}--slide-up-left`;
        break;
      case ANIMATION_TYPE.FADE:
      default:
        this._effectClass = `${prefix}--fade-in`;
        this._exitEffectClass = `${prefix}--fade-out`;
        break;
    }
  }

  @property()
  animation?: string = 'fade';

  /**
   * Iteration boolean for continuous play option.
   *
   * `true` to keep fade in/out behavior during the entire component lifecycle,
   * `false` to do it only once.
   *
   */
  @property({ type: Boolean, attribute: 'keep-animation' })
  keepAnimation = false;

  /**
   * The CSS selector string that selects all fade in-out target elements.
   */
  @property({ attribute: 'selector-targets' })
  selectorTargets?: string;

  connectedCallback() {
    super.connectedCallback();
    this._cleanAndCreateObservers({ create: true });
  }

  disconnectedCallback() {
    this._cleanAndCreateObservers();
    super.disconnectedCallback();
  }

  render() {
    return html`
      <slot></slot>
    `;
  }
}

export default DDSScrollAnimations;
