// packages/react/src/patterns/sub-patterns/ContentItem/ContentItem.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { CTA } from '../../../components/CTA';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { ImageWithCaption } from '../../../components/ImageWithCaption';
import { markdownToHtml } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * ContentItem Component
 *
 * @param {object} props props object
 * @param {string} props.cta cta object
 * @param {string} props.copy copy text
 * @param {string} props.heading  heading object
 * @param {object} props.image image object
 * @returns {*} JSX ContentItem component
 */
const ContentItem = ({ cta, copy, heading, image }) => (
  <div
    className={`${prefix}--content-item`}
    data-autoid={`${stablePrefix}--content-item`}>
    {heading && (
      <h4
        data-autoid={`${stablePrefix}--content-item__heading`}
        className={`${prefix}--content-item__heading`}>
        {heading}
      </h4>
    )}
    {image && (
      <ImageWithCaption
        customClassName={`${prefix}--content-item__image`}
        {...image}
      />
    )}
    {copy && (
      <div
        data-autoid={`${stablePrefix}--content-item__copy`}
        className={`${prefix}--content-item__copy`}
        dangerouslySetInnerHTML={{
          __html: markdownToHtml(copy, { bold: false }),
        }}></div>
    )}
    {cta && (
      <CTA
        style="text"
        type={cta.type}
        copy={cta.copy}
        href={cta.href}
        customClassName={`${prefix}--content-item__cta`}
      />
    )}
  </div>
);

ContentItem.propTypes = {
  cta: PropTypes.oneOfType(PropTypes.shape(CTA.propTypes)),
  copy: PropTypes.string,
  heading: PropTypes.string,
  image: PropTypes.oneOfType(PropTypes.shape(ImageWithCaption.propTypes)),
};

export default ContentItem;

// packages/web-components/src/components/content-item/content-item.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, internalProperty, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import ifNonNull from 'carbon-web-components/es/globals/directives/if-non-null.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import '../markdown/markdown';
import styles from './content-item.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  cta: '_hasCta',
};

/**
 * Content item.
 *
 * @element dds-content-item
 * @slot media - The media content.
 * @slot heading - The heading content.
 * @slot cta - The footer (CTA) content.
 */
@customElement(`${ddsPrefix}-content-item`)
class DDSContentItem extends StableSelectorMixin(LitElement) {
  /**
   * `true` if there is a CTA content.
   */
  @internalProperty()
  _hasCta = false;

  /**
   * Handles `slotchange` event on the CTA slot.
   *
   * @param event The event.
   */
  private _handleSlotchange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name] || '_hasDefaultContent'] = hasContent;
  }

  /**
   * The copy text.
   */
  @property()
  copy = '';

  render() {
    const { copy, _hasCta: hasCta } = this;
    return html`
      <slot name="heading"></slot>
      <div>
        <slot name="media"></slot>
      </div>
      ${!copy
        ? undefined
        : html`
            <dds-markdown class="${prefix}--content-item__copy" nobold .content="${ifNonNull(copy)}"> </dds-markdown>
          `}
      <div ?hidden="${!hasCta}" class="${prefix}--content-item__cta">
        <slot name="cta" @slotchange="${this._handleSlotchange}"></slot>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-item`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentItem;
