// packages/web-components/src/components/pictogram-item/pictogram-item.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, LitElement, property } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import settings from 'carbon-components/es/globals/js/settings';
import styles from './pictogram-item.scss';
import '../content-item/content-item';
import '../content-item/content-item-heading';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Pictogram item.
 *
 * @element dds-pictogram-item
 * @slot heading - The heading content.
 * @slot cta - The footer (CTA) content.
 */
@customElement(`${ddsPrefix}-pictogram-item`)
class DDSPictogramItem extends LitElement {
  /**
   * Internal Property for get copy from slot
   */
  @property({ reflect: true })
  copy = '';

  render() {
    return html`
      <div class="${prefix}--pictogram-item__row">
        <div class="${prefix}--pictogram-item__wrapper">
          <slot class="${prefix}--pictogram-item__pictogram" name="pictogram"></slot>
        </div>
        <div class="${prefix}--pictogram-item__content">
          <dds-content-item copy="${this.copy}">
            <dds-content-item-heading>
              <slot name="heading"></slot>
            </dds-content-item-heading>
            <slot name="cta" slot="cta"></slot>
          </dds-content-item>
        </div>
      </div>
    `;
  }

  static styles = styles;
}

export default DDSPictogramItem;

// packages/react/src/components/PictogramItem/PictogramItem.js
/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import ContentItem from '../../internal/components/ContentItem/ContentItem';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';
const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content with pictogram component.
 */
const PictogramItem = ({
  heading,
  copy,
  pictogram: { src: Pictogram, ...pictogramProps },
  cta,
  className,
}) => (
  <div className={classNames(className, `${prefix}--pictogram-item`)}>
    <div className={`${prefix}--pictogram-item__row`}>
      <div className={`${prefix}--pictogram-item__wrapper`}>
        <Pictogram
          data-autoid={`${stablePrefix}--pictogram-item__pictogram`}
          className={`${prefix}--pictogram-item__pictogram`}
          {...pictogramProps}
        />
      </div>
      <div
        data-autoid={`${stablePrefix}--pictogram-item__content`}
        className={`${prefix}--pictogram-item__content`}>
        <ContentItem
          heading={heading}
          copy={copy}
          cta={cta && { style: 'text', ...cta }}
        />
      </div>
    </div>
  </div>
);

PictogramItem.propTypes = {
  /**
   * Content with pictogram component title property.
   */
  heading: PropTypes.string.isRequired,

  /**
   * Content with pictogram component copy property.
   */
  copy: PropTypes.string.isRequired,

  /**
   * Object with CTA data.
   * See the [`<CTA>`'s README](http://ibmdotcom-react.mybluemix.net/?path=/docs/components-cta--default#props) for full usage details.
   */
  cta: PropTypes.shape({
    type: PropTypes.oneOfType([
      PropTypes.oneOf(['jump', 'local', 'external', 'download', 'video']),
      PropTypes.arrayOf(
        PropTypes.oneOf(['jump', 'local', 'external', 'download', 'video'])
      ),
    ]),
    copy: PropTypes.string,
    href: PropTypes.string,
    customClassName: PropTypes.string,
  }),

  /**
   * Pictogram data object.
   * The structure is:
   *
   * | Name  | Required | Data Type | Default Value | Description                                                  |
   * | ----- | -------- | --------- | ------------- | ------------------------------------------------------------ |
   * | `src` | YES      | Component | null          | Pictogram component imported from `@carbon/pictograms-react` |
   */
  pictogram: PropTypes.shape({
    src: PropTypes.object.isRequired,
  }).isRequired,

  /**
   * Pictogram Item `className`` prop.
   */
  className: PropTypes.string,
};

export default PictogramItem;
