// packages/react/.storybook/Container.js
/**
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import cx from 'classnames';
import React, { Component } from 'react';
import './_container.scss';
import { settings } from 'carbon-components';

/**
 * @param {Element} elem An element.
 * @param {string[]} props CSS property names.
 * @returns {Object<string, any>}
 *   The key-value pair of CSS property name/value.
 *   Used primary for integration testing.
 */
window.getStyleValues = function getStyleValues(elem, props) {
  const computedStyle = elem.ownerDocument.defaultView.getComputedStyle(elem);
  return props.reduce(
    (acc, prop) => ({
      ...acc,
      [prop]: computedStyle.getPropertyValue(prop),
    }),
    {}
  );
};

const { prefix } = settings;
export default class Container extends Component {
  componentDidMount() {
    if (process.env.REACT_STORYBOOK_USE_RTL === 'true') {
      document.documentElement.dir = 'rtl';
      document.getElementsByTagName('html')[0].setAttribute('dir', 'rtl');
    }
  }

  render() {
    const { parameters, story } = this.props;
    const classes = cx({
      'storybook-proxy-story': parameters.proxy,
    });

    return (
      <React.StrictMode>
        <div data-floating-menu-container="" role="main" className={classes}>
          {story()}
        </div>
        <input
          aria-label="input-text-offleft"
          type="text"
          className={`${prefix}--visually-hidden`}
        />
      </React.StrictMode>
    );
  }
}

// packages/web-components/.storybook/container.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, TemplateResult } from 'lit';
import containerStyles from './_container.scss?lit'; // eslint-disable-line import/first

/**
 * @param options The rendering options.
 * @param [options.hasMainTag] `true` if the story itself has `<main>` tag.
 * @param [options.children] The story content.
 * @returns The content that wraps the story.
 */
const container = ({
  hasMainTag,
  children,
}: {
  hasMainTag?: boolean;
  children: TemplateResult;
}) => html`
  <style>
    ${containerStyles}
  </style>
  <div
    id="main-content"
    name="main-content"
    data-floating-menu-container
    role="${hasMainTag ? 'none' : 'main'}">
    ${children}
  </div>
`;

export default container;
