// packages/web-components/src/components/card-link/card-link.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSCard from '../card/card';
import styles from './card-link.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Card Link.
 *
 * @element dds-card-link
 */
@customElement(`${ddsPrefix}-card-link`)
class DDSCardLink extends DDSCard {
  updated(changedProperties) {
    super.updated(changedProperties);
    const { _linkNode: linkNode } = this;
    if (linkNode) {
      linkNode.classList.add(`${prefix}--card__CTA`);
      linkNode.classList.add(`${prefix}--card-link`);
      if (this.hasAttribute('disabled')) linkNode.classList.add(`${prefix}--card__CTA--disabled`);
    }
  }

  static get stableSelector() {
    return `${ddsPrefix}--card-link`;
  }

  static styles = styles;
}

export default DDSCardLink;

// packages/react/src/patterns/sub-patterns/CardLink/CardLink.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import classNames from 'classnames';
import { ClickableTile } from 'carbon-components-react';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { Image } from '../../../components/Image';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Card Link Component
 *
 * @param {object} props react proptypes
 * @returns {object} JSX object
 */
const CardLink = ({
  title,
  href,
  content,
  icon,
  image,
  className,
  ...props
}) => {
  if (!title || !href) {
    return null;
  }

  return (
    <ClickableTile
      data-autoid={`${stablePrefix}--card-link`}
      className={classNames(`${prefix}--card-link`, className)}
      href={href}
      {...props}>
      <Image {...image} />
      <div className={`${prefix}--card-link__wrapper`}>
        <h3 className={`${prefix}--card-link__title`}>{title}</h3>
        {optionalContent(content)}
        {renderFooter(icon)}
      </div>
    </ClickableTile>
  );
};

/**
 * Card Link optional content
 *
 * @param {string} content paragraph of text
 * @returns {object} JSX object
 */
function optionalContent(content) {
  return !content ? null : (
    <p className={`${prefix}--card-link__content`}>{content}</p>
  );
}

/**
 * Render footer with icon
 *
 * @param {object} icon passes in react icon
 * @returns {object} JSX object
 */
function renderFooter(icon) {
  return !icon ? null : (
    <footer className={`${prefix}--card-link__footer`}>{icon}</footer>
  );
}

CardLink.propTypes = {
  title: PropTypes.string.isRequired,
  href: PropTypes.string.isRequired,
  icon: PropTypes.element,
  content: PropTypes.string,
  image: PropTypes.object,
  className: PropTypes.string,
};

export default CardLink;
