// packages/react/src/components/HorizontalRule/HorizontalRule.js
/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import classnames from 'classnames';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Horizontal Rule component.
 */
const HorizontalRule = ({ type, size, contrast, weight }) => (
  <hr
    data-autoid={`${stablePrefix}--hr`}
    className={classnames(`${prefix}--hr`, {
      [`${prefix}--hr--${type}`]: type,
      [`${prefix}--hr--${contrast}`]: contrast,
      [`${prefix}--hr--${size}`]: size,
      [`${prefix}--hr--${weight}`]: weight,
    })}
  />
);

HorizontalRule.propTypes = {
  /**
   * Type of HR. Choose from:
   *
   * | Name     | Description                                                                    |
   * | -------- | ------------------------------------------------------------------------------ |
   * | `solid`  | Default type variant of the horizontal rule                                   |
   * | `dashed` | Dashed/dotted type variant (type is applied in conjuction with `fluid` size) |
   */
  type: PropTypes.oneOf(['solid', 'dashed']),

  /**
   * Length of the HR. Choose from:
   *
   * | Name     | Description                                                         |
   * | -------- | ------------------------------------------------------------------- |
   * | `fluid`  | Default size variant - horizontal rule takes full width of the grid |
   * | `small`  | Shorter fixed-length variant with a max-width of 32px               |
   * | `medium` | Medium fixed-length variant with a max-width of 48px                |
   * | `large`  | Longer fixed-length variant with a max-width of 64px                |
   */
  size: PropTypes.oneOf(['fluid', 'small', 'medium', 'large']),

  /**
   * Contrast of the HR. Choose from:
   *
   * | Name              | Description                    |
   * | ----------------- | ------------------------------ |
   * | `medium-contrast` | Default contrast color variant |
   * | `low-contrast`    | Lighter contrast color variant |
   * | `high-contrast`   | Darker contrast color variant  |
   */
  contrast: PropTypes.oneOf([
    'medium-contrast',
    'low-contrast',
    'high-contrast',
  ]),

  /**
   * Weight of the HR. Choose from:
   *
   * | Name    | Description                                                                          |
   * | ------- | ------------------------------------------------------------------------------------ |
   * | `thin`  | Default weight variant                                                               |
   * | `thick` | Slightly thicker weight variant (this only applied in conjunction with `fluid` size) |
   */
  weight: PropTypes.oneOf(['thin', 'thick']),
};

export default HorizontalRule;

// packages/web-components/src/components/horizontal-rule/horizontal-rule.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, customElement, LitElement } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './horizontal-rule.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Type of the HR
 */
export enum HR_TYPE {
  /**
   * solid type of hr
   */
  SOLID = 'solid',

  /**
   * dashed/dotted type of hr
   */
  DASHED = 'dashed',
}

/**
 * Length of the HR
 */
export enum HR_SIZE {
  /**
   * fluid length of hr, takes full width of the grid
   */
  FLUID = 'fluid',

  /**
   * Small length of hr
   */
  SMALL = 'small',

  /**
   * Medium length of hr
   */
  MEDIUM = 'medium',

  /**
   * Large length of hr
   */
  LARGE = 'large',
}

/**
 * Contrast of the HR
 */
export enum HR_CONTRAST {
  /**
   * medium-contrast of hr
   */
  MEDIUM_CONTRAST = 'medium-contrast',

  /**
   * low-contrast of hr
   */
  LOW_CONTRAST = 'low-contrast',

  /**
   * high-contrast of hr
   */
  HIGH_CONTRAST = 'high-contrast',
}

/**
 * Weight of the HR
 */
export enum HR_WEIGHT {
  /**
   * thin weight of hr
   */
  THIN = 'thin',

  /**
   * thick weight of hr
   */
  THICK = 'thick',
}

/**
 * Horizontal Rule
 *
 * @element dds-hr
 */
@customElement(`${ddsPrefix}-hr`)
class DDSHorizontalRule extends LitElement {
  /**
   * Style of the HR (solid (default) | dashed)
   */
  @property({ attribute: 'type', reflect: true })
  type = HR_TYPE.SOLID;

  /**
   * Length of the HR
   * (fluid (default) | small | medium | large)
   */
  @property({ attribute: 'size', reflect: true })
  size = HR_SIZE.FLUID;

  /**
   * Contrast of the HR
   * (medium-contrast (default) | low-contrast | high-contrast)
   */
  @property({ attribute: 'contrast', reflect: true })
  contrast = HR_CONTRAST.MEDIUM_CONTRAST;

  /**
   * Weight of the HR
   * (thin (default) | thick)
   */
  @property({ attribute: 'weight', reflect: true })
  weight = HR_WEIGHT.THIN;

  render() {
    return super.render();
  }

  static get stableSelector() {
    return `${ddsPrefix}--hr`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSHorizontalRule;
