// packages/web-components/src/components/content-group-cards/content-group-cards.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, html, TemplateResult } from 'lit';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import deprecate from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/deprecate/deprecate';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-cards.scss';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group cards.
 *
 * @element dds-content-group-cards
 */
@customElement(`${ddsPrefix}-content-group-cards`)
class DDSContentGroupCards extends DDSContentGroup {
  protected _renderInnerBody(): TemplateResult | string | void {
    const { _hasContent: hasContent, _hasMedia: hasMedia } = this;
    return html`
      <div
        ?hidden="${!hasContent && !hasMedia}"
        class="${prefix}--content-group__children ${prefix}--content-group__col">
        <div
          class="${prefix}--content-group-cards-group ${prefix}--grid--condensed">
          <div class="${prefix}--content-group-cards__row">
            ${this._renderContent()}${this._renderMedia()}
          </div>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-group-cards`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default deprecate(
  DDSContentGroupCards,
  'The content-group-cards component has been deprecated in favor of the content-section/block and the card group component. ' +
    'See content-section/block and card-group documentation for more information.'
);

// packages/react/src/components/ContentGroupCards/ContentGroupCards.js
/**
 * Copyright IBM Corp. 2016, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import ArrowRight20 from '@carbon/icons-react/es/arrow--right/20';
import { Card } from '../Card';
import ContentGroup from '../ContentGroup/ContentGroup';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { prefix } = settings;
const { stablePrefix } = ddsSettings;
/**
 * Card Array Component.
 */
const ContentGroupCards = ({ heading, items, copy }) => {
  return (
    <section
      data-autoid={`${stablePrefix}--content-group-cards`}
      className={`${prefix}--content-group-cards`}>
      <ContentGroup heading={heading} copy={copy}>
        <div
          data-autoid={`${stablePrefix}--content-group-cards-group`}
          className={`${prefix}--content-group-cards-group ${prefix}--grid--condensed`}>
          <div className={`${prefix}--content-group-cards__row`}>
            {_renderCards(items)}
          </div>
        </div>
      </ContentGroup>
    </section>
  );
};

/**
 * Renders the cards based on the ContentArray entries
 *
 * @param {Array} items Content object array
 * @returns {*} CardArrayItem JSX objects
 */
const _renderCards = items =>
  items.map((elem, index) => (
    <div
      data-autoid={`${stablePrefix}--content-group-cards-item`}
      className={`${prefix}--content-group-cards-item__col`}
      key={index}
      role="region">
      <Card
        customClassName={`${prefix}--content-group-cards-item`}
        heading={elem.heading}
        copy={elem.copy}
        cta={{
          href: elem.cta.href,
          icon: {
            src: ArrowRight20,
          },
        }}
        aria-label={elem.heading}
      />
    </div>
  ));

ContentGroupCards.propTypes = {
  /**
   * Main heading of the pattern.
   */
  heading: PropTypes.string.isRequired,

  /**
   * Copy text (enabled for the `markdownToHtml` utility)
   */
  copy: PropTypes.string,

  /**
   * Array of content group objects. Has the following structure:
   *
   * | Name      | Data Type | Description                                                |
   * | --------- | --------- | ---------------------------------------------------------- |
   * | `heading` | String    | Title for the Card.                                        |
   * | `copy`    | String    | Copy for the Card.                                         |
   * | `cta`     | Object    | Object containing target and href of cta. See `cta` below. |
   *
   * `cta`:
   *
   * | Name   | Data Type | Description                       |
   * | ------ | --------- | --------------------------------- |
   * | `href` | String    | Url of the Content Card item cta. |
   */
  items: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string,
      heading: PropTypes.string,
      cta: PropTypes.shape({
        href: PropTypes.string,
      }),
    })
  ),
};

export default ContentGroupCards;
