// packages/web-components/src/components/dotcom-shell/__stories__/data/content.react.tsx
/* eslint-disable max-len */
/**
 * Copyright IBM Corp. 2016, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';

import C4DImage from '@carbon/ibmdotcom-web-components/es/components-react/image/image';
import C4DImageItem from '@carbon/ibmdotcom-web-components/es/components-react/image/image-item';
import C4DContentBlockSegmented from '@carbon/ibmdotcom-web-components/es/components-react/content-block-segmented/content-block-segmented';
import C4DContentBlockSegmentedItem from '@carbon/ibmdotcom-web-components/es/components-react/content-block-segmented/content-block-segmented-item';
import C4DContentGroupHeading from '@carbon/ibmdotcom-web-components/es/components-react/content-group/content-group-heading';
import C4DContentItemCopy from '@carbon/ibmdotcom-web-components/es/components-react/content-item/content-item-copy';
import C4DTextCTA from '@carbon/ibmdotcom-web-components/es/components-react/cta/text-cta';
import C4DContentItemHorizontal from '@carbon/ibmdotcom-web-components/es/components-react/content-item-horizontal/content-item-horizontal';
import C4DContentItemHorizontalEyebrow from '@carbon/ibmdotcom-web-components/es/components-react/content-item-horizontal/content-item-horizontal-eyebrow';
import C4DContentItemHeading from '@carbon/ibmdotcom-web-components/es/components-react/content-item/content-item-heading';
import C4DContentItemHorizontalCopy from '@carbon/ibmdotcom-web-components/es/components-react/content-item-horizontal/content-item-horizontal-copy';
import C4DLinkList from '@carbon/ibmdotcom-web-components/es/components-react/link-list/link-list';
import C4DLinkListItemCTA from '@carbon/ibmdotcom-web-components/es/components-react/cta/link-list-item-cta';
import C4DUniversalBanner from '@carbon/ibmdotcom-web-components/es/components-react/universal-banner/universal-banner';
import C4DUniversalBannerImage from '@carbon/ibmdotcom-web-components/es/components-react/universal-banner/universal-banner-image';
import C4DUniversalBannerHeading from '@carbon/ibmdotcom-web-components/es/components-react/universal-banner/universal-banner-heading';
import C4DUniversalBannerCopy from '@carbon/ibmdotcom-web-components/es/components-react/universal-banner/universal-banner-copy';
import C4DButtonCTA from '@carbon/ibmdotcom-web-components/es/components-react/cta/button-cta';
import C4DCardGroupItem from '@carbon/ibmdotcom-web-components/es/components-react/card-group/card-group-item';
import C4DCardHeading from '@carbon/ibmdotcom-web-components/es/components-react/card/card-heading';
import C4DCardEyebrow from '@carbon/ibmdotcom-web-components/es/components-react/card/card-eyebrow';
import C4DCardCTAFooter from '@carbon/ibmdotcom-web-components/es/components-react/cta/card-cta-footer';
import C4DLeadspace from '@carbon/ibmdotcom-web-components/es/components-react/leadspace/leadspace';
import C4DLeadspaceHeading from '@carbon/ibmdotcom-web-components/es/components-react/leadspace/leadspace-heading';
import C4DButtonGroup from '@carbon/ibmdotcom-web-components/es/components-react/button-group/button-group';
import C4DButtonGroupItem from '@carbon/ibmdotcom-web-components/es/components-react/button-group/button-group-item';
import C4DLeadspaceWithSearch from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-with-search/leadspace-with-search';
import C4DLeadspaceWithSearchHeading from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-with-search/leadspace-with-search-heading';
import C4DLeadspaceWithSearchContent from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-with-search/leadspace-with-search-content';
import C4DLeadspaceWithSearchContentHeading from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-with-search/leadspace-with-search-content-heading';
import C4DLeadspaceWithSearchContentCopy from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-with-search/leadspace-with-search-content-copy';
import C4DSearchWithTypeahead from '@carbon/ibmdotcom-web-components/es/components-react/search-with-typeahead/search-with-typeahead';
import C4DLeadspaceBlock from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-block/leadspace-block';
import C4DLeadspaceBlockHeading from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-block/leadspace-block-heading';
import C4DLeadspaceBlockContent from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-block/leadspace-block-content';
import C4DContentBlockHeading from '@carbon/ibmdotcom-web-components/es/components-react/content-block/content-block-heading';
import C4DContentBlockCopy from '@carbon/ibmdotcom-web-components/es/components-react/content-block/content-block-copy';
import C4DLeadspaceBlockMedia from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-block/leadspace-block-media';
import C4DVideoPlayerContainer from '@carbon/ibmdotcom-web-components/es/components-react/video-player/video-player-container';
import C4DLinkListHeading from '@carbon/ibmdotcom-web-components/es/components-react/link-list/link-list-heading';
import C4DLinkListItem from '@carbon/ibmdotcom-web-components/es/components-react/link-list/link-list-item';
import C4DLeadspaceBlockCTA from '@carbon/ibmdotcom-web-components/es/components-react/leadspace-block/leadspace-block-cta';
import C4DFeatureCard from '@carbon/ibmdotcom-web-components/es/components-react/feature-card/feature-card';
import C4DFeatureCardFooter from '@carbon/ibmdotcom-web-components/es/components-react/feature-card/feature-card-footer';
import C4DCardCTA from '@carbon/ibmdotcom-web-components/es/components-react/cta/card-cta';
import C4DCalloutWithMedia from '@carbon/ibmdotcom-web-components/es/components-react/callout-with-media/callout-with-media';
import C4DCalloutWithMediaCopy from '@carbon/ibmdotcom-web-components/es/components-react/callout-with-media/callout-with-media-copy';
import C4DCalloutWithMediaVideo from '@carbon/ibmdotcom-web-components/es/components-react/callout-with-media/callout-with-media-video';
import C4DContentBlockHorizontal from '@carbon/ibmdotcom-web-components/es/components-react/content-block-horizontal/content-block-horizontal';
import C4DLogoGrid from '@carbon/ibmdotcom-web-components/es/components-react/logo-grid/logo-grid';
import C4DLogoGridItem from '@carbon/ibmdotcom-web-components/es/components-react/logo-grid/logo-grid-item';
import C4DContentBlockCards from '@carbon/ibmdotcom-web-components/es/components-react/content-block-cards/content-block-cards';
import C4DCardGroup from '@carbon/ibmdotcom-web-components/es/components-react/card-group/card-group';
import C4DCalloutQuote from '@carbon/ibmdotcom-web-components/es/components-react/callout-quote/callout-quote';
import C4DQuoteSourceHeading from '@carbon/ibmdotcom-web-components/es/components-react/quote/quote-source-heading';
import C4DQuoteSourceCopy from '@carbon/ibmdotcom-web-components/es/components-react/quote/quote-source-copy';
import C4DQuoteSourceBottomCopy from '@carbon/ibmdotcom-web-components/es/components-react/quote/quote-source-bottom-copy';
import C4DCalloutLinkWithIcon from '@carbon/ibmdotcom-web-components/es/components-react/callout-quote/callout-link-with-icon';
import C4DCTABlock from '@carbon/ibmdotcom-web-components/es/components-react/cta-block/cta-block';
import C4DCTABlockItemRow from '@carbon/ibmdotcom-web-components/es/components-react/cta-block/cta-block-item-row';
import C4DCTABlockItem from '@carbon/ibmdotcom-web-components/es/components-react/cta-block/cta-block-item';
import C4DTableOfContents from '@carbon/ibmdotcom-web-components/es/components-react/table-of-contents/table-of-contents';

import ArrowRight20 from '@carbon/icons-react/es/arrow--right/20.js';
import logosGroup from '../../../logo-grid/__stories__/data/logos.js';
import { TOC_TYPES } from '../../../table-of-contents/defs';

import imgSm16x9 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--002.jpg';
import imgMd16x9 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--002.jpg';
import imgLg16x9 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--002.jpg';
import imgLg1x1 from '../../../../../../storybook-images/assets/720/fpo--1x1--720x720--005.jpg';
import imgXlg4x3 from '../../../../../../storybook-images/assets/1312/fpo--4x3--1312x984--003.jpg';

import leadspaceImg from '../../../../../../storybook-images/assets/leadspace/fpo--leadspace--1584x560--002.jpg';

export const image = (
  <C4DImage
    alt="Image alt text"
    default-src={imgLg16x9}
    heading="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
    <C4DImageItem media="min-width: 672px" srcset={imgLg16x9}></C4DImageItem>
    <C4DImageItem media="min-width: 400px" srcset={imgMd16x9}></C4DImageItem>
    <C4DImageItem media="min-width: 320px" srcset={imgSm16x9}></C4DImageItem>
  </C4DImage>
);

export const contentBlockSegmentedItems = (
  <>
    <C4DContentBlockSegmentedItem>
      <C4DContentGroupHeading>
        A scelerisque purus semper eget duis at tellus.{' '}
      </C4DContentGroupHeading>
      <C4DContentItemCopy>
        Elementum nibh tellus molestie nunc non. Habitant morbi tristique
        senectus et netus et malesuada fames.
      </C4DContentItemCopy>
      <C4DTextCTA
        slot="footer"
        cta-type="local"
        icon-placement="right"
        href="https://example.com">
        Lorem Ipsum dolor sit
      </C4DTextCTA>
    </C4DContentBlockSegmentedItem>

    <C4DContentBlockSegmentedItem>
      <C4DContentGroupHeading>
        A scelerisque purus semper eget duis at tellus.{' '}
      </C4DContentGroupHeading>
      <C4DContentItemCopy>
        Elementum nibh tellus molestie nunc non. Habitant morbi tristique
        senectus et netus et malesuada fames.
      </C4DContentItemCopy>
    </C4DContentBlockSegmentedItem>
  </>
);

export const contentBlockSegmentedItemsWithImage = (
  <C4DContentBlockSegmentedItem>
    <C4DContentGroupHeading>
      A scelerisque purus semper eget duis at tellus.{' '}
    </C4DContentGroupHeading>
    <C4DContentItemCopy>
      Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus
      et netus et malesuada fames.
    </C4DContentItemCopy>
    {image}
    <C4DTextCTA
      slot="footer"
      cta-type="local"
      icon-placement="right"
      href="https://example.com">
      Lorem Ipsum dolor sit
    </C4DTextCTA>
  </C4DContentBlockSegmentedItem>
);

export const contentItemHorizontal = (
  <C4DContentItemHorizontal>
    <C4DContentItemHorizontalEyebrow>
      Lorem ipsum
    </C4DContentItemHorizontalEyebrow>
    <C4DContentItemHeading>Aliquam condimentum</C4DContentItemHeading>
    <C4DContentItemHorizontalCopy>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et
      ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit
      sollicitudin.
    </C4DContentItemHorizontalCopy>
    <C4DLinkList slot="footer" type="vertical">
      <C4DLinkListItemCTA
        icon-placement="right"
        href="https://www.ibm.com"
        cta-type="local">
        Link text
      </C4DLinkListItemCTA>
      <C4DLinkListItemCTA
        icon-placement="right"
        href="https://www.ibm.com"
        cta-type="external">
        External link text
      </C4DLinkListItemCTA>
    </C4DLinkList>
  </C4DContentItemHorizontal>
);

export const universalBanner = (srcImage) => (
  <C4DUniversalBanner image-width="4-col">
    <C4DUniversalBannerImage
      slot="image"
      default-src={srcImage}></C4DUniversalBannerImage>
    <C4DUniversalBannerHeading slot="heading">
      heading
    </C4DUniversalBannerHeading>
    <C4DUniversalBannerCopy slot="copy">copy</C4DUniversalBannerCopy>
    <C4DButtonCTA
      slot="cta"
      cta-type="local"
      kind="tertiary"
      href="https://www.example.com">
      cta copy
    </C4DButtonCTA>
  </C4DUniversalBanner>
);

export const cardGroupItems = (
  <C4DCardGroupItem href="https://example.com">
    <C4DImage
      slot="image"
      alt="Image alt text"
      default-src={imgXlg4x3}></C4DImage>
    <C4DCardEyebrow>Topic</C4DCardEyebrow>
    <C4DCardHeading>Natural Language Processing.</C4DCardHeading>
    <C4DCardCTAFooter></C4DCardCTAFooter>
  </C4DCardGroupItem>
);

export const contentLeadspace = (
  <C4DLeadspace
    size="medium"
    gradient-style-scheme="true"
    alt=""
    default-src={leadspaceImg}>
    <C4DLeadspaceHeading>Leadspace Title</C4DLeadspaceHeading>
    Use this area for a short line of copy to support the title
    <C4DButtonGroup slot="action">
      <C4DButtonGroupItem aria-label="" href="">
        test
      </C4DButtonGroupItem>
    </C4DButtonGroup>
    <C4DImage slot="image" class="cds--image" alt="" default-src={leadspaceImg}>
      <C4DImageItem
        media="(min-width: 672px)"
        srcset={leadspaceImg}></C4DImageItem>
      <C4DImageItem media="(min-width: 0)" srcset={leadspaceImg}></C4DImageItem>
    </C4DImage>
  </C4DLeadspace>
);

export const contentLeadspaceSearch = (
  <C4DLeadspaceWithSearch adjacent-theme="white-and-g10" scroll-behavior>
    <C4DLeadspaceWithSearchHeading>
      Find a product
    </C4DLeadspaceWithSearchHeading>
    <C4DLeadspaceWithSearchContent>
      <C4DLeadspaceWithSearchContentHeading>
        Innovate like a startup, scale for the enterprise
      </C4DLeadspaceWithSearchContentHeading>
      <C4DLeadspaceWithSearchContentCopy>
        Automate your software release process with continuous delivery (CD)—the
        most critical part of adopting DevOps. Build, test, and deploy code
        changes quickly, ensuring software is always ready for deployment.
      </C4DLeadspaceWithSearchContentCopy>
    </C4DLeadspaceWithSearchContent>
    <C4DSearchWithTypeahead
      slot="search"
      leadspace-search
      active
      should-remain-open></C4DSearchWithTypeahead>
  </C4DLeadspaceWithSearch>
);

export const tocContent = (
  <>
    <C4DLeadspaceBlock name="1" data-title="Lorem ipsum dolor sit amet">
      <C4DLeadspaceBlockHeading>
        Lorem ipsum dolor sit amet
      </C4DLeadspaceBlockHeading>
      <C4DLeadspaceBlockContent>
        <C4DContentBlockHeading>
          Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.
        </C4DContentBlockHeading>
        <C4DContentBlockCopy slot="copy">
          Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
          nisi ut aliquip ex ea commodo consequat.
        </C4DContentBlockCopy>
        <C4DLeadspaceBlockMedia slot="media">
          <C4DVideoPlayerContainer video-id="1_9h94wo6b"></C4DVideoPlayerContainer>
        </C4DLeadspaceBlockMedia>
        <C4DLinkList type="end">
          <C4DLinkListHeading>Featured products</C4DLinkListHeading>
          <C4DLinkListItem href="https://example.com">
            IBM Cloud Continuous Delivery <ArrowRight20 slot="icon" />
          </C4DLinkListItem>
          <C4DLinkListItem href="https://example.com">
            UrbanCode <ArrowRight20 slot="icon" />
          </C4DLinkListItem>
          <C4DLinkListItem href="https://example.com">
            View all products <ArrowRight20 slot="icon" />
          </C4DLinkListItem>
        </C4DLinkList>
        <C4DLeadspaceBlockCTA>
          <C4DButtonGroupItem href="www.ibm.com">
            Contact sales <ArrowRight20 slot="icon" />
          </C4DButtonGroupItem>
        </C4DLeadspaceBlockCTA>
      </C4DLeadspaceBlockContent>
    </C4DLeadspaceBlock>

    <C4DContentBlockSegmented
      name="2"
      data-title="Pharetra pharetra massa massa ultricies mi quis.">
      <C4DContentBlockHeading>
        Pharetra pharetra massa massa ultricies mi quis.
      </C4DContentBlockHeading>
      {Array.from([1, 2]).map(() => contentBlockSegmentedItems)}
    </C4DContentBlockSegmented>
    <C4DFeatureCard size="large" href="https://example.com">
      <C4DImage slot="image" alt="Image alt text" default-src={imgLg1x1}>
        <C4DImageItem
          media="(min-width: 991px)"
          srcset={imgLg1x1}></C4DImageItem>
      </C4DImage>
      <C4DCardEyebrow>scelerisque purus</C4DCardEyebrow>
      <C4DCardHeading>Elementum nibh tellus molestie nunc?</C4DCardHeading>
      <p>
        Habitant morbi tristique senectus et netus et malesuada fames. Habitant
        morbu tristique.
      </p>
      <C4DFeatureCardFooter>
        <ArrowRight20 slot="icon" />
      </C4DFeatureCardFooter>
    </C4DFeatureCard>

    <C4DContentBlockSegmented
      name="3"
      data-title="Elementum nibh tellus molestie nunc non.">
      <C4DContentBlockHeading>
        Elementum nibh tellus molestie nunc non.
      </C4DContentBlockHeading>
      {Array.from([1, 2]).map(() => contentBlockSegmentedItemsWithImage)}
      <C4DCardCTA slot="footer" cta-type="local" href="https://example.com">
        Lorem ipsum dolor
        <C4DCardCTAFooter></C4DCardCTAFooter>
      </C4DCardCTA>
    </C4DContentBlockSegmented>

    <C4DCalloutWithMedia>
      <C4DContentBlockHeading slot="heading">
        Mauris ultrices eros in cursus
      </C4DContentBlockHeading>
      <C4DCalloutWithMediaCopy size="sm">
        Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada
        proin libero nunc consequat. In est ante in nibh mauris cursus mattis.
        Turpis tincidunt id aliquet risus feugiat in. Vel facilisis volutpat est
        velit egestas dui.
      </C4DCalloutWithMediaCopy>
      <C4DCalloutWithMediaVideo video-id="1_9h94wo6b"></C4DCalloutWithMediaVideo>
    </C4DCalloutWithMedia>

    <C4DContentBlockHorizontal name="4" data-title="Tincidunt ornare massa">
      <C4DContentBlockHeading>Tincidunt ornare massa</C4DContentBlockHeading>
      {Array.from([1, 2]).map(() => contentItemHorizontal)}
    </C4DContentBlockHorizontal>

    <C4DLogoGrid
      name="5"
      data-title="Lobortis elementum nibh tellus"
      hide-border="true">
      <C4DContentBlockHeading>
        Lobortis elementum nibh tellus
      </C4DContentBlockHeading>
      {logosGroup &&
        logosGroup.map((elem) => (
          <C4DLogoGridItem
            default-src={elem.imgSrc}
            alt={elem.altText}></C4DLogoGridItem>
        ))}
    </C4DLogoGrid>

    <C4DContentBlockCards name="6" data-title="Aliquam condimentum interdum">
      <C4DContentBlockHeading>
        Aliquam condimentum interdum
      </C4DContentBlockHeading>
      <C4DCardGroup>
        {Array.from([1, 2, 3]).map(() => cardGroupItems)}
      </C4DCardGroup>
    </C4DContentBlockCards>
    <C4DCalloutQuote>
      Duis aute irure dolor in reprehenderit
      <C4DQuoteSourceHeading>Lorem ipsum dolor sit amet</C4DQuoteSourceHeading>
      <C4DQuoteSourceCopy>consectetur adipiscing elit</C4DQuoteSourceCopy>
      <C4DQuoteSourceBottomCopy>IBM Cloud</C4DQuoteSourceBottomCopy>
      <C4DCalloutLinkWithIcon slot="footer" href="https://example.com">
        Link with Icon <ArrowRight20 slot="icon" />
      </C4DCalloutLinkWithIcon>
    </C4DCalloutQuote>

    <C4DCTABlock
      name="7"
      data-title="Duis aute irure dolor in reprehenderit"
      no-border>
      <C4DContentBlockHeading>Take the next step</C4DContentBlockHeading>
      <C4DContentBlockCopy>
        Want to discuss your options with a DevOps expert? <br />
        Contact our sales team to evaluate your needs.
      </C4DContentBlockCopy>
      <C4DButtonGroup slot="action">
        <C4DButtonGroupItem href="https://example.com">
          Secondary Button <ArrowRight20 slot="icon" />
        </C4DButtonGroupItem>
        <C4DButtonGroupItem href="https://example.com">
          Primary button <ArrowRight20 slot="icon" />
        </C4DButtonGroupItem>
      </C4DButtonGroup>
      <C4DCTABlockItemRow no-border>
        <C4DCTABlockItem>
          <C4DContentItemHeading>Get connected</C4DContentItemHeading>
          <C4DContentItemCopy>
            IBM DevOps partners have a wide range of expertise. Find one to
            build the right solution for you.
          </C4DContentItemCopy>
          <C4DTextCTA
            slot="footer"
            cta-type="local"
            icon-placement="right"
            href="example.com">
            Find a partner
          </C4DTextCTA>
        </C4DCTABlockItem>
        <C4DCTABlockItem>
          <C4DContentItemHeading>Learn how</C4DContentItemHeading>
          <C4DContentItemCopy>
            IBM DevOps partners have a wide range of expertise
          </C4DContentItemCopy>
          <C4DTextCTA
            slot="footer"
            cta-type="local"
            icon-placement="right"
            href="example.com">
            Browse tutorials
          </C4DTextCTA>
        </C4DCTABlockItem>
      </C4DCTABlockItemRow>
    </C4DCTABlock>
  </>
);

export const StoryContent = (
  config = {
    l1: false,
    leadspace: false,
    tocLayout: TOC_TYPES.DEFAULT,
  }
) => {
  const mainClasses = [
    'cds--content',
    'cds-ce-demo-devenv--ui-shell-content',
    config?.l1 ? 'has-l1' : null,
    config?.leadspace ? 'has-leadspace' : null,
  ]
    .filter((className) => className != null)
    .join(' ');

  return (
    <div className={mainClasses}>
      {config?.leadspace ? contentLeadspace : null}
      {config?.tocLayout === TOC_TYPES.HORIZONTAL ? (
        <C4DTableOfContents stickyOffset={48} toc-layout={config.tocLayout}>
          <div className="cds--row">
            <div className="cds--col-lg-12">{tocContent}</div>
          </div>
        </C4DTableOfContents>
      ) : (
        <C4DTableOfContents stickyOffset={48} toc-layout={config.tocLayout}>
          {tocContent}
        </C4DTableOfContents>
      )}
    </div>
  );
};

export const StoryContentNoToC = () => (
  <div
    className="cds-ce-demo-devenv--ui-shell-content"
    style={{ paddingRight: '1rem' }}>
    <div className="cds--gridcdsds--col-lg-8">
      {contentLeadspaceSearch}

      <C4DContentBlockSegmented>
        <C4DContentBlockHeading>
          Pharetra pharetra massa massa ultricies mi quis.
        </C4DContentBlockHeading>
        {Array.from([1, 2]).map(() => contentBlockSegmentedItems)}
      </C4DContentBlockSegmented>

      <C4DFeatureCard size="large" href="https://example.com">
        <C4DImage slot="image" alt="Image alt text" default-src={imgLg1x1}>
          <C4DImageItem
            media="(min-width: 991px)"
            srcset={imgLg1x1}></C4DImageItem>
        </C4DImage>
        <C4DCardEyebrow>scelerisque purus</C4DCardEyebrow>
        <C4DCardHeading>Elementum nibh tellus molestie nunc?</C4DCardHeading>
        <p>
          Habitant morbi tristique senectus et netus et malesuada fames.
          Habitant morbu tristique.
        </p>
        <C4DFeatureCardFooter>
          <ArrowRight20 slot="icon" />
        </C4DFeatureCardFooter>
      </C4DFeatureCard>

      <C4DContentBlockSegmented>
        <C4DContentBlockHeading>
          Elementum nibh tellus molestie nunc non.
        </C4DContentBlockHeading>
        {Array.from([1, 2]).map(() => contentBlockSegmentedItemsWithImage)}
        <C4DCardCTA slot="footer" cta-type="local" href="https://example.com">
          Lorem ipsum dolor
          <C4DCardCTAFooter></C4DCardCTAFooter>
        </C4DCardCTA>
      </C4DContentBlockSegmented>

      <C4DCalloutWithMedia>
        <C4DContentBlockHeading slot="heading">
          Mauris ultrices eros in cursus
        </C4DContentBlockHeading>
        <C4DCalloutWithMediaCopy size="sm">
          Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada
          proin libero nunc consequat. In est ante in nibh mauris cursus mattis.
          Turpis tincidunt id aliquet risus feugiat in. Vel facilisis volutpat
          est velit egestas dui.
        </C4DCalloutWithMediaCopy>
        <C4DCalloutWithMediaVideo video-id="1_9h94wo6b"></C4DCalloutWithMediaVideo>
      </C4DCalloutWithMedia>

      <C4DContentBlockHorizontal>
        <C4DContentBlockHeading>Tincidunt ornare massa</C4DContentBlockHeading>
        {Array.from([1, 2]).map(() => contentItemHorizontal)}
      </C4DContentBlockHorizontal>

      <C4DLogoGrid hide-border="true">
        <C4DContentBlockHeading>
          Lobortis elementum nibh tellus
        </C4DContentBlockHeading>
        {logosGroup &&
          logosGroup.map((elem) => (
            <C4DLogoGridItem
              default-src={elem.imgSrc}
              alt={elem.altText}></C4DLogoGridItem>
          ))}
      </C4DLogoGrid>

      <C4DContentBlockCards>
        <C4DContentBlockHeading>
          Aliquam condimentum interdum
        </C4DContentBlockHeading>
        <C4DCardGroup>
          {Array.from([1, 2, 3]).map(() => cardGroupItems)}
        </C4DCardGroup>
      </C4DContentBlockCards>

      <C4DCalloutQuote>
        Duis aute irure dolor in reprehenderit
        <C4DQuoteSourceHeading>
          Lorem ipsum dolor sit amet
        </C4DQuoteSourceHeading>
        <C4DQuoteSourceCopy>consectetur adipiscing elit</C4DQuoteSourceCopy>
        <C4DQuoteSourceBottomCopy>IBM Cloud</C4DQuoteSourceBottomCopy>
        <C4DCalloutLinkWithIcon slot="footer" href="https://example.com">
          Link with Icon <ArrowRight20 slot="icon" />
        </C4DCalloutLinkWithIcon>
      </C4DCalloutQuote>

      <C4DCTABlock no-border>
        <C4DContentBlockHeading>Take the next step</C4DContentBlockHeading>
        <C4DContentBlockCopy>
          Want to discuss your options with a DevOps expert? <br />
          Contact our sales team to evaluate your needs.
        </C4DContentBlockCopy>

        <C4DButtonGroup slot="action">
          <C4DButtonGroupItem href="https://example.com">
            Secondary Button <ArrowRight20 slot="icon" />
          </C4DButtonGroupItem>
          <C4DButtonGroupItem href="https://example.com">
            Primary button <ArrowRight20 slot="icon" />
          </C4DButtonGroupItem>
        </C4DButtonGroup>

        <C4DCTABlockItemRow no-border>
          <C4DCTABlockItem>
            <C4DContentItemHeading>Get connected</C4DContentItemHeading>
            <C4DContentItemCopy>
              IBM DevOps partners have a wide range of expertise. Find one to
              build the right solution for you.
            </C4DContentItemCopy>
            <C4DTextCTA
              slot="footer"
              cta-type="local"
              icon-placement="right"
              href="example.com">
              Find a partner
            </C4DTextCTA>
          </C4DCTABlockItem>

          <C4DCTABlockItem>
            <C4DContentItemHeading>Learn how</C4DContentItemHeading>
            <C4DContentItemCopy>
              IBM DevOps partners have a wide range of expertise
            </C4DContentItemCopy>
            <C4DTextCTA
              slot="footer"
              cta-type="local"
              icon-placement="right"
              href="example.com">
              Browse tutorials
            </C4DTextCTA>
          </C4DCTABlockItem>
        </C4DCTABlockItemRow>
      </C4DCTABlock>
    </div>
  </div>
);

export default { StoryContent, StoryContentNoToC };
/* eslint-enable max-len */

// packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
/* eslint-disable max-len */
/**
 * Copyright IBM Corp. 2016, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit-element';
import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20';
import logosGroup from '../../../logo-grid/__stories__/data/logos.js';
import { TOC_TYPES } from '../../../table-of-contents/defs';

import imgSm16x9 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--002.jpg';
import imgMd16x9 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--002.jpg';
import imgLg16x9 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--002.jpg';
import imgLg1x1 from '../../../../../../storybook-images/assets/720/fpo--1x1--720x720--005.jpg';
import imgXlg4x3 from '../../../../../../storybook-images/assets/1312/fpo--4x3--1312x984--003.jpg';

import leadspaceImg from '../../../../../../storybook-images/assets/leadspace/fpo--leadspace--1584x560--002.jpg';

export const image = html`
  <dds-image-with-caption
    alt="Image alt text"
    default-src="${imgLg16x9}"
    heading="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  >
    <dds-image-item media="(min-width: 672px)" srcset="${imgLg16x9}"> </dds-image-item>
    <dds-image-item media="(min-width: 400px)" srcset="${imgMd16x9}"> </dds-image-item>
    <dds-image-item media="(min-width: 320px)" srcset="${imgSm16x9}"> </dds-image-item>
  </dds-image-with-caption>
`;

export const contentBlockSegmentedItems = html`
  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
    <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="https://example.com"
      >Lorem Ipsum dolor sit</dds-text-cta
    >
  </dds-content-block-segmented-item>

  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
  </dds-content-block-segmented-item>
`;

export const contentBlockSegmentedItemsWithImage = html`
  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
    ${image}
    <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="https://example.com"
      >Lorem Ipsum dolor sit</dds-text-cta
    >
  </dds-content-block-segmented-item>
`;

export const contentItemHorizontal = html`
  <dds-content-item-horizontal>
    <dds-content-item-horizontal-eyebrow>Lorem ipsum</dds-content-item-horizontal-eyebrow>
    <dds-content-item-heading>Aliquam condimentum</dds-content-item-heading>
    <dds-content-item-horizontal-copy
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit.
      Phasellus at elit sollicitudin.</dds-content-item-horizontal-copy
    >
    <dds-link-list slot="footer" type="vertical">
      <dds-link-list-item-cta icon-placement="right" href="https://www.ibm.com" cta-type="local">
        Link text
      </dds-link-list-item-cta>
      <dds-link-list-item-cta icon-placement="right" href="https://www.ibm.com" cta-type="external">
        External link text
      </dds-link-list-item-cta>
    </dds-link-list>
  </dds-content-item-horizontal>
`;

export const universalBanner = srcImage => html`
  <dds-universal-banner image-width="4-col">
    <dds-universal-banner-image slot="image" default-src="${srcImage}"></dds-universal-banner-image>
    <dds-universal-banner-heading slot="heading">heading</dds-universal-banner-heading>
    <dds-universal-banner-copy slot="copy">copy</dds-universal-banner-copy>
    <dds-button-cta slot="cta" cta-type="local" kind="tertiary" href="https://www.example.com">
      cta copy
    </dds-button-cta>
  </dds-universal-banner>
`;

export const cardGroupItems = html`
  <dds-card-group-item href="https://example.com">
    <dds-image slot="image" alt="Image alt text" default-src="${imgXlg4x3}"> </dds-image>
    <dds-card-eyebrow>Topic</dds-card-eyebrow>
    <dds-card-heading>Natural Language Processing.</dds-card-heading>
    <dds-card-cta-footer slot="footer">
      ${ArrowRight20({ slot: 'icon' })}
    </dds-card-cta-footer>
  </dds-card-group-item>
`;

export const contentLeadspace = html`
  <dds-leadspace size="medium" gradient-style-scheme="true" alt="" default-src="${leadspaceImg}">
    <dds-leadspace-heading>Leadspace Title</dds-leadspace-heading>
    Use this area for a short line of copy to support the title
    <dds-button-group slot="action">
      <dds-button-group-item aria-label="" href="">test</dds-button-group-item>
    </dds-button-group>
    <dds-image slot="image" class="bx--image" alt="" default-src="${leadspaceImg}">
      <dds-image-item media="(min-width: 672px)" srcset="${leadspaceImg}"></dds-image-item>
      <dds-image-item media="(min-width: 0)" srcset="${leadspaceImg}"></dds-image-item>
    </dds-image>
  </dds-leadspace>
`;

export const contentLeadspaceSearch = html`
  <dds-leadspace-with-search adjacent-theme="white-and-g10" scroll-behavior>
    <dds-leadspace-with-search-heading>Find a product</dds-leadspace-with-search-heading>
    <dds-leadspace-with-search-content>
      <dds-leadspace-with-search-content-heading
        >Innovate like a startup, scale for the enterprise</dds-leadspace-with-search-content-heading
      >
      <dds-leadspace-with-search-content-copy>
        Automate your software release process with continuous delivery (CD)—the most critical part of adopting DevOps. Build,
        test, and deploy code changes quickly, ensuring software is always ready for deployment.
      </dds-leadspace-with-search-content-copy>
    </dds-leadspace-with-search-content>
    <dds-search-with-typeahead slot="search" leadspace-search active should-remain-open></dds-search-with-typeahead>
  </dds-leadspace-with-search>
`;

export const tocContent = html`
  <a name="1" data-title="Lorem ipsum dolor sit amet"></a>
  <dds-leadspace-block>
    <dds-leadspace-block-heading>Lorem ipsum dolor sit amet</dds-leadspace-block-heading>
    <dds-leadspace-block-content>
      <dds-content-block-heading>
        Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.
      </dds-content-block-heading>
      <dds-content-block-copy slot="copy"
      >Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
        ut aliquip ex ea commodo consequat.
      </dds-content-block-copy>
      <dds-leadspace-block-media slot="media">
        <dds-video-player-container video-id="1_9h94wo6b"></dds-video-player-container>
      </dds-leadspace-block-media>
      <dds-link-list type="end">
        <dds-link-list-heading>Featured products</dds-link-list-heading>
        <dds-link-list-item href="https://example.com">
          IBM Cloud Continuous Delivery ${ArrowRight20({ slot: 'icon' })}
        </dds-link-list-item>
        <dds-link-list-item href="https://example.com">
          UrbanCode ${ArrowRight20({ slot: 'icon' })}
        </dds-link-list-item>
        <dds-link-list-item href="https://example.com">
          View all products ${ArrowRight20({ slot: 'icon' })}
        </dds-link-list-item>
      </dds-link-list>
      <dds-leadspace-block-cta>
        <dds-button-group-item href="www.ibm.com">Contact sales ${ArrowRight20({
          slot: 'icon',
        })}</dds-button-group-item>
      </dds-leadspace-block-cta>
    </dds-leadspace-block-content>
  </dds-leadspace-block>

  <a name="2" data-title="Pharetra pharetra massa massa ultricies mi quis."></a>
  <dds-content-block-segmented>
    <dds-content-block-heading>Pharetra pharetra massa massa ultricies mi quis.</dds-content-block-heading>
    ${Array.from([1, 2]).map(() => contentBlockSegmentedItems)}
  </dds-content-block-segmented>
  <dds-feature-card size='large' href="https://example.com">
    <dds-image slot="image" alt="Image alt text"
                default-src="${imgLg1x1}"
    >
      </dds-image-item>
      <dds-image-item
        media="(min-width: 991px)"
        srcset="${imgLg1x1}"
      >
    </dds-image>
    <dds-card-eyebrow>scelerisque purus</dds-card-eyebrow>
    <dds-card-heading>Elementum nibh tellus molestie nunc?</dds-card-heading>
    <p>Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbu tristique.</p>
    <dds-feature-card-footer>
      ${ArrowRight20({ slot: 'icon' })}
    </dds-feature-card-footer>
  </dds-feature-card>

  <a name="3" data-title="Elementum nibh tellus molestie nunc non."></a>
  <dds-content-block-segmented>
    <dds-content-block-heading>Elementum nibh tellus molestie nunc non.
    </dds-content-block-heading>
    ${Array.from([1, 2]).map(() => contentBlockSegmentedItemsWithImage)}
    <dds-card-cta slot="footer" cta-type="local" href="https://example.com">
      Lorem ipsum dolor
      <dds-card-cta-footer></dds-card-cta-footer>
    </dds-card-cta>
  </dds-content-block-segmented>

  <dds-callout-with-media>
    <dds-content-block-heading slot="heading">Mauris ultrices eros in cursus</dds-content-block-heading>
    <dds-callout-with-media-copy size="sm"
    >Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada proin libero nunc consequat.
      In est ante in nibh mauris cursus mattis. Turpis tincidunt id aliquet risus feugiat in.
      Vel facilisis volutpat est velit egestas dui.
    </dds-callout-with-media-copy>
    <dds-callout-with-media-video video-id="1_9h94wo6b"></dds-callout-with-media-video>
  </dds-callout-with-media>

  <a name="4" data-title="Tincidunt ornare massa"></a>
  <dds-content-group-horizontal>
    <dds-content-block-heading>Tincidunt ornare massa</dds-content-block-heading>
    ${Array.from([1, 2]).map(() => contentItemHorizontal)}
  </dds-content-group-horizontal>

  <a name="5" data-title="Lobortis elementum nibh tellus"></a>
  <dds-logo-grid ?hide-border="true">
    <dds-content-block-heading>Lobortis elementum nibh tellus</dds-content-block-heading>
    ${logosGroup &&
      logosGroup.map(
        elem => html`
          <dds-logo-grid-item default-src="${elem.imgSrc}" alt="${elem.altText}"></dds-logo-grid-item>
        `
      )}
  </dds-logo-grid>

  <a name="6" data-title="Aliquam condimentum interdum"></a>
  <dds-content-block-cards>
    <dds-content-block-heading>Aliquam condimentum interdum</dds-content-block-heading>
    <dds-card-group>
      ${Array.from([1, 2, 3]).map(() => cardGroupItems)}
    </dds-card-group>
  </dds-content-block-cards>
  <dds-callout-quote>
    Duis aute irure dolor in reprehenderit
    <dds-quote-source-heading>
      Lorem ipsum dolor sit amet
    </dds-quote-source-heading>
    <dds-quote-source-copy>
      consectetur adipiscing elit
    </dds-quote-source-copy>
    <dds-quote-source-bottom-copy>
      IBM Cloud
    </dds-quote-source-bottom-copy>
    <dds-callout-link-with-icon slot="footer" href="https://example.com">
      Link with Icon ${ArrowRight20({ slot: 'icon' })}
    </dds-callout-link-with-icon>
  </dds-callout-quote>

  <a name="7" data-title="Duis aute irure dolor in reprehenderit"></a>
  <dds-cta-block no-border>
    <dds-content-block-heading>Take the next step</dds-content-block-heading>
    <dds-content-block-copy>Want to discuss your options with a DevOps expert? <br />
      Contact our sales team to evaluate your needs.</dds-content-block-copy>
    <dds-button-group slot="action">
      <dds-button-group-item href="https://example.com">
        Secondary Button ${ArrowRight20({ slot: 'icon' })}
      </dds-button-group-item>
      <dds-button-group-item href="https://example.com">
        Primary button ${ArrowRight20({ slot: 'icon' })}
      </dds-button-group-item>
    </dds-button-group>
    <dds-cta-block-item-row no-border>
      <dds-cta-block-item>
        <dds-content-item-heading>Get connected</dds-content-item-heading>
        <dds-content-item-copy
        >IBM DevOps partners have a wide range of expertise. Find one to build the right solution for
          you.</dds-content-item-copy
        >
        <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
          Find a partner
        </dds-text-cta>
      </dds-cta-block-item>
      <dds-cta-block-item>
        <dds-content-item-heading>Learn how</dds-content-item-heading>
        <dds-content-item-copy>IBM DevOps partners have a wide range of expertise</dds-content-item-copy>
        <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
          Browse tutorials
        </dds-text-cta>
      </dds-cta-block-item>
    </dds-cta-block-item-row>
  </dds-cta-block>
`;

export const StoryContent = (
  config = {
    l1: false,
    leadspace: false,
    tocLayout: TOC_TYPES.DEFAULT,
  }
) => {
  const mainClasses = [
    'bx--content',
    'dds-ce-demo-devenv--ui-shell-content',
    config?.l1 ? 'has-l1' : null,
    config?.leadspace ? 'has-leadspace' : null,
  ]
    .filter(className => className != null)
    .join(' ');

  return html`
    <div class="${mainClasses}">
      ${config?.leadspace ? contentLeadspace : null}
      ${config?.tocLayout === TOC_TYPES.HORIZONTAL
        ? html`
            <dds-table-of-contents stickyOffset="48" toc-layout=${config.tocLayout}>
              <div class="bx--row">
                <div class="bx--col-lg-12">
                  ${tocContent}
                </div>
              </div>
            </dds-table-of-contents>
          `
        : html`
            <dds-table-of-contents stickyOffset="48" toc-layout=${config.tocLayout}>
              ${tocContent}
            </dds-table-of-contents>
          `}
    </div>
  `;
};

export const StoryContentNoToC = () =>
  html`
    <div class="dds-ce-demo-devenv--ui-shell-content" style='padding-right:1rem'>
      <div class="bx--grid bx--col-lg-8">
        ${contentLeadspaceSearch}

        <dds-content-block-segmented>
          <dds-content-block-heading>Pharetra pharetra massa massa ultricies mi quis.</dds-content-block-heading>
          ${Array.from([1, 2]).map(() => contentBlockSegmentedItems)}
        </dds-content-block-segmented>

        <dds-feature-card size='large' href="https://example.com">
          <dds-image slot="image" alt="Image alt text"
                      default-src="${imgLg1x1}"
          >
            </dds-image-item>
            <dds-image-item
              media="(min-width: 991px)"
              srcset="${imgLg1x1}"
            >
          </dds-image>
          <dds-card-eyebrow>scelerisque purus</dds-card-eyebrow>
          <dds-card-heading>Elementum nibh tellus molestie nunc?</dds-card-heading>
          <p>Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbu tristique.</p>
          <dds-feature-card-footer>
            ${ArrowRight20({ slot: 'icon' })}
          </dds-feature-card-footer>
        </dds-feature-card>

        <dds-content-block-segmented>
          <dds-content-block-heading>Elementum nibh tellus molestie nunc non.
          </dds-content-block-heading>
          ${Array.from([1, 2]).map(() => contentBlockSegmentedItemsWithImage)}
          <dds-card-cta slot="footer" cta-type="local" href="https://example.com">
            Lorem ipsum dolor
            <dds-card-cta-footer></dds-card-cta-footer>
          </dds-card-cta>
        </dds-content-block-segmented>

        <dds-callout-with-media>
          <dds-content-block-heading slot="heading">Mauris ultrices eros in cursus</dds-content-block-heading>
          <dds-callout-with-media-copy size="sm"
          >Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada proin libero nunc consequat.
            In est ante in nibh mauris cursus mattis. Turpis tincidunt id aliquet risus feugiat in.
            Vel facilisis volutpat est velit egestas dui.
          </dds-callout-with-media-copy>
          <dds-callout-with-media-video video-id="1_9h94wo6b"></dds-callout-with-media-video>
        </dds-callout-with-media>

        <dds-content-group-horizontal>
          <dds-content-block-heading>Tincidunt ornare massa</dds-content-block-heading>
          ${Array.from([1, 2]).map(() => contentItemHorizontal)}
        </dds-content-group-horizontal>

        <dds-logo-grid ?hide-border="true">
          <dds-content-block-heading>Lobortis elementum nibh tellus</dds-content-block-heading>
          ${logosGroup &&
            logosGroup.map(
              elem => html`
                <dds-logo-grid-item default-src="${elem.imgSrc}" alt="${elem.altText}"></dds-logo-grid-item>
              `
            )}
        </dds-logo-grid>

        <dds-content-block-cards>
          <dds-content-block-heading>Aliquam condimentum interdum</dds-content-block-heading>
          <dds-card-group>
            ${Array.from([1, 2, 3]).map(() => cardGroupItems)}
          </dds-card-group>
        </dds-content-block-cards>

        <dds-callout-quote>
          Duis aute irure dolor in reprehenderit
          <dds-quote-source-heading>
            Lorem ipsum dolor sit amet
          </dds-quote-source-heading>
          <dds-quote-source-copy>
            consectetur adipiscing elit
          </dds-quote-source-copy>
          <dds-quote-source-bottom-copy>
            IBM Cloud
          </dds-quote-source-bottom-copy>
          <dds-callout-link-with-icon slot="footer" href="https://example.com">
            Link with Icon ${ArrowRight20({ slot: 'icon' })}
          </dds-callout-link-with-icon>
        </dds-callout-quote>

        <dds-cta-block no-border>
          <dds-content-block-heading>Take the next step</dds-content-block-heading>
          <dds-content-block-copy>Want to discuss your options with a DevOps expert? <br />
            Contact our sales team to evaluate your needs.</dds-content-block-copy>

          <dds-button-group slot="action">
            <dds-button-group-item href="https://example.com">
              Secondary Button ${ArrowRight20({ slot: 'icon' })}
            </dds-button-group-item>
            <dds-button-group-item href="https://example.com">
              Primary button ${ArrowRight20({ slot: 'icon' })}
            </dds-button-group-item>
          </dds-button-group>

          <dds-cta-block-item-row no-border>
            <dds-cta-block-item>
              <dds-content-item-heading>Get connected</dds-content-item-heading>
              <dds-content-item-copy
              >IBM DevOps partners have a wide range of expertise. Find one to build the right solution for
                you.</dds-content-item-copy
              >
              <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
                Find a partner
              </dds-text-cta>
            </dds-cta-block-item>

            <dds-cta-block-item>
              <dds-content-item-heading>Learn how</dds-content-item-heading>
              <dds-content-item-copy>IBM DevOps partners have a wide range of expertise</dds-content-item-copy>
              <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
                Browse tutorials
              </dds-text-cta>
            </dds-cta-block-item>
          </dds-cta-block-item-row>
        </dds-cta-block>
      </div>
    </div>`;

export default { StoryContent, StoryContentNoToC };
/* eslint-enable max-len */
