// packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html } from 'lit-element';
import ArrowRight20 from 'carbon-web-components/es/icons/arrow--right/20';
import logosGroup from '../../../logo-grid/__stories__/data/logos.js';

import imgSm16x9 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--002.jpg';
import imgMd16x9 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--002.jpg';
import imgLg16x9 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--002.jpg';
import imgLg1x1 from '../../../../../../storybook-images/assets/720/fpo--1x1--720x720--005.jpg';
import imgXlg4x3 from '../../../../../../storybook-images/assets/1312/fpo--4x3--1312x984--003.jpg';

const image = html`
  <dds-image-with-caption
    alt="Image alt text"
    default-src="${imgLg16x9}"
    heading="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  >
    <dds-image-item media="(min-width: 672px)" srcset="${imgLg16x9}"> </dds-image-item>
    <dds-image-item media="(min-width: 400px)" srcset="${imgMd16x9}"> </dds-image-item>
    <dds-image-item media="(min-width: 320px)" srcset="${imgSm16x9}"> </dds-image-item>
  </dds-image-with-caption>
`;

const contentBlockSegmentedItems = html`
  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
    <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="https://example.com"
      >Lorem Ipsum dolor sit</dds-text-cta
    >
  </dds-content-block-segmented-item>

  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
  </dds-content-block-segmented-item>
`;

const contentBlockSegmentedItemsWithImage = html`
  <dds-content-block-segmented-item>
    <dds-content-group-heading>A scelerisque purus semper eget duis at tellus. </dds-content-group-heading>
    <dds-content-item-copy
      >Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.
    </dds-content-item-copy>
    ${image}
    <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="https://example.com"
      >Lorem Ipsum dolor sit</dds-text-cta
    >
  </dds-content-block-segmented-item>
`;

const contentItemHorizontal = html`
  <dds-content-item-horizontal>
    <dds-content-item-horizontal-eyebrow>Lorem ipsum</dds-content-item-horizontal-eyebrow>
    <dds-content-item-heading>Aliquam condimentum</dds-content-item-heading>
    <dds-content-item-horizontal-copy
      >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit.
      Phasellus at elit sollicitudin.</dds-content-item-horizontal-copy
    >
    <dds-link-list slot="footer" type="vertical">
      <dds-link-list-item-cta icon-placement="right" href="https://www.ibm.com" cta-type="local">
        Link text
      </dds-link-list-item-cta>
      <dds-link-list-item-cta icon-placement="right" href="https://www.ibm.com" cta-type="external">
        External link text
      </dds-link-list-item-cta>
    </dds-link-list>
  </dds-content-item-horizontal>
`;

const cardGroupItems = html`
  <dds-card-group-item href="https://example.com">
    <dds-image slot="image" alt="Image alt text" default-src="${imgXlg4x3}"> </dds-image>
    <dds-card-eyebrow>Topic</dds-card-eyebrow>
    <dds-card-heading>Natural Language Processing.</dds-card-heading>
    <dds-card-footer slot="footer">
      ${ArrowRight20({ slot: 'icon' })}
    </dds-card-footer>
  </dds-card-group-item>
`;

const StoryContent = () => html`
  <main class="bx--content dds-ce-demo-devenv--ui-shell-content">
    <div class="bx--grid">
      <dds-table-of-contents stickyOffset="48">
        <a name="1" data-title="Lorem ipsum dolor sit amet"></a>
        <dds-leadspace-block>
          <dds-leadspace-block-heading>Lorem ipsum dolor sit amet</dds-leadspace-block-heading>
          <dds-leadspace-block-content>
            <dds-content-block-heading>
              Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.
            </dds-content-block-heading>
            <dds-content-block-copy slot="copy"
              >Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
              ut aliquip ex ea commodo consequat.
            </dds-content-block-copy>
            <dds-leadspace-block-media slot="media">
              <dds-video-player-container video-id="1_9h94wo6b"></dds-video-player-container>
            </dds-leadspace-block-media>
            <dds-link-list type="end">
            <dds-link-list-heading>Featured products</dds-link-list-heading>
            <dds-link-list-item href="https://example.com">
              IBM Cloud Continuous Delivery ${ArrowRight20({ slot: 'icon' })}
            </dds-link-list-item>
            <dds-link-list-item href="https://example.com">
              UrbanCode ${ArrowRight20({ slot: 'icon' })}
            </dds-link-list-item>
            <dds-link-list-item href="https://example.com">
              View all products ${ArrowRight20({ slot: 'icon' })}
            </dds-link-list-item>
          </dds-link-list>
          <dds-leadspace-block-cta>
            <dds-button-group-item href="www.ibm.com">Contact sales ${ArrowRight20({ slot: 'icon' })}</dds-button-group-item>
          </dds-leadspace-block-cta>
          </dds-leadspace-block-content>
        </dds-leadspace-block>

        <a name="2" data-title="Pharetra pharetra massa massa ultricies mi quis."></a>
        <dds-content-block-segmented>
          <dds-content-block-heading>Pharetra pharetra massa massa ultricies mi quis.</dds-content-block-heading>
            ${Array.from([1, 2]).map(() => contentBlockSegmentedItems)}
        </dds-content-block-segmented>

        <dds-feature-card-block-large href="https://example.com">
          <dds-image slot="image" alt="Image alt text"
            default-src="${imgLg1x1}"
          >
            </dds-image-item>
            <dds-image-item
              media="(min-width: 991px)"
              srcset="${imgLg1x1}"
            >
          </dds-image>
          <dds-card-eyebrow>scelerisque purus</dds-card-eyebrow>
          <dds-card-heading>Elementum nibh tellus molestie nunc?</dds-card-heading>
          <p>Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbu tristique.</p>
          <dds-feature-card-block-large-footer>
            ${ArrowRight20({ slot: 'icon' })}
          </dds-feature-card-block-large-footer>
        </dds-feature-card-block-large>

        <a name="3" data-title="Elementum nibh tellus molestie nunc non."></a>
        <dds-content-block-segmented>
          <dds-content-block-heading>Elementum nibh tellus molestie nunc non.
          </dds-content-block-heading>
            ${Array.from([1, 2]).map(() => contentBlockSegmentedItemsWithImage)}
            <dds-card-cta slot="footer" cta-type="local" href="https://example.com">
              Lorem ipsum dolor
              <dds-card-cta-footer></dds-card-cta-footer>
            </dds-card-cta>
        </dds-content-block-segmented>

        <dds-callout-with-media>
          <dds-content-block-heading slot="heading">Mauris ultrices eros in cursus</dds-content-block-heading>
          <dds-content-item-copy
            >Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada proin libero nunc consequat.
            In est ante in nibh mauris cursus mattis. Turpis tincidunt id aliquet risus feugiat in.
            Vel facilisis volutpat est velit egestas dui.
          </dds-content-item-copy>
          <dds-callout-with-media-video video-id="1_9h94wo6b"></dds-callout-with-media-video>
        </dds-callout-with-media>

        <a name="4" data-title="Tincidunt ornare massa"></a>
        <dds-content-group-horizontal>
          <dds-content-block-heading>Tincidunt ornare massa</dds-content-block-heading>
          ${Array.from([1, 2]).map(() => contentItemHorizontal)}
        </dds-content-group-horizontal>

        <a name="5" data-title="Lobortis elementum nibh tellus"></a>
        <dds-logo-grid ?hide-border="true">
          <dds-content-block-heading>Lobortis elementum nibh tellus</dds-content-block-heading>
          ${logosGroup &&
            logosGroup.map(
              elem => html`
                <dds-logo-grid-item default-src="${elem.imgSrc}" alt="${elem.altText}"></dds-logo-grid-item>
              `
            )}
          <dds-logo-grid-link href="https://example.com">
            <p>Amet justo donec</p>
            ${ArrowRight20({ slot: 'footer' })}
          </dds-logo-grid-link>
        </dds-logo-grid>

        <a name="6" data-title="Aliquam condimentum interdum"></a>
        <dds-content-block-cards>
          <dds-content-block-heading>Aliquam condimentum interdum</dds-content-block-heading>
          <dds-card-group>
            ${Array.from([1, 2, 3]).map(() => cardGroupItems)}
          </dds-card-group>
        </dds-content-block-cards>

        <dds-callout-quote>
          Duis aute irure dolor in reprehenderit
        <dds-quote-source-heading>
          Lorem ipsum dolor sit amet
        </dds-quote-source-heading>
        <dds-quote-source-copy>
          consectetur adipiscing elit
        </dds-quote-source-copy>
        <dds-quote-source-bottom-copy>
          IBM Cloud
        </dds-quote-source-bottom-copy>
        <dds-link-with-icon slot="footer" href="https://example.com">
          Link with Icon ${ArrowRight20({ slot: 'icon' })}
        </dds-link-with-icon>
      </dds-callout-quote>

        <a name="7" data-title="Duis aute irure dolor in reprehenderit"></a>
        <dds-cta-section>
          <dds-content-block-heading>Take the next step</dds-content-block-heading>
          <dds-cta-section-copy>
            Want to discuss your options with a DevOps expert? Contact our sales team to evaluate your needs.
          </dds-cta-section-copy>

          <dds-button-group slot="action">
            <dds-button-group-item href="https://example.com">
              Secondary Button ${ArrowRight20({ slot: 'icon' })}
            </dds-button-group-item>
            <dds-button-group-item href="https://example.com">
              Primary button ${ArrowRight20({ slot: 'icon' })}
            </dds-button-group-item>
          </dds-button-group>

          <dds-cta-section-item>
            <dds-cta-section-item-heading>Get connected</dds-cta-section-item-heading>
            <dds-cta-section-item-copy
              >IBM DevOps partners have a wide range of expertise. Find one to build the right solution for
              you.</dds-cta-section-item-copy
            >
            <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
              Find a partner
            </dds-text-cta>
          </dds-cta-section-item>

          <dds-cta-section-item>
            <dds-cta-section-item-heading>Learn how</dds-cta-section-item-heading>
            <dds-cta-section-item-copy>IBM DevOps partners have a wide range of expertise</dds-cta-section-item-copy>
            <dds-text-cta slot="footer" cta-type="local" icon-placement="right" href="example.com">
              Browse tutorials
            </dds-text-cta>
          </dds-cta-section-item>
        </dds-cta-section>
      </dds-table-of-contents>
    </div>
  </main>
`;

export default StoryContent;

// packages/react/src/components/DotcomShell/__stories__/data/content.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/* eslint-disable jsx-a11y/anchor-is-valid, jsx-a11y/anchor-has-content */
import {
  CalloutQuote,
  CalloutWithMedia,
  ContentBlockCards,
  ContentBlockSegmented,
  ContentGroupHorizontal,
  CTASection,
  Layout,
  LeadSpaceBlock,
  LogoGrid,
  FeatureCard,
  TableOfContents,
} from '../../../../index';

import { ArrowRight20 } from '@carbon/icons-react';
import imgLg16x9 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--003.jpg';
import imgLg16x9_2 from '../../../../../../storybook-images/assets/720/fpo--16x9--720x405--004.jpg';
import imgLg1x1 from '../../../../../../storybook-images/assets/720/fpo--1x1--720x720--004.jpg';
import imgMd16x9 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--003.jpg';
import imgMd16x9_2 from '../../../../../../storybook-images/assets/480/fpo--16x9--480x270--004.jpg';
import imgSm16x9 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--003.jpg';
import imgSm16x9_2 from '../../../../../../storybook-images/assets/320/fpo--16x9--320x180--004.jpg';
import imgSm1x1 from '../../../../../../storybook-images/assets/320/fpo--1x1--320x320--001.jpg';
import imgXlg4x3 from '../../../../../../storybook-images/assets/1312/fpo--4x3--1312x984--002.jpg';
import React from 'react';

/**
 * DDS patterns template
 *
 * @returns {*} JSX for Learn template
 */
const Content = () => (
  <>
    <TableOfContents menuLabel="Jump to" theme="white" stickyOffset="48">
      <a name="section-1" data-title="Lorem ipsum dolor sit amet" />
      <Layout type="2-1">
        <div>
          <LeadSpaceBlock
            title="Lorem ipsum dolor sit amet"
            copy="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
            heading="Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut."
            mediaType="video"
            mediaData={{
              videoId: '1_9h94wo6b',
              showDescription: true,
            }}
            items={{
              heading: 'Featured products',
              items: [
                {
                  type: 'local',
                  copy: 'IBM Cloud Continuous Delivery',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
                {
                  type: 'local',
                  copy: 'UrbanCode',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
                {
                  type: 'local',
                  copy: 'View all products',
                  cta: {
                    href: 'https://ibm.com',
                  },
                },
              ],
            }}
            cta={{
              style: 'button',
              type: 'local',
              buttons: [
                {
                  type: 'local',
                  copy: 'Excepteur sint occaecat',
                  href: 'https://example.com/',
                },
              ],
            }}
          />
        </div>
        <></>
      </Layout>

      <a
        name="section-2"
        data-title="Pharetra pharetra massa massa ultricies mi quis."
      />
      <ContentBlockSegmented
        heading="Pharetra pharetra massa massa ultricies mi quis."
        items={[
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
          },
        ]}
      />
      <FeatureCard
        card={{
          eyebrow: 'scelerisque purus',
          heading: 'Elementum nibh tellus molestie nunc?',
          copy:
            'Habitant morbi tristique senectus et netus et malesuada fames. Habitant morbi tristique.',
          cta: {
            href: 'https://example.com',
            icon: {
              src: ArrowRight20,
            },
          },
          image: {
            defaultSrc: imgLg1x1,
            alt: 'Image alt text',
          },
        }}
        size={'large'}
      />

      <a
        name="section-3"
        data-title="Elementum nibh tellus molestie nunc non"
      />
      <ContentBlockSegmented
        heading="Elementum nibh tellus molestie nunc non."
        items={[
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            image: {
              heading: 'Mauris iaculis eget dolor nec hendrerit.',
              image: {
                sources: [
                  {
                    src: imgSm16x9,
                    breakpoint: 320,
                  },
                  {
                    src: imgMd16x9,
                    breakpoint: 400,
                  },
                  {
                    src: imgLg16x9,
                    breakpoint: 672,
                  },
                ],
                alt: 'Image alt text',
                defaultSrc: imgLg16x9,
              },
            },
            cta: {
              type: 'local',
              copy: 'Lorem Ipsum dolor sit',
              href: 'https://example.com',
            },
          },
          {
            heading: 'A scelerisque purus semper eget duis at tellus.',
            copy:
              'Elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames.',
            image: {
              heading: 'Mauris iaculis eget dolor nec hendrerit.',
              image: {
                sources: [
                  {
                    src: imgSm16x9_2,
                    breakpoint: 320,
                  },
                  {
                    src: imgMd16x9_2,
                    breakpoint: 400,
                  },
                  {
                    src: imgLg16x9_2,
                    breakpoint: 672,
                  },
                ],
                alt: 'Image alt text',
                defaultSrc: imgLg16x9_2,
              },
            },
          },
        ]}
        cta={{
          style: 'card',
          disableImage: true,
          type: 'video',
          media: {
            src: '1_9h94wo6b',
            type: 'video',
          },
        }}
        mediaType="image"
      />

      <CalloutWithMedia
        heading="Mauris ultrices eros in cursus"
        copy="Porttitor eget dolor morbi non arcu. Et ligula ullamcorper malesuada proin libero nunc consequat. In est ante in nibh mauris cursus mattis. Turpis tincidunt id aliquet risus feugiat in. Vel facilisis volutpat est velit egestas dui."
        mediaType="video"
        mediaData={{
          videoId: '1_9h94wo6b',
        }}
      />

      <a name="section-4" data-title="Tincidunt ornare massa" />
      <ContentGroupHorizontal
        heading="Tincidunt ornare massa"
        items={[
          {
            eyebrow: 'Lorem ipsum',
            heading: 'Aliquam condimentum',
            copy:
              'Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin.',
            cta: {
              heading: 'Aliquam condimentum',
              items: [
                {
                  type: 'local',
                  copy: 'Link text',
                  href: 'https://example.com',
                },
                {
                  type: 'external',
                  copy: 'External link text',
                  href: 'https://example.com',
                },
              ],
            },
          },
          {
            eyebrow: 'Lorem ipsum',
            heading: 'Aliquam condimentum',
            copy:
              'Lorem ipsum dolor sit amet, _consectetur_ adipiscing elit. Aenean et ultricies est. Mauris iaculis eget dolor nec hendrerit. Phasellus at elit sollicitudin.',
            cta: {
              heading: 'Aliquam condimentum',
              items: [
                {
                  type: 'local',
                  copy: 'Link text',
                  href: 'https://example.com',
                },
                {
                  type: 'external',
                  copy: 'External link text',
                  href: 'https://example.com',
                },
              ],
            },
          },
        ]}
      />

      <a name="section-5" data-title="Lobortis elementum nibh tellus" />
      <LogoGrid
        heading="Lobortis elementum nibh tellus"
        logosGroup={[
          {
            title: 'Company A',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company B',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company C',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company D',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company E',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
          {
            title: 'Company F',
            imgSrc: imgSm1x1,
            altText: 'Image alt text',
            href: 'http://example.com/',
          },
        ]}
        ctaCopy="Amet justo donec"
        ctaHref="https://www.example.com"
      />

      <a name="section-6" data-title="Aliquam condimentum interdum" />
      <ContentBlockCards
        heading="Aliquam condimentum interdum"
        cards={[
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
          {
            image: {
              defaultSrc: imgXlg4x3,
              alt: 'Image alt text',
            },
            eyebrow: 'Topic',
            heading: 'Natural language processing.',
            cta: {
              href: 'https://www.example.com',
            },
          },
        ]}
      />
      <a name="section-7" data-title="Duis aute irure dolor in reprehenderit" />
      <CalloutQuote
        quote={{
          copy: 'Duis aute irure dolor in reprehenderit',
          source: {
            heading: 'Lorem ipsum',
            copy: 'dolor sit amet',
          },
          cta: {
            copy: 'Link with Icon',
            type: 'local',
            href: 'https://example.com',
          },
        }}
      />
    </TableOfContents>
    <div className="bx--grid" style={{ backgroundColor: '#f4f4f4' }}>
      <div className="bx--row">
        <div className="bx--col-sm-4 bx--col-lg-12 bx--offset-lg-4">
          <CTASection
            theme="g10"
            cta={{
              style: 'button',
              type: 'local',
              buttons: [
                {
                  type: 'local',
                  copy: 'Contact sales',
                  href: 'https://example.com/',
                },
              ],
            }}
            items={[
              {
                heading: 'Get connected',
                copy:
                  'IBM DevOps partners have a wide range of expertise. Find one to build the right solution for you.',
                cta: {
                  copy: 'Find a partner',
                  type: 'local',
                  href: 'https://example.com/',
                },
              },
              {
                heading: 'Learn how',
                copy:
                  'Dig into more self-directed learning about DevOps methodologies.',
                cta: {
                  copy: 'Browse tutorials',
                  type: 'local',
                  href: 'https://example.com/',
                },
              },
            ]}
            heading="Take the next step"
            copy="Want to discuss your options with a DevOps expert? Contact our sales team to evaluate your needs."
          />
        </div>
      </div>
    </div>
  </>
);

export default Content;
