// packages/web-components/src/components/callout-quote/callout-quote.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import styles from './callout-quote.scss';
import DDSCalloutMixin from '../../component-mixins/callout/callout';
import DDSQuote from '../quote/quote';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Callout Data.
 *
 * @element dds-callout-data
 */
@customElement(`${ddsPrefix}-callout-quote`)
class DDSCalloutQuote extends DDSCalloutMixin(DDSQuote) {
  static get stableSelector() {
    return `${ddsPrefix}--callout-quote`;
  }

  static styles = styles;
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSCalloutQuote;

// packages/react/src/components/CalloutQuote/CalloutQuote.js
/**
 * Copyright IBM Corp. 2016, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import Callout from '../../internal/components/Callout/Callout';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import PropTypes from 'prop-types';
import { Quote } from '../Quote';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';
const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * CalloutQuote component.
 */
const CalloutQuote = ({ quote }) => {
  return (
    <div
      className={`${prefix}--callout-quote`}
      data-autoid={`${stablePrefix}--callout-quote`}
    >
      <Callout>
        <Quote {...quote} />
      </Callout>
    </div>
  );
};

CalloutQuote.propTypes = {
  /**
   * Quote object.
   * See [`<Quote>`'s README](http://www.ibm.com/standards/carbon/react/?path=/docs/components-quote--default#props) for full usage details.
   */
  quote: PropTypes.shape({
    markType: PropTypes.oneOf([
      'doubleCurved',
      'singleCurved',
      'doubleAngle',
      'singleAngle',
      'lowHighReversedDoubleCurved',
    ]),
    copy: PropTypes.string.isRequired,
    source: PropTypes.shape({
      heading: PropTypes.string,
      copy: PropTypes.string,
    }),
    cta: PropTypes.shape({
      copy: PropTypes.string,
      type: PropTypes.oneOf(['local', 'external']),
      href: PropTypes.string,
    }),
    inverse: PropTypes.bool,
  }),
};

export default CalloutQuote;
