// packages/web-components/src/components/image-with-caption/image-with-caption.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import '../image/image';
import '../lightbox-media-viewer/lightbox-image-viewer';
import '../button/button';
import ZoomIn20 from 'carbon-web-components/es/icons/zoom--in/20';
import DDSModal from '../modal/modal';
import 'carbon-web-components/es/components/modal/modal-close-button';
import styles from './image-with-caption.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Image With Caption
 *
 * @element dds-image-with-caption
 */

@customElement(`${ddsPrefix}-image-with-caption`)
class DDSImageWithCaption extends LitElement {
  /**
   * The lightbox.
   */
  @property({ type: Boolean, reflect: true })
  lightbox = false;

  /**
   * The image source.
   */
  @property({ reflect: true })
  defaultSrc = '';

  /**
   * The alt text.
   */
  @property({ reflect: true })
  alt = '';

  /**
   * The heading.
   */
  @property({ reflect: true })
  heading = '';

  /**
   * The description.
   */
  @property({ reflect: true })
  copy = '';

  _handleClick() {
    const modal = this.shadowRoot?.querySelector('dds-modal');
    (modal as DDSModal).open = true;
  }

  render() {
    return html`
      ${this.lightbox
        ? html`
            <button class="${prefix}--image-with-caption__image" @click="${this._handleClick}">
              <dds-image alt="${this.alt}" default-src="${this.defaultSrc}" />
              <div class="${prefix}--image-with-caption__zoom-button">
                ${ZoomIn20()}
              </div>
            </button>
            <dds-modal expressive-size="full-width">
              <bx-modal-close-button></bx-modal-close-button>
              <dds-lightbox-image-viewer
                alt="${this.alt}"
                default-src="${this.defaultSrc}"
                description="${this.copy}"
                title="${this.heading}"
              >
              </dds-lightbox-image-viewer>
            </dds-modal>
          `
        : html`
            <dds-image default-src="${this.defaultSrc}" />
          `}
      <p class="${prefix}--image__caption">
        ${this.heading}
      </p>
    `;
  }

  static styles = styles;
}

export default DDSImageWithCaption;

// packages/react/src/components/ImageWithCaption/ImageWithCaption.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React, { useState } from 'react';
import CTALogic from '../CTA/CTALogic';
import cx from 'classnames';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { Image } from '../Image';
import PropTypes from 'prop-types';
import { settings } from 'carbon-components';
import { ZoomIn20 } from '@carbon/icons-react';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * renders background image
 *
 * @param {boolean} props props object
 * @param {boolean} props.inverse inverse
 * @param {object} props.image image object
 * @param {string} props.lightbox launch lightbox on click
 * @param {string} props.heading image caption
 * @param {string} props.copy more detailed description of image
 * @param {string} props.customClassName custom classname
 * @returns {*} picture element
 */
const ImageWithCaption = ({
  inverse,
  image,
  lightbox,
  heading,
  copy,
  customClassName,
}) => {
  const [renderLightBox, openLightBox] = useState(false);

  if (!image) {
    return null;
  }
  const classnames = cx(
    `${prefix}--image-with-caption`,
    { [`${prefix}--image-with-caption--inverse`]: inverse },
    customClassName
  );

  const media = {
    type: 'image',
    src: image.defaultSrc,
    title: heading,
    alt: image.alt,
    description: copy,
  };

  return (
    <div
      className={classnames}
      data-autoid={`${stablePrefix}--image-with-caption`}>
      {CTALogic.launchLightBox(renderLightBox, openLightBox, media)}
      {lightbox ? (
        <button
          aria-label="launch light box media viewer"
          className={`${prefix}--image-with-caption__image`}
          onClick={e => CTALogic.setLightBox(e, openLightBox)}>
          <Image {...image} />
          <div className={`${prefix}--image-with-caption__zoom-button`}>
            <ZoomIn20 aria-label="Zoom In Icon" />
          </div>
        </button>
      ) : (
        <Image {...image} />
      )}
      <p
        className={`${prefix}--image__caption--inverse`}
        data-autoid={`${stablePrefix}--image__caption`}>
        {heading}
      </p>
    </div>
  );
};

ImageWithCaption.propTypes = {
  inverse: PropTypes.bool,
  image: PropTypes.shape(Image.propTypes).isRequired,
  lightbox: PropTypes.bool,
  heading: PropTypes.string,
  copy: PropTypes.string,
  customClassName: PropTypes.string,
};

ImageWithCaption.defaultProps = {
  inverse: false,
  copy: '',
  lightbox: false,
};

export default ImageWithCaption;
