// packages/web-components/src/components/footer/locale-button.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import FocusMixin from 'carbon-web-components/es/globals/mixins/focus.js';
import EarthFilled20 from 'carbon-web-components/es/icons/earth--filled/20.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './footer.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Locale button.
 *
 * @element dds-locale-button
 */
@customElement(`${ddsPrefix}-locale-button`)
class DDSLocaleButton extends StableSelectorMixin(FocusMixin(LitElement)) {
  /**
   * The shadow slot this locale button should be in.
   */
  @property({ reflect: true })
  slot = 'locale-button';

  createRenderRoot() {
    return this.attachShadow({ mode: 'open', delegatesFocus: true });
  }

  render() {
    return html`
      <button id="button" class="${prefix}--btn ${prefix}--btn--secondary ${prefix}--locale-btn">
        <slot></slot>
        ${EarthFilled20()}
      </button>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--locale-btn`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLocaleButton;

// packages/react/src/components/Footer/LocaleButton.js
/**
 * Copyright IBM Corp. 2020, 2022
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React, { useState } from 'react';
import Button from '../../internal/vendor/carbon-components-react/components/Button/Button';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import EarthFilled20 from '@carbon/icons-react/es/earth--filled/20';
import LocaleModal from '../LocaleModal/LocaleModal';
import PropTypes from 'prop-types';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Renders the locale button.
 */
const LocaleButton = ({ displayLang, aria }) => {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className={`${prefix}--locale-btn__container`}>
      <Button
        data-autoid={`${stablePrefix}--locale-btn`}
        className={`${prefix}--locale-btn`}
        kind="tertiary"
        onClick={open}
        renderIcon={EarthFilled20}
        iconDescription="Earth Filled Icon"
        aria-label={aria}>
        {displayLang}
      </Button>

      <LocaleModal isOpen={isOpen} setIsOpen={setIsOpen} />
    </div>
  );

  /**
   * Sets modal state to open
   *
   * @private
   */
  function open() {
    setIsOpen(true);
  }
};

LocaleButton.propTypes = {
  /**
   * Display language for locale button.
   */
  displayLang: PropTypes.string,

  /**
   * `aria-label`` value.
   */
  aria: PropTypes.string,
};

export default LocaleButton;
