// packages/react/src/patterns/blocks/ContentGroupPictograms/ContentGroupPictograms.js
/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import ContentGroup from '../../../internal/components/ContentGroup/ContentGroup';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import { PictogramItem } from '../../../components/PictogramItem';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content group — with pictograms
 *
 * @param {object} props props object
 * @param {object} props.className class Name prop
 * @param {Array} props.items Pictogram item content array
 * @param {string} props.heading Content group — with pictograms title
 * @returns {*}  Content group — with pictograms JSX Component
 */
const ContentGroupPictograms = ({ heading, items, className }) => (
  <div
    data-autoid={`${stablePrefix}--content-group-pictograms`}
    className={classNames(className, `${prefix}--content-group-pictograms`)}>
    <ContentGroup heading={heading}>{_renderItems(items)}</ContentGroup>
  </div>
);

/**
 * Renders the array of items
 *
 * @param {Array} items Array of items for PictogramItem
 * @returns {*} PictogramItem JSX components
 */
const _renderItems = items =>
  items.map((item, index) => (
    <PictogramItem
      className={`${prefix}--content-group-pictograms__item`}
      data-autoid={`${prefix}--content-group-pictograms__item`}
      {...item}
      key={index}
    />
  ));

ContentGroupPictograms.propTypes = {
  heading: PropTypes.string.isRequired,
  items: PropTypes.arrayOf(PropTypes.shape(PictogramItem.propTypes)).isRequired,
  className: PropTypes.string,
};

export default ContentGroupPictograms;

// packages/web-components/src/components/content-group-pictograms/content-group-pictograms.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-pictograms.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group with pictograms
 *
 * @element dds-content-group-pictogram
 */

@customElement(`${ddsPrefix}-content-group-pictograms`)
class DDSContentGroupPictograms extends DDSContentGroup {
  static get stableSelector() {
    return `${ddsPrefix}--content-group-pictograms`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupPictograms;
