// packages/react/src/components/ContentGroupPictograms/ContentGroupPictograms.js
/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import ContentGroup from '../ContentGroup/ContentGroup';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { PictogramItem } from '../PictogramItem';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * Content group — with pictograms.
 */
const ContentGroupPictograms = ({ heading, items, className, copy }) => (
  <div
    data-autoid={`${stablePrefix}--content-group-pictograms`}
    className={classNames(className, `${prefix}--content-group-pictograms`)}>
    <ContentGroup heading={heading} copy={copy}>
      {_renderItems(items)}
    </ContentGroup>
  </div>
);

/**
 * Renders the array of items
 *
 * @param {Array} items Array of items for PictogramItem
 * @returns {*} PictogramItem JSX components
 */
const _renderItems = (items) =>
  items.map((item, index) => (
    <PictogramItem
      className={`${prefix}--content-group-pictograms__item`}
      data-autoid={`${prefix}--content-group-pictograms__item`}
      {...item}
      key={index}
    />
  ));

ContentGroupPictograms.propTypes = {
  /**
   * Main title of Content Group — with Pictograms pattern.
   */
  heading: PropTypes.string.isRequired,

  /**
   * Copy text (enabled for the `markdownToHtml` utility)
   */
  copy: PropTypes.string,

  /**
   * Array of PictogramItems.
   * See [`<PictogramItem>`'s README](http://www.ibm.com/standards/carbon/react/?path=/docs/components-pictogramitem--default#props) for full usage details.
   */
  items: PropTypes.arrayOf(
    PropTypes.shape({
      heading: PropTypes.string.isRequired,
      copy: PropTypes.string.isRequired,
      cta: PropTypes.shape({
        style: PropTypes.oneOf(['text', 'card', 'button', 'feature']),
        type: PropTypes.oneOfType([
          PropTypes.oneOf(['jump', 'local', 'external', 'download', 'video']),
          PropTypes.arrayOf(
            PropTypes.oneOf(['jump', 'local', 'external', 'download', 'video'])
          ),
        ]),
        copy: PropTypes.string,
        href: PropTypes.string,
        customClassName: PropTypes.string,
      }),
      pictogram: PropTypes.shape({
        src: PropTypes.object.isRequired,
      }),
      className: PropTypes.string,
    })
  ).isRequired,

  /**
   * The CSS class name to apply to the top-level element.
   */
  className: PropTypes.string,
};

export default ContentGroupPictograms;

// packages/web-components/src/components/content-group-pictograms/content-group-pictograms.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit-element';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';
import DDSContentGroup from '../content-group/content-group';
import styles from './content-group-pictograms.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content group with pictograms
 *
 * @element dds-content-group-pictogram
 */

@customElement(`${ddsPrefix}-content-group-pictograms`)
class DDSContentGroupPictograms extends DDSContentGroup {
  static get stableSelector() {
    return `${ddsPrefix}--content-group-pictograms`;
  }

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSContentGroupPictograms;
