// packages/web-components/src/components/leadspace/leadspace.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html, svg, property, LitElement } from 'lit-element';
import { classMap } from 'lit-html/directives/class-map';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import { LEADSPACE_TYPE, LEADSPACE_GRADIENT_STYLE_SCHEME, LEADSPACE_SIZE } from './defs';
import styles from './leadspace.scss';
import StableSelectorMixin from '../../globals/mixins/stable-selector';

export { LEADSPACE_TYPE, LEADSPACE_GRADIENT_STYLE_SCHEME };

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The LeadSpace component.
 *
 * @element dds-leadspace
 * @slot action The action (CTA) content.
 * @slot image The image content.
 * @csspart section The first DOM node inside the shadow-root
 */
@customElement(`${ddsPrefix}-leadspace`)
class DDSLeadSpace extends StableSelectorMixin(LitElement) {
  /**
   * Sets background image for leadspace centered
   */
  protected _getBackgroundImage() {
    return this.defaultSrc && this.type === LEADSPACE_TYPE.CENTERED ? `background-image: url(${this.defaultSrc})` : '';
  }

  /**
   * Returns a class-name based on the gradient parameter type
   */
  protected _getGradientClass() {
    return classMap({
      [`${prefix}--leadspace--gradient`]: this.gradientStyleScheme === LEADSPACE_GRADIENT_STYLE_SCHEME.WITH_GRADIENT,
      [`${prefix}--leadspace__overlay`]: true,
    });
  }

  /**
   * Returns a class-name based on the type parameter type
   */
  protected _getTypeClass() {
    return classMap({
      [`${prefix}--leadspace--centered`]: this.type === LEADSPACE_TYPE.CENTERED,
      [`${prefix}--leadspace--centered__image`]: this.type === LEADSPACE_TYPE.CENTERED && this.defaultSrc,
      [`${prefix}--leadspace--productive`]: this.type === LEADSPACE_TYPE.SMALL,
      [`${prefix}--leadspace__section`]: true,
    });
  }

  /**
   * Returns a class-name based on the size parameter size
   */
  protected _getSizeClass() {
    return classMap({
      [`${prefix}--leadspace--medium`]: this.size === LEADSPACE_SIZE.MEDIUM,
    });
  }

  /**
   * Renders Leadspace copy/description
   */
  protected _renderCopy() {
    const { copy } = this;
    return html`
      <div class="${prefix}--leadspace__row">
        <p data-autoid="${ddsPrefix}--leadspace__desc" class="${prefix}--leadspace__desc">
          <slot>${copy}</slot>
        </p>
      </div>
    `;
  }

  /**
   * Renders Leadspace title slot
   */
  protected _renderHeading() {
    const { title } = this;
    return html`
      <slot name="heading">${title}</slot>
    `;
  }

  /**
   *  Renders the image slot or the mobile image for centered leadspace
   */
  protected _renderImage() {
    const { defaultSrc, alt, type } = this;
    if (type === LEADSPACE_TYPE.CENTERED) {
      return html`
        <div data-autoid="${ddsPrefix}--leadspace--centered--mobile__image" class="${prefix}--leadspace--centered--mobile__image">
          <img src="${defaultSrc}" alt="${alt}" />
        </div>
      `;
    }
    return html`
      <slot name="image"></slot>
    `;
  }

  /**
   * The alternate text.
   */
  @property()
  alt = '';

  /**
   * The image source.
   */
  @property({ attribute: 'default-src' })
  defaultSrc = '';

  /**
   * The leadspace copy.
   */
  @property()
  copy = '';

  /**
   * The gradient style sceheme.
   */
  @property({ reflect: true, attribute: 'gradient-style-scheme' })
  gradientStyleScheme = LEADSPACE_GRADIENT_STYLE_SCHEME.WITH_GRADIENT;

  /**
   * The leadspace title.
   */
  @property()
  title = '';

  /**
   *  Leadspace type (small, left, or centered)
   */
  @property({ reflect: true })
  type = LEADSPACE_TYPE.LEFT;

  @property({ reflect: true })
  size = LEADSPACE_SIZE.NONE;

  render() {
    const { gradientStyleScheme, type } = this;
    return html`
      <section style="${this._getBackgroundImage()}" class="${this._getTypeClass()}" part="section">
        <div class="${prefix}--leadspace__container">
          <div class="${this._getGradientClass()}">
            ${gradientStyleScheme === LEADSPACE_GRADIENT_STYLE_SCHEME.NONE
              ? undefined
              : svg`
                <svg
                  class="${prefix}--leadspace__gradient"
                  viewBox="0 0 100 100"
                  preserveAspectRatio="none"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
                  <defs>
                    <linearGradient id="stops" class="${prefix}--leadspace__gradient__stops">
                      ${
                        type === LEADSPACE_TYPE.CENTERED
                          ? svg`
                          <stop offset="0%" />
                          <stop offset="27%" />
                          <stop offset="53%" />
                          <stop offset="80%" />
                        `
                          : svg`
                          <stop offset="0%" />
                          <stop offset="75%" />
                        `
                      }
                    </linearGradient>
                  </defs>
                  <rect class="${prefix}--leadspace__gradient__rect" width="100" height="100" />
                </svg>
              `}
            <div class="${prefix}--leadspace--content__container">
              <div class="${prefix}--leadspace__row">
                ${this._renderHeading()}
              </div>
              <div class="${prefix}--leadspace__content">
                ${this._renderCopy()}
                <slot name="action"></slot>
              </div>
            </div>
          </div>
          ${this._renderImage()}
        </div>
      </section>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--leadspace`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeadSpace;

// packages/react/src/components/LeadSpace/LeadSpace.js
/**
 * Copyright IBM Corp. 2016, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { ButtonGroup } from '../../components/ButtonGroup';
import classnames from 'classnames';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import deprecate from '@carbon/ibmdotcom-utilities/es/utilities/deprecate/deprecate.js';
import { Image } from '../Image';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * renders main class name
 *
 * @param {string} type switches between centered or default
 * @param {string} theme theme of the pattern
 * @returns {string} classnames
 */
const classNames = (type, theme) => {
  return classnames(`${prefix}--leadspace__section`, {
    [`${prefix}--leadspace--${theme}`]: theme,
    [`${prefix}--leadspace--centered`]: type === 'centered',
    [`${prefix}--leadspace--productive`]: type === 'small',
  });
};

/**
 *
 * @param {object} image image
 * @returns {object} returns either image component or the centered image div
 */
function imageClassname(image) {
  return <Image {...image} />;
}

/**
 * Lead space component (left-aligned)
 *
 * @param {object} props props object
 * @param {Array} props.buttons array of buttons for lead space (max 2 buttons)
 * @param {string} props.copy lead space short copy to support the title
 * @param {object} props.image image object with diff source for diff breakpoints
 * @param {string} props.theme theme of the pattern (g100 or white (default))
 * @param {string} props.title lead space title
 * @param {string} props.type type of lead space
 * @returns {*} Lead space component
 */

const LeadSpace = ({
  buttons,
  copy,
  image,
  theme,
  title,
  type,
  size = 'tall',
}) => {
  return (
    <div
      data-autoid={`${stablePrefix}--leadspace`}
      className={classnames(`${prefix}--leadspace`, {
        [`${prefix}--leadspace--medium`]: size === 'medium',
        [`${prefix}--leadspace--tall`]: size === 'tall',
        [`${prefix}--leadspace--super`]: size === 'super',
      })}>
      <section className={classNames(type, theme)}>
        <div className={`${prefix}--leadspace__container`}>
          <div
            className={classnames(`${prefix}--leadspace__overlay`, {
              [`${prefix}--leadspace--gradient`]: image && image.defaultSrc,
            })}>
            {image && image.defaultSrc === true ? (
              undefined
            ) : (
              <svg
                className={`${prefix}--leadspace__gradient`}
                viewBox="0 0 100 100"
                preserveAspectRatio="none"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink">
                <defs>
                  <linearGradient
                    id="stops"
                    className={`${prefix}--leadspace__gradient__stops`}>
                    {type === 'centered' ? (
                      <>
                        <stop offset="0%" />
                        <stop offset="54%" />
                        <stop offset="77%" />
                        <stop offset="100%" />
                      </>
                    ) : (
                      <>
                        <stop offset="0%" />
                        <stop offset="25%" />
                        <stop offset="50%" />
                        <stop offset="75%" />
                      </>
                    )}
                  </linearGradient>
                </defs>
                <rect
                  className={`${prefix}--leadspace__gradient__rect`}
                  width="100"
                  height="100"
                />
              </svg>
            )}
            <div className={`${prefix}--leadspace--content__container`}>
              <div className={`${prefix}--leadspace__row`}>
                <h1 className={`${prefix}--leadspace__title`}>{title}</h1>
              </div>
              <div className={`${prefix}--leadspace__content`}>
                {copy && (
                  <div className={`${prefix}--leadspace__row`}>
                    <p
                      data-autoid={`${stablePrefix}--leadspace__desc`}
                      className={`${prefix}--leadspace__desc`}>
                      {copy}
                    </p>
                  </div>
                )}
                {buttons && buttons.length > 0 && (
                  <ButtonGroup buttons={buttons} />
                )}
              </div>
            </div>
          </div>
          {image && imageClassname(image)}
        </div>
      </section>
    </div>
  );
};

LeadSpace.propTypes = {
  /**
   * Array of button objects to render (max 2).
   * See [`<ButtonGroup>`'s README](http://www.ibm.com/standards/carbon/react/?path=/docs/components-buttongroup--default#button-item) for full usage details.
   */
  buttons: PropTypes.arrayOf(
    PropTypes.shape({
      copy: PropTypes.string.isRequired,
      href: PropTypes.string.isRequired,
      renderIcon: PropTypes.elementType,
    })
  ),

  /**
   * Short copy of LeadSpace.
   */
  copy: PropTypes.string,

  /**
   * Object with different ratio options for corresponding breakpoints.
   * See [`<Image>`'s README](http://www.ibm.com/standards/carbon/react/?path=/docs/components-image--default#props) for full usage details.
   */
  image: PropTypes.shape({
    classname: PropTypes.string,
    sources: PropTypes.arrayOf(
      PropTypes.shape({
        src: PropTypes.string,
        breakpoint: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
      })
    ),
    defaultSrc: PropTypes.string.isRequired,
    alt: PropTypes.string.isRequired,
    longDescription: PropTypes.string,
  }),

  /**
   * Color theme of LeadSpace. Choose from:
   *
   * | Name    | Data Type | Description           |
   * | ------- | --------- | --------------------- |
   * | `white` | String    | Carbon White theme    |
   * | `g10`   | String    | Carbon Gray 10 theme  |
   * | `g90`   | String    | Carbon Gray 90 theme  |
   * | `g100`  | String    | Carbon Gray 100 theme |
   */
  theme: PropTypes.oneOf(['white', 'g10', 'g90', 'g100']),

  /**
   * Title of LeadSpace.
   */
  title: PropTypes.string.isRequired,

  /**
   * Sets the type of Leadspace layout. Choose from:
   *
   * | Name              | Data Type | Description                                         |
   * | ----------------- | --------- | --------------------------------------------------- |
   * | `default`         | String    | Left-aligned - default style of the leadspace title |
   * | `left`            | String    | Left-aligned - large style of the leadspace title   |
   * | `centered`        | String    | Centered type of the LeadSpace                      |
   */
  type: PropTypes.oneOf(['default', 'left', 'centered']),
  /**
   * | Name         | Data Type | Description                           |
   * |--------------|-----------|---------------------------------------|
   * | `tall`/empty | String/-- | Default - tall size of the leadspace  |
   * | `medium`     | String    | Medium - medium size of the leadspace |
   * | `super`      | String    | Super - super size of the leadspace   |
   */
  size: PropTypes.oneOf(['tall', 'medium', 'super']),
};

export default deprecate(
  LeadSpace,
  `
  The Leadspace Small and Leadspace Small With Image variations are now deprecated.
  Please refer to the Carbon for IBM.com documentation for further details.
  https://www.ibm.com/standards/carbon/components/leadspace
`
);
