// packages/react/src/patterns/sections/CTASection/CTASection.js
/**
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import classNames from 'classnames';
import { ContentBlock } from '../../sub-patterns/ContentBlock';
import { ContentItem } from '../../sub-patterns/ContentItem';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * CTASection pattern
 *
 * @param {object} props props object
 * @param {string} props.heading heading string
 * @param {string} props.copy pattern copy
 * @param {object} props.cta CTA component
 * @param {string} props.theme theme name
 * @ param {Array} props.items CTA items to the ContentItem
 * @returns {object} JSX Object
 */
const CTASection = ({ heading, copy, cta, items, theme }) => {
  /**
   * sets the class name based on theme type
   *
   * @private
   * @param {string} theme theme type
   * @returns {string} theme css class names
   */
  const _setTheme = theme => {
    return theme && `${prefix}--cta-section--${theme}`;
  };

  return (
    <section
      data-autoid={`${stablePrefix}--cta-section`}
      className={classNames(`${prefix}--cta-section`, _setTheme(theme))}>
      <ContentBlock heading={heading} copy={copy} cta={cta} />
      <hr className={`${prefix}--horizontal-line`} />
      <div className={`${prefix}--helper-wrapper`}>
        <div className={`${prefix}--content-item-wrapper`}>
          {items.map((item, index) => (
            <ContentItem
              key={index}
              heading={item.heading}
              copy={item.copy}
              cta={item.cta}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

CTASection.propTypes = {
  heading: PropTypes.string.isRequired,
  copy: PropTypes.string.isRequired,
  cta: PropTypes.object,
  theme: PropTypes.string,
  items: PropTypes.arrayOf(
    PropTypes.shape({
      heading: PropTypes.string,
      copy: PropTypes.string,
      cta: PropTypes.shape({
        heading: PropTypes.string,
        copy: PropTypes.string,
        cta: PropTypes.object,
      }),
    })
  ),
};

export default CTASection;

// packages/web-components/src/components/cta-section/cta-section.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css } from 'lit';
import { property } from 'lit/decorators.js';
import parseAspectRatio from '@carbon/ibmdotcom-utilities/es/utilities/parseAspectRatio/parseAspectRatio.js';
import ddsSettings from '../../internal/vendor/@carbon/ibmdotcom-utilities/utilities/settings/settings';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './cta-section.scss';
import DDSContentSection from '../content-section/content-section';
import { carbonElement as customElement } from '../../internal/vendor/@carbon/web-components/globals/decorators/carbon-element';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The CTA SECTION pattern
 *
 * @element dds-cta-section
 */
@customElement(`${ddsPrefix}-cta-section`)
class DDSCTASection extends StableSelectorMixin(DDSContentSection) {
  @property({ attribute: 'logo-ratio' })
  logoRatio?;

  updated(changedProperties) {
    const { logoRatio } = this;
    if (changedProperties.has('logoRatio')) {
      if (logoRatio) {
        const [w, h] = parseAspectRatio(logoRatio);
        this.style.setProperty('--logo-ratio', `${w}/${h}`);
      } else {
        this.style.removeProperty('--logo-ratio');
      }
    }
  }

  static get stableSelector() {
    return `${ddsPrefix}--cta-section`;
  }

  static get styles() {
    return css`
      ${super.styles}${styles}
    `;
  }
}

/* @__GENERATE_REACT_CUSTOM_ELEMENT_TYPE__ */
export default DDSCTASection;
