// packages/react/src/patterns/sub-patterns/LinkList/LinkList.js
/**
 * Copyright IBM Corp. 2016, 2018
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { CTA } from '../../../components/CTA';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import { settings } from 'carbon-components';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 * LinkList Component, for use with items array
 *
 * @param {object} props props object
 * @param {string} props.heading  Heading string
 * @param {Array} props.items array of item
 * @returns {*} JSX LinkList component
 */
const LinkList = ({ heading, items }) => {
  return (
    <div
      className={`${prefix}--link-list`}
      data-autoid={`${stablePrefix}--link-list`}>
      <h4 className={`${prefix}--link-list__heading`}>{heading}</h4>
      <ul className={`${prefix}--link-list__list`}>
        {items.map((cta, index) => {
          return (
            <li className={`${prefix}--link-list__list__CTA`} key={index}>
              <CTA style="card" {...cta} />
            </li>
          );
        })}
      </ul>
    </div>
  );
};

LinkList.propTypes = {
  heading: PropTypes.string.isRequired,
  items: PropTypes.arrayOf(PropTypes.shape(CTA.propTypes)).isRequired,
};

export default LinkList;

// packages/web-components/src/components/link-list/link-list.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { html, customElement, property, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import styles from './link-list.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Link list.
 *
 * @element dds-link-list
 */
@customElement(`${ddsPrefix}-link-list`)
class DDSLinkList extends LitElement {
  @property({ type: String })
  type = 'default';

  // eslint-disable-next-line class-methods-use-this
  protected render() {
    return html`
      <div class="${prefix}--link-list" data-autoid="${(this.constructor as typeof DDSLinkList).stableSelector}">
        <h4 class="${prefix}--link-list__heading"><slot name="heading" /></h4>
        <ul name="list" class="${prefix}--link-list__list ${this.ulClasses()}">
          <slot />
        </ul>
      </div>
    `;
  }

  protected ulClasses() {
    switch (this.type) {
      case 'horizontal':
        return `${prefix}--link-list__list--horizontal`;
      case 'vertical':
        return `${prefix}--link-list__list--vertical`;
      default:
        return `${prefix}--link-list__list--card`;
    }
  }

  static get stableSelector() {
    return `${ddsPrefix}--link-list`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLinkList;
