// packages/web-components/src/components/image/image.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { html, property, internalProperty, customElement, LitElement } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import styles from './image.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Image.
 *
 * @element dds-image
 * @slot long-description - The long description content.
 * @slot icon - The icon content.
 */
@customElement(`${ddsPrefix}-image`)
class DDSImage extends StableSelectorMixin(LitElement) {
  /**
   * The image data, harvested from `<dds-image-item>`.
   */
  @internalProperty()
  private _images: HTMLElement[] = [];

  /**
   * Handles `slotchange` event.
   */
  private _handleSlotChange({ target }: Event) {
    const { selectorItem } = this.constructor as typeof DDSImage;
    this._images = (target as HTMLSlotElement)
      .assignedNodes()
      // Supports `<dds-image><slot></slot></dds-image>` rendered in shadow DOM
      .reduce((acc, node) => {
        if ((node as Element).tagName === 'SLOT') {
          acc.push(...(node as HTMLSlotElement).assignedNodes());
        } else {
          acc.push(node);
        }
        return acc;
      }, [] as Node[])
      .filter(node => node.nodeType === Node.ELEMENT_NODE && (node as Element).matches(selectorItem)) as HTMLElement[];
  }

  /**
   * The alternate text.
   */
  @property()
  alt = '';

  /**
   * The image source.
   */
  @property({ attribute: 'default-src' })
  defaultSrc = '';

  render() {
    const { alt, defaultSrc, _images: images, _handleSlotChange: handleSlotChange } = this;
    return html`
      <slot @slotchange="${handleSlotChange}"></slot>
      <picture>
        ${images.map(
          image => html`<source media="${image.getAttribute('media')}" srcset="${image.getAttribute('srcset')}"></source>`
        )}
        <img class="${prefix}--image__img" src="${defaultSrc}" alt="${alt}" aria-describedby="long-description" loading="lazy" />
      </picture>
      <div id="long-description" class="${prefix}--image__longdescription">
        <slot name="long-description"></slot>
      </div>
      <slot name="icon"></slot>
    `;
  }

  /**
   * A selector that will return image items.
   */
  static get selectorItem() {
    return `${ddsPrefix}-image-item`;
  }

  static get stableSelector() {
    return `${ddsPrefix}--image`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSImage;

// packages/react/src/components/Image/Image.js
/**
 * Copyright IBM Corp. 2016, 2020
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import { baseFontSize, breakpoints } from '@carbon/layout';
import classnames from 'classnames';
import { settings as ddsSettings } from '@carbon/ibmdotcom-utilities';
import PropTypes from 'prop-types';
import React from 'react';
import settings from 'carbon-components/es/globals/js/settings';
import { uniqueid } from '@carbon/ibmdotcom-utilities';

const { stablePrefix } = ddsSettings;
const { prefix } = settings;

/**
 *  sorts media query min-widths order to ensure the
 * browser returns the proper sources and the specified widths
 *
 * @param {Array} sources image sources and min-widths
 *
 * @returns {Array} sorted array of sources
 */
const sortSources = sources => {
  const images = sources.map(elem => {
    if (typeof elem.breakpoint == 'number') {
      return elem;
    } else {
      return {
        breakpoint:
          parseFloat(breakpoints[elem.breakpoint].width) * baseFontSize,
        src: elem.src,
      };
    }
  });
  return images.sort((a, b) => (a.breakpoint > b.breakpoint ? -1 : 1));
};

/**
 * Picture element.
 */
const Image = ({
  classname,
  sources,
  defaultSrc,
  alt,
  longDescription,
  icon: Icon,
}) => {
  if (!defaultSrc || !alt) {
    return null;
  }

  const sortedImages = sources ? sortSources(sources) : [];
  const id = uniqueid(`${prefix}--image-`);
  return (
    <div
      className={`${prefix}--image`}
      data-autoid={`${stablePrefix}--image__longdescription-`}>
      <picture>
        {sortedImages.map((imgSrc, key) => {
          return (
            <source
              media={`(min-width: ${imgSrc.breakpoint}px )`}
              key={key}
              srcSet={imgSrc.src}
            />
          );
        })}
        <img
          className={classnames(`${prefix}--image__img`, classname)}
          src={defaultSrc}
          alt={alt}
          aria-describedby={longDescription ? `${id}` : undefined}
        />
      </picture>
      {longDescription ? (
        <div id={id} className={`${prefix}--image__longdescription`}>
          {longDescription}
        </div>
      ) : null}
      {Icon && <Icon className={`${prefix}--image__icon`} />}
    </div>
  );
};

Image.propTypes = {
  /**
   * The CSS class names.
   */
  classname: PropTypes.string,

  /**
   * Array of image objects. Use below object structure for each items:
   *
   * | Name         | Data Type     | Description                                  |
   * | ------------ | ------------- | -------------------------------------------- |
   * | `src`        | String        | Url of Image.                                |
   * | `breakpoint` | Num OR String | min-width breakpoint to render the image src |
   */
  sources: PropTypes.arrayOf(
    PropTypes.shape({
      src: PropTypes.string,
      breakpoint: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    })
  ),

  /**
   * Default image (usually image for largest breakpoint).
   */
  defaultSrc: PropTypes.string.isRequired,

  /**
   * Alternate text for image component.
   */
  alt: PropTypes.string.isRequired,

  /**
   * Visible to screen readers, hidden from users.
   */
  longDescription: PropTypes.string,

  /**
   * Icon that overlays the image
   */
  icon: PropTypes.element,
};

export default Image;
